### ISSUE TITLE
PSU1.6 - Server will fail to start if plugins are missing from appsettings.json

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#110]
**Describe the bug**

If the Plugins section is missing from appsettings.json, the server will fail to start. 

**To Reproduce**

Delete the Plugins section from appsettings.json

**Expected behavior**

Server should start or provide a good error message. 

**Version**

Version Number: 1.6.0-beta2
Dashboard Framework (if applicable): Any
Operating System: Any

**Logs** 

```
Category: Microsoft.AspNetCore.Hosting.Diagnostics

EventId: 6

 

Application startup exception

 

Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

   at Universal.Server.Services.PluginService..ctor(IConfiguration configuration) in D:\a\universal\universal\src\Universal.Server\Services\PluginService.cs:line 25

   at Universal.Server.Startup.ConfigureServices(IServiceCollection services) in D:\a\universal\universal\src\Universal.Server\Startup.cs:line 54

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)

   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)

   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

**Comment by adamdriscoll** [comment]
Adding a better error message. This is a required setting.
