### ISSUE TITLE
Can't install PowerShell Universal

### ISSUE THREAD

**Issue by potatoqualitee** [ironmansoftware/powershell-universal#1163]
### Steps to Reproduce

Hello,
I installed PowerShell Universal back in November, then later uninstalled it so that I can install the beta. Since then, I have been unable to install any product in any way. Usually it says Access Denied or file doesn't exist.

### Expected behavior

```console
Install works without issue
```

### Actual behavior

```console
Run as normal user or admin


 C:/github❯ Install-PSUServer -Version 3.0.0-beta4                                                                                                                                  Start-Service : Service 'PowerShell Universal (PowerShellUniversal)' cannot be started due to the following error: Cannot start service PowerShellUniversal on computer '.'.
At C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1:177 char:9
+         Start-Service -Name 'PowerShellUniversal'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PowerShell Universal is running on port 5000. View the admin console by visiting http://localhost:5000
[3m7s] C:/github❯ $error
Start-Service : Service 'PowerShell Universal (PowerShellUniversal)' cannot be started due to the following error: Cannot start service PowerShellUniversal on computer '.'.
At C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1:177 char:9
+         Start-Service -Name 'PowerShellUniversal'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

Remove-Item : Cannot find path 'C:\Users\ctrlb\AppData\Local\Temp\Universal.3.0.0-beta4.win7-x64.zip' because it does not exist.
At C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1:165 char:5
+     Remove-Item $Zip -Force -ErrorAction SilentlyContinue
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ctrlb\...a4.win7-x64.zip:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

[32ms] C:/github❯ $error | select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : Microsoft.PowerShell.Commands.ServiceCommandException: Service 'PowerShell Universal (PowerShellUniversal)' cannot be started due to the following error:
                        Cannot start service PowerShellUniversal on computer '.'. ---> System.InvalidOperationException: Cannot start service PowerShellUniversal on computer '.'.
                        ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
                           --- End of inner exception stack trace ---
                           at System.ServiceProcess.ServiceController.Start(String[] args)
                           at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStartService(ServiceController serviceController)
                           --- End of inner exception stack trace ---
TargetObject          : PowerShellUniversal
CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Install-PSUServer, C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1: line 177
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
PSMessageDetails      :
Exception             : System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\ctrlb\AppData\Local\Temp\Universal.3.0.0-beta4.win7-x64.zip' because it
                        does not exist.
                           at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive,
                        ContainerCmdletProvider provider, CmdletProviderContext context)
                           at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths,
                        CmdletProvider& providerInstance)
                           at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext
                        context, CmdletProvider& providerInstance)
                           at Microsoft.PowerShell.Commands.RemoveItemCommand.ProcessRecord()
TargetObject          : C:\Users\ctrlb\AppData\Local\Temp\Universal.3.0.0-beta4.win7-x64.zip
CategoryInfo          : ObjectNotFound: (C:\Users\ctrlb\...a4.win7-x64.zip:String) [Remove-Item], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Install-PSUServer, C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1: line 165
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}



[134ms] C:/github❯ ls C:\Users\ctrlb\AppData\Local\Temp\Universal.3.0.0-beta4.win7-x64.zip
ls : Cannot find path 'C:\Users\ctrlb\AppData\Local\Temp\Universal.3.0.0-beta4.win7-x64.zip' because it does not exist.
At line:1 char:1
+ ls C:\Users\ctrlb\AppData\Local\Temp\Universal.3.0.0-beta4.win7-x64.z ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ctrlb\...a4.win7-x64.zip:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```
```


### Environment data

beta and current versions

Windows 11

Name                           Value
----                           -----
PSVersion                      5.1.22000.651
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.651
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Visuals

![image](https://user-images.githubusercontent.com/8278033/167103394-6da7bbd1-30e5-44cc-a9dd-7be29cbec217.png)

**Comment by potatoqualitee** [comment]
When I manually moved the zip file, it installed but refuses to start

```
Start-Service : Service 'PowerShell Universal (PowerShellUniversal)' cannot be started due to the following error: Cannot start service PowerShellUniversal on computer '.'.
At C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1:177 char:9
+         Start-Service -Name 'PowerShellUniversal'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

PowerShell Universal is running on port 5000. View the admin console by visiting http://localhost:5000
[3m1s] C:/github❯ $error[0] | select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : Microsoft.PowerShell.Commands.ServiceCommandException: Service 'PowerShell Universal (PowerShellUniversal)' cannot be started due to the following error:
                        Cannot start service PowerShellUniversal on computer '.'. ---> System.InvalidOperationException: Cannot start service PowerShellUniversal on computer '.'.
                        ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
                           --- End of inner exception stack trace ---
                           at System.ServiceProcess.ServiceController.Start(String[] args)
                           at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStartService(ServiceController serviceController)
                           --- End of inner exception stack trace ---
TargetObject          : PowerShellUniversal
CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Install-PSUServer, C:\Users\ctrlb\Documents\WindowsPowerShell\Modules\Universal\2.6.2\Universal.psm1: line 177
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

Here's some stuff from Event Viewer

```
Application: Universal.Server.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at Microsoft.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PowerShellUniversal.SQL.DatabaseFeature.InitializeDatabase(IConfiguration configuration) in D:\a\universal\universal\src\PowerShellUniversal.SQL\Plugin.cs:line 51
   at Universal.Server.Services.PluginService..ctor(IConfiguration configuration) in D:\a\universal\universal\src\Universal.Server\Services\PluginService.cs:line 73
   at Universal.Server.Startup.ConfigureServices(IServiceCollection services) in D:\a\universal\universal\src\Universal.Server\Startup.cs:line 70
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Universal.Server.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 69
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Universal.Server.Program.Main(String[] args) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 51
```

then

```
Faulting application name: Universal.Server.exe, version: 1.0.0.0, time stamp: 0x622f78e0
Faulting module name: KERNELBASE.dll, version: 10.0.22000.651, time stamp: 0xd680f8f6
Exception code: 0xe0434352
Fault offset: 0x000000000004474c
Faulting process id: 0x3da8
Faulting application start time: 0x01d8612abe9ecf46
Faulting application path: C:\ProgramData\PowerShellUniversal\Server\Universal.Server.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4648059f-2f8b-4e23-9d1a-d9f17ca39c8a
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: Universal.Server.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at Microsoft.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PowerShellUniversal.SQL.DatabaseFeature.InitializeDatabase(IConfiguration configuration) in D:\a\universal\universal\src\PowerShellUniversal.SQL\Plugin.cs:line 51
   at Universal.Server.Services.PluginService..ctor(IConfiguration configuration) in D:\a\universal\universal\src\Universal.Server\Services\PluginService.cs:line 73
   at Universal.Server.Startup.ConfigureServices(IServiceCollection services) in D:\a\universal\universal\src\Universal.Server\Startup.cs:line 70
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Universal.Server.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 69
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Universal.Server.Program.Main(String[] args) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 51
```

```
Faulting application name: Universal.Server.exe, version: 1.0.0.0, time stamp: 0x622f78e0
Faulting module name: KERNELBASE.dll, version: 10.0.22000.651, time stamp: 0xd680f8f6
Exception code: 0xe0434352
Fault offset: 0x000000000004474c
Faulting process id: 0x349c
Faulting application start time: 0x01d8612c59761402
Faulting application path: C:\ProgramData\PowerShellUniversal\Server\Universal.Server.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6f3d9c1d-3e8d-4440-b63c-e2c674373baa
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 2126025650963684018, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Universal.Server.exe
P2: 1.0.0.0
P3: 622f78e0
P4: KERNELBASE.dll
P5: 10.0.22000.651
P6: d680f8f6
P7: e0434352
P8: 000000000004474c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cbf6621a-6139-421d-95bf-5aa3810dca73.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6a7aa47f-b3f0-4f0b-bc45-28dd8d8ca202.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f56d41de-fd47-4755-b7a9-8d4c8b00a92f.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eba0f7d9-991c-41d6-acd2-1c0bea0f5b87.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2e5983f5-349b-4f38-ad89-c47aca4525e3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Universal.Server_bd976dcf2bf67e86926359d197628bebd9262711_707fd7c8_d277fccb-61ba-4631-b4fd-2e92b1958361

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6f3d9c1d-3e8d-4440-b63c-e2c674373baa
Report Status: 268435456
Hashed bucket: 6c6b0a579e50cdaead812910bd0f1ab2
Cab Guid: 0
```

The SQL Server things probably result from the previous install attempts.

**Comment by potatoqualitee** [comment]
I was going to also give some feedback on the installer but didn't know where so I'll put it here. Generally, when sql related programs are installed, we're given a heads up like "You'll be able to provide the servername, username and password in next pane" or alternatively "This installs localdb and works only for the local user"

**Comment by potatoqualitee** [comment]
sweet, deleting from registry, running `sc.exe delete PowerShellUniversal`, deleting files i could find and rebooting worked!

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/install-issue-on-azure-ad-joined-machine/7132/2
