### ISSUE TITLE
[Profiler Not Working] Powershell Pro Tools for VsCode

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1170]
2022.5.0

```
[5/8/2022 9:31:35 PM] Exception running command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

---> System.Management.Automation.Remoting.PSRemotingTransportException: The background process reported an error with the following message: "The named pipe target process has ended.".

   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()

   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)

   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)

   at System.Management.Automation.PowerShell.Invoke[T]()

   at PowerShellToolsPro.PoshToolsServer.ExecutePowerShellMainRunspace[T](String command) in C:\Users\builder\Desktop\agent\_work\1\s\HostInjection\PoshToolsServer.cs:line 966

   at PowerShellToolsPro.PoshToolsServer.MeasureScript(String fileName) in C:\Users\builder\Desktop\agent\_work\1\s\HostInjection\PoshToolsServer.cs:line 693

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at PowerShellToolsPro.PoshToolsServer.Start(String pipeName) in C:\Users\builder\Desktop\agent\_work\1\s\HostInjection\PoshToolsServer.cs:line 122

PowerShell process exited.

**Comment by adamdriscoll** [comment]
Cannot reproduce. Requesting more information for the person that reported it.
