### ISSUE TITLE
New-UDTextbox -Mask throwing React errors

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#1314]
### Steps to Reproduce

Create a dashboard with the following code inside a modal: 

```
New-UDTextbox -Id 'badgeID' -Label 'Badge Number:' -Mask @('/[0-9]/')
New-UDTextbox -Mask @('+', '1', ' ', '(', '/[1-9]/', '/\d/', '/\d/', ')', ' ', '/\d/', '/\d/', '/\d/', '-', '/\d/', '/\d/', '/\d/', '/\d/') -Label 'Phone #'
```

### Expected behavior

```console
Textbox renders following Mask parameter.
```

### Actual behavior

```console
Textbox does not render, produces an error. 

Error rendering component (mu-textbox)
TypeError: t is not a function

    at t (https://psu.mydomain.com/printers/6729.a82d15a6167de9a5bc70.bundle.js:1:3120)
    at https://psu.mydomain.com/printers/6729.a82d15a6167de9a5bc70.bundle.js:1:431
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/7805.0c2f057afb7441f09826.bundle.js:1:11912
    at https://psu.mydomain.com/printers/7805.0c2f057afb7441f09826.bundle.js:1:20566
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/7805.0c2f057afb7441f09826.bundle.js:1:4793
    at y (https://psu.mydomain.com/printers/6729.a82d15a6167de9a5bc70.bundle.js:1:398)
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:1799925
    at o (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2610608)
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:31055
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:31055
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:1799925
    at o (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2610608)
    at p
    at n (https://psu.mydomain.com/printers/ud-element.6df499cea164875ce03e.bundle.js:1:1375)
    at n (https://psu.mydomain.com/printers/ud-element.6df499cea164875ce03e.bundle.js:1:350)
    at Suspense
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:8313
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:66172
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at t (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2539328)
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:22581
    at l (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:38136)
    at div
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:36624
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:61078
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:64142
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:2:1220
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:102:12207
    at ve (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:130540)
    at Suspense
    at yt (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:138610)
    at u (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:89328)
    at f (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:89046)
    at A (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:89448)
    at ie (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:62765)
    at o (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2567304)
    at https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2568180
    at Dashboard (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:205774)
    at t (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2507951)
    at t (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2509934)
    at div
    at t (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2504680)
    at t (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2499940)
    at o (https://psu.mydomain.com/printers/index.cf7bbe4570e0f17fb874.bundle.js:147:2614224)
```

### Environment data

PSU 3.0.5
Windows Server 2022 - Isolated box from the internet
Using MS Edge 94

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udtextbox-mask-parameter-throwing-react-errors/7353/1

**Comment by adamdriscoll** [comment]
This fix is actually switching to a different react library for textmask. It's waaaaayyy easier to configure and supports unmasking. Documentation will be updated but this is a breaking change (although, it's not working right now).
