### ISSUE TITLE
Roles Web UI is creating roles.ps1 entries without a  -Policies parameter while service startup runs a check that mandates -Policy resulting in admin console unavailability.

### ISSUE THREAD

**Issue by x86Since8088** [ironmansoftware/powershell-universal#1351]
### Steps to Reproduce

I have been having repeat failures of the PowerShell Universal UI for a while now and today one of the critical issues have become appearant.

### Expected behavior

```console
2022-07-13 15:36:51.235 -05:00 [DBG] Reading configuration for Role
2022-07-13 15:36:51.235 -05:00 [DBG] Reading configuration file roles.ps1
2022-07-13 15:36:51.255 -05:00 [DBG] Reading configuration for ExecutionEnvironment
```

### Actual behavior

```console
2022-07-13 15:21:16.061 -05:00 [DBG] File .universal\roles.ps1 changed. Syncing...
2022-07-13 15:21:16.062 -05:00 [DBG] Reading configuration file dashboards.ps1
2022-07-13 15:21:16.330 -05:00 [DBG] Reading configuration file roles.ps1
2022-07-13 15:21:16.415 -05:00 [ERR] Failed to read configuration file. roles.ps1
System.Management.Automation.ParameterBindingException: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
   at UniversalAutomation.PowerShellSerializer`1.Deserialize(String script, IDatabase database, IConfigurationService configService) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\PowerShellSerializer.cs:line 46
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 0
2022-07-13 15:21:16.427 -05:00 [WRN] Failed to sync
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Notification_Identity_IdentityId". The conflict occurred in database "PSWebConfigData", table "dbo.Identity", column 'Id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:bcbe7abf-129c-48af-a419-64b19830e5e2
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at PowerShellUniversal.SQL.SqlTable`1.Insert(T item) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.SQL\Database.cs:line 457
   at Universal.Server.Services.NotificationService.SendNotification(Notification notification) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\NotificationService.cs:line 101
   at Universal.Server.Services.NotificationService.ConfigurationError(String fileName, String message) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\NotificationService.cs:line 163
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 240
   at UniversalAutomation.Services.UniversalConfigurationService.NotifyChange(String fileName) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\UniversalConfigurationService.cs:line 150
2022-07-13 15:21:20.706 -05:00 [INF] Starting groom job.
2022-07-13 15:21:20.707 -05:00 [INF] Groom date is: 6/13/2022 8:21:20 PM
2022-07-13 15:21:20.708 -05:00 [INF] Old jobs: 25
```

### Environment data

Delete Roles.ps1 and restart PowerShell universal to fix the behavior and regain the admin console and other broken services.

**Comment by adamdriscoll** [comment]
It's possible to reproduce this error but it will no longer cause the admin console to become inaccessible to allow for fixing it.
