### ISSUE TITLE
Change default behaviors in configuration scripts to $ErrorActionPreference = 'continue'

### ISSUE THREAD

**Issue by x86Since8088** [ironmansoftware/powershell-universal#1352]
### Steps to Reproduce

I have been having a hell of a time where PowerShell universal breaks fails to provide a UI at all if there is a single error in roles.ps1.  Similarly endpoints, scripts, dashboards and pages show incomplete listings where one error in a single entry prevents many entries from showing if not all.

To test: add a defect of any type to parameters in configuration files.  If you make certain mistakes in roles you will get an error in the log file that does not provide invocation information.

### Expected behavior

```console
See a UI and see all dashboards, endpoints, pages, and scripts.
```

### Actual behavior

```console
The /admin dashboard is offline or there are many/all unlisted dashboards, endpoints, pages, and scripts.



2022-07-13 18:08:49.525 -05:00 [ERR] Failed to read configuration file. roles.ps1
System.Management.Automation.ParameterBindingException: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
   at UniversalAutomation.PowerShellSerializer`1.Deserialize(String script, IDatabase database, IConfigurationService configService) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\PowerShellSerializer.cs:line 46
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 0
2022-07-13 18:08:49.692 -05:00 [ERR] Failure configuring Universal. Some settings from your configuration files may not be applied.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Notification_Identity_IdentityId". The conflict occurred in database "PSWebConfigData", table "dbo.Identity", column 'Id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:a1d5a67c-afd8-4ec1-a34b-1aabe00ca51d
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at PowerShellUniversal.SQL.SqlTable`1.Insert(T item) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.SQL\Database.cs:line 455
   at Universal.Server.Services.NotificationService.SendNotification(Notification notification) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\NotificationService.cs:line 101
   at Universal.Server.Services.NotificationService.ConfigurationError(String fileName, String message) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\NotificationService.cs:line 163
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 240
   at UniversalAutomation.Services.UniversalConfigurationService.Read[T](Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\UniversalConfigurationService.cs:line 317
   at UniversalAutomation.Services.UniversalConfigurationService.SyncAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\UniversalConfigurationService.cs:line 264
   at UniversalAutomation.StartupService.StartAsync(CancellationToken cancellationToken) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\StartupService.cs:line 90
2022-07-13 18:08:49.708 -05:00 [INF] Scheduling git sync service.
```

### Environment data

3.1.0

**Comment by x86Since8088** [comment]
for now I have learned to put $ErrorActionPreference = 'continue'  everywhere to keep things running.  Whenever the UI is used to modify a role, $ErrorActionPreference = 'continue'  is removed from line 1.

**Comment by adamdriscoll** [comment]
This is similar to #102 

I'm surprised ErrorActionPreference continue works because that's the default setting. The issue is when there are terminating errors in the script. That new behavior in the next version will be to fall back to the defaults for roles if the roles.ps1 file cannot be read.

**Comment by x86Since8088** [comment]
Thanks.  I also had to start adding $ErrorActionPreference = 'continue' inside of any -content or similar fields to improve availability.
