### ISSUE TITLE
Unable to create a schedule, "Error" toast message pops up

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#1356]
### Steps to Reproduce

the entry is written to schedules.ps1 but is not visible in the GUI

```
2022-07-14 15:13:18.329 +01:00 [DBG] Reading configuration for Schedule
2022-07-14 15:13:18.329 +01:00 [DBG] Reading configuration file schedules.ps1
2022-07-14 15:13:18.386 +01:00 [ERR] Failed to read configuration file. schedules.ps1
System.Management.Automation.ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalAutomation.RemoteCommand.GetScriptParameters(Script Script) in C:\actions-runner\_work\universal\universal\src\Cmdlets\RemoteCommand.cs:line 39
   at UniversalAutomation.RemoteCommand.GetScriptDynamicParameters(Script script) in C:\actions-runner\_work\universal\universal\src\Cmdlets\RemoteCommand.cs:line 66
   at UniversalAutomation.Cmdlets.NewScheduleCommand.GetDynamicParameters() in C:\actions-runner\_work\universal\universal\src\Cmdlets\NewScheduleCommand.cs:line 102
   at System.Management.Automation.CmdletParameterBinderController.HandleCommandLineDynamicParameters(ParameterBindingException& outgoingBindingException)
   --- End of inner exception stack trace ---
   at UniversalAutomation.PowerShellSerializer`1.Deserialize(String script, IDatabase database, IConfigurationService configService) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\PowerShellSerializer.cs:line 46
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 0
2022-07-14 15:13:18.635 +01:00 [ERR] Failure configuring Universal. Some settings from your configuration files may not be applied.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Notification_Identity_IdentityId". The conflict occurred in database "PSUniversal_v3", table "dbo.Identity", column 'Id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCo```
pyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlD
```ataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunE2022-07-14 15:13:18.329 +01:00 [DBG] Reading configuration for Schedule
2022-07-14 15:13:18.329 +01:00 [DBG] Reading configuration file schedules.ps1
2022-07-14 15:13:18.386 +01:00 [ERR] Failed to read configuration file. schedules.ps1
System.Management.Automation.ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalAutomation.RemoteCommand.GetScriptParameters(Script Script) in C:\actions-runner\_work\universal\universal\src\Cmdlets\RemoteCommand.cs:line 39
   at UniversalAutomation.RemoteCommand.GetScriptDynamicParameters(Script script) in C:\actions-runner\_work\universal\universal\src\Cmdlets\RemoteCommand.cs:line 66
   at UniversalAutomation.Cmdlets.NewScheduleCommand.GetDynamicParameters() in C:\actions-runner\_work\universal\universal\src\Cmdlets\NewScheduleCommand.cs:line 102
   at System.Management.Automation.CmdletParameterBinderController.HandleCommandLineDynamicParameters(ParameterBindingException& outgoingBindingException)
   --- End of inner exception stack trace ---
   at UniversalAutomation.PowerShellSerializer`1.Deserialize(String script, IDatabase database, IConfigurationService configService) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\PowerShellSerializer.cs:line 46
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 0
2022-07-14 15:13:18.635 +01:00 [ERR] Failure configuring Universal. Some settings from your configuration files may not be applied.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Notification_Identity_IdentityId". The conflict occurred in database "PSUniversal_v3", table "dbo.Identity", column 'Id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:bcf86715-80e3-46b7-8d53-e48f8c8802ab

xecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:bcf86715-80e3-46b7-8d53-e48f8c8802ab

```

### Expected behavior

```console
schedule created
```

### Actual behavior

```console
nothing created
```

### Environment data

3.1.0

**Comment by adamdriscoll** [comment]
@alexrgreenwood - I can't reproduce this one. Do you see this with any schedule you try to create?

**Comment by alexrgreenwood** [comment]
yes any type of schedule - also get similar error on 3.1.2 on ubuntu (the notification works)
seems to think cronExpression is null but has written it into schedules.ps1
New-PSUSchedule -Cron "* * * * *" -Script "test.ps1" -Credential "Default" -Name "dsdfs"

```
18:56:46 DBG] Done attempting to validate the bound parameter 'schedule' of type 'PowerShellUniversal.Schedule'.
[18:56:46 DBG] Reading configuration for Schedule
[18:56:46 DBG] Reading configuration file schedules.ps1
[18:56:46 INF] Removing job 1
[18:56:46 INF] Scheduling script 1 on schedule  with time zone Europe/London.
[18:56:46 INF] Scheduling job '1' with schedule  on time zone Europe/London
[18:56:46 ERR] Failed to schedule job. Value cannot be null. (Parameter 'cronExpression') 
[18:56:46 ERR] Failed to read configuration file. schedules.ps1
System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalAutomation.JobService.AddOrUpdateRecurringJob(Script script, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobService.cs:line 319
   at UniversalAutomation.JobService.ScheduleJob(Script script, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobService.cs:line 279
   at UniversalAutomation.Services.SchedulesConfigurationScript.OnReadAfterAddAsync(Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Schedules.cs:line 61
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 212
[18:56:46 DBG] List of registered output formatters, in the following order: ["Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter"]
[18:56:46 DBG] No information found on request to perform content negotiation.
[18:56:46 DBG] Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
[18:56:46 DBG] Attempting to select the first formatter in the output formatters list which can write the result.
[18:56:46 DBG] Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter' and content type 'text/plain' to write the response.
[18:56:46 INF] Executing BadRequestObjectResult, writing value of type 'System.String'.
[18:56:46 DBG] The response will be compressed with 'br'.
[18:56:46 INF] Executed action UniversalAutomation.ScheduleController.Post (Universal.Server) in 59.713ms
[18:56:46 INF] Executed endpoint 'UniversalAutomation.ScheduleController.Post (Universal.Server)'
[18:56:46 DBG] Connection id "0HMJ6H5A9KEIH" completed keep alive response.
[18:56:46 INF] Request finished HTTP/1.1 POST http://localhost:5000/api/v1/schedule application/json;charset=UTF-8 166 - 400 - text/plain;+charset=utf-8 70.7027ms
[18:56:46 INF] Request starting HTTP/1.1 GET http://localhost:5000/api/v1/notification/last - -
[18:56:46 DBG] AuthenticationScheme: Cookies was successfully authenticated.
[18:56:46 DBG] The request path /api/v1/notification/last does not match a supported file type
[18:56:46 DBG] The request path  does not match the path filter

```

**Comment by alexrgreenwood** [comment]
what is the latest version ? i see 3.1.2 for download , and 3.2.0 in the nightly builds ?

**Comment by alexrgreenwood** [comment]
on 3.1.3 i get 
```
2022-07-15 19:43:51.137 +01:00 [DBG] Reading configuration file schedules.ps1
2022-07-15 19:43:51.203 +01:00 [ERR] Failed to read configuration file. schedules.ps1
System.Management.Automation.ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Database was not found. This cmdlet can only be run in this mode when configuring PSU.
 ---> System.Exception: Database was not found. This cmdlet can only be run in this mode when configuring PSU.
   at UniversalAutomation.RemoteCommand.GetScriptParameters(Script Script) in C:\actions-runner\_work\universal\universal\src\Cmdlets\RemoteCommand.cs:line 42
   at UniversalAutomation.RemoteCommand.GetScriptDynamicParameters(Script script) in C:\actions-runner\_work\universal\universal\src\Cmdlets\RemoteCommand.cs:line 70
   at UniversalAutomation.Cmdlets.NewScheduleCommand.GetDynamicParameters() in C:\actions-runner\_work\universal\universal\src\Cmdlets\NewScheduleCommand.cs:line 102
   at System.Management.Automation.CmdletParameterBinderController.HandleCommandLineDynamicParameters(ParameterBindingException& outgoingBindingException)
   --- End of inner exception stack trace ---
   at UniversalAutomation.PowerShellSerializer`1.Deserialize(String script, IDatabase database, IConfigurationService configService) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\PowerShellSerializer.cs:line 45
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 0

```

**Comment by adamdriscoll** [comment]
Interesting. I added the new error message in there because I was suspecting that is what the null was coming from. That said, I can't imagine why that's happening. Do you have some time for a Zoom call next week to look at this together? You can email me at adam@ironmansoftware.com

**Comment by adamdriscoll** [comment]
This is being caused by: #1383 - I'll close both issues once this is fixed.
