### ISSUE TITLE
One-time jobs that run longer than 24 hours may invoke a 2nd unwanted instance of the job under a new Job ID

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1465]
### Steps to Reproduce

> Jobs that run for more than 24 hours get invoked again under the same UA Job ID. The original process is still running and a new instance is invoked. When I canceled the Job in UA both process were still running. Had to close both process manually via task manager.

Same issue as reported at https://forums.ironmansoftware.com/t/jobs-running-for-more-than-24-hours-seem-to-get-lost/7159/7

Below is a log snippet

```
2022-08-03 13:09:16.306 -05:00 [ERR] Error in job thread
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at LiteDB.Engine.LockService.EnterTransaction()
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at UniversalAutomation.ExecutionService.<>c__DisplayClass19_0.<<ExecutePowerShell>b__5>d.MoveNext() in D:\a\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 611
```

* internally reported issue

### Actual behavior

```console
After a one-time job has run for more than 24 hours, a 2nd unwanted instance of the job may be created under a new Job ID.
```

### Expected behavior

```console
A PSU job should never create a 2nd unwanted instance of the job under a new Job ID.
```

### Environment data

PSU 2.10.2

**Comment by DataTraveler1** [comment]
@adamdriscoll - Updated the title and behavior in this issue to try to clarify it

Thank you for patience to the colleague who originally reported this.

**Comment by DataTraveler1** [comment]
@adamdriscoll - I have an important update for this. I was able to recreate this issue directly. Full logs will be sent separately. Steps are below:

1) Configure a one-time schedule to run a script which executes a loop that lasts for more than 24 hours and outputs something unique with each loop (e.g. every 30 minutes).

After the job surpasses 24-hours in duration, additional processes/instances will be spawned Thus, with each loop you will begin to have two outputs of something unique instead of 1.

```
2022-08-24 18:06:10.990 -06:00 [INF] Error executing job 33: Cannot insert duplicate key in unique index '_id'. The duplicate value is '{"f":"$/joblog/33","n":0}'.    at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at LiteDB.LiteFileStream`1.WriteChunks(Boolean flush)
   at LiteDB.LiteFileStream`1.Flush()
   at LiteDB.LiteFileStream`1.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at LiteDB.LiteStorage`1.Upload(TFileId id, String filename, Stream stream, BsonDocument metadata)
   at UniversalAutomation.FileStorage`1.Flush(T item) in C:\actions-runner\_work\universal\universal\src\UniversalAutomation.LiteDBv5\LiteDBDatabase.cs:line 456
   at UniversalAutomation.ExecutionService.TryExecute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 394
```

Note: This was only tested in PSU 2.x

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/jobs-running-for-more-than-24-hours-seem-to-get-lost/7159/10
