### ISSUE TITLE
Api Endpoint cant have 2 variables in url

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/powershell-universal#1474]
### Steps to Reproduce

create a new endpoint with 2 variables in it -url "/api/:one/:two"

### Expected behavior

```console
it should work.
```

### Actual behavior

```console
Admin interface will then throw:

`TypeError: Cannot read properties of undefined (reading 'includes')

    at be (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/main.982c33f0.chunk.js:1:138325)
    at section
    at https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:903002
    at a (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:902572)
    at section
    at https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:903002
    at a (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:902572)
    at wt (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/main.982c33f0.chunk.js:1:160344)
    at d (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:387529)
    at p (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:387857)
    at h (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:387594)
    at u (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:378017)
    at n (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:3092525)
    at Suspense
    at u (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/main.982c33f0.chunk.js:1:9087)
    at h (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/main.982c33f0.chunk.js:1:136707)
    at s (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:934721)
    at c (https://casedashboard.prod.inf.nc.nchosting.dk:5001/admin/static/js/16.43767b65.chunk.js:2:652657)
    at va`
```

### Environment data

PU: 3.2.1
Powershell: 7.2.2
Windows Server 2019

### Visuals

![image](https://user-images.githubusercontent.com/14300946/184374415-dddf50db-0934-4129-af23-d32907afa5ed.png)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/api-with-2-variables-in-url-break-it/7593/1

**Comment by McAndersDK** [comment]
Okey, this is only a problem IF the variables are created under /api/
if I add another folder like 
/api/bla/:var/:var
or
/apis/:var/:var
there is no issues

**Comment by adamdriscoll** [comment]
The reason this is happening is that the URL is matching all the management API URLs so whenever we call something like `/api/v1/accessible` from the admin console, it matches the `/api/:var/:var2` endpoint and returns data we aren't expecting. This will cause all kinds of issues. 

I'm going to move this out of the current milestone since we will need to do some work to address this and it's a bit of a big change.

**Comment by McAndersDK** [comment]
an easy fix could just be to make a blacklist of urls that cant be used as it's used by PU?
atleast this is possible in the UI, much harder if one do it by powershell code, but I guess a dynamic parameter check could solve that also? :)

**Comment by adamdriscoll** [comment]
We should definitely do this. I think we have an open issue to improve the API validation and I can link this to that when I find it.

**Comment by adamdriscoll** [comment]
This will be resolved in 2026.1.4.
