### ISSUE TITLE
New-UDIcon "haykal" and others crashs dashboard

### ISSUE THREAD

**Issue by lubeda** [ironmansoftware/powershell-universal#1480]
### Steps to Reproduce

New-UDDashboard -Title 'PowerShell Universal' -Content {
 new-udicon haykal   
}

### Expected behavior

```console
Display the icon haykal
```

### Actual behavior

```console
One or more errors occurred

Unknown icon

   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at UniversalDashboard.Execution.PowerShellExecutionService.ExecuteEndpoint(ExecutionContext context, AbstractEndpoint endpoint, List`1 nonTerminatingErrors) in C:\actions-runner\_work\universal\univer
```

### Environment data

Powershell universal 3.20 on all platforms

**Comment by lubeda** [comment]
There are more icons with this behavior. i used this code to list all icons:

`$Icons = [Enum]::GetNames([UniversalDashboard.Models.FontAwesomeIcons]) 
    
    foreach ($i in $Icons) {    
        if (@("none", "haykal") -notcontains $i) {
           
                New-UDErrorBoundary -Content {
                    New-UDChip -Label $i -Icon (New-UDIcon -Icon  $i)
                }
        }
    }`

**Comment by adamdriscoll** [comment]
This isn't a support icon in FontAwesome 6. You should use Find-UDIcon to look up the supported irons or the FontAwesome.io website.
