### ISSUE TITLE
New-UDForm with -Schema gives an error since a few versions

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/powershell-universal#1496]
### Steps to Reproduce

New-UDForm with -Schema doesnt seem to work correctly anymore, since a few versions. My code is:

```powershell
New-UDForm -Id 'formExtraGuestDrives' -Schema @{
                            title = "Extra guest drives (press submit to save)"
                            type  = "array"
                            items = @{
                                type       = "object"
                                properties = @{
                                    driveLetter = @{
                                        type = "string"
                                        enum = (65..90) | Foreach-Object { [char]$_ } | Where-Object {$_ -notin 'A','C'} # alphabet
                                    }
                                    capacityGB    = @{
                                        type = "integer"
                                    }
                                }
                            }
                        } -OnSubmit {
...
```

### Expected behavior

```console
Rendering the UD-Form with -Schema
```

### Actual behavior

```console
It doesnt render, except it gives an error:

Error rendering component (mu-schema-form)
TypeError: Cannot read properties of null (reading 'ui:rootFieldId')

    at Form (https://fqdn/dashboardname/vendors-node_modules_rjsf_material-ui_dist_material-ui_esm_js.5e21111148a854ac9690.bundle.js:274903:5)
    at https://fqdn/dashboardname/vendors-node_modules_rjsf_material-ui_dist_material-ui_esm_js.5e21111148a854ac9690.bundle.js:281594:23
    at highOrderComponent (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51771:55)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at Grid (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:30709:87)
    at UDGrid (https://fqdn/dashboardname/Components_grid_jsx.1d7db2fb2b85af6f2f52.bundle.js:24:16)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at Grid (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:30709:87)
    at UDGrid (https://fqdn/dashboardname/Components_grid_jsx.1d7db2fb2b85af6f2f52.bundle.js:24:16)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at highOrderComponent (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51771:55)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at div
    at highOrderComponent (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51771:55)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at AccordionDetails (https://fqdn/dashboardname/vendors-node_modules_mui_material_AccordionDetails_AccordionDetails_js-node_modules_mui_mater-6fe6fb.6a13b2922070239f24ce.bundle.js:57:82)
    at div
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at Transition (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:93501:30)
    at Collapse (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:27819:82)
    at div
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at Paper (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:33594:82)
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:190:66
    at Accordion (https://fqdn/dashboardname/vendors-node_modules_mui_material_AccordionDetails_AccordionDetails_js-node_modules_mui_mater-6fe6fb.6a13b2922070239f24ce.bundle.js:529:83)
    at UDExpansionPanel (https://fqdn/dashboardname/Components_expansion-panel_jsx.8af839e795e896fc5150.bundle.js:52:17)
    at div
    at AccordionGroup (https://fqdn/dashboardname/Components_expansion-panel_jsx.8af839e795e896fc5150.bundle.js:122:17)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at highOrderComponent (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51771:55)
    at ErrorBoundary (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49994:197)
    at Suspense
    at main
    at UDPage (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:47703:23)
    at highOrderComponent (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51771:55)
    at Route (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:87692:29)
    at Switch (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:87898:29)
    at div
    at Suspense
    at highOrderComponent (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51771:55)
    at Suspense
    at InnerThemeProvider (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:43026:70)
    at ThemeProvider (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:41364:5)
    at ThemeProvider (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:43046:5)
    at StyledEngineProvider (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:41549:5)
    at n (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:100616:58)
    at https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:100616:1060
    at Dashboard (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:51098:22)
    at Route (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:87692:29)
    at Switch (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:87898:29)
    at div
    at Router (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:87323:30)
    at BrowserRouter (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:86948:35)
    at App (https://fqdn/dashboardname/index.b40065df8e2fdc762537.bundle.js:49541:197)
```

### Environment data

PowerShell Universal 3.2.3, OS: Win 2019, latest Dashboard Framework

### Visuals

![pic](https://user-images.githubusercontent.com/32512939/185334513-18593c24-8d38-464c-b30c-37d1cb685268.png)

**Comment by adamdriscoll** [comment]
@gitbute - I can reproduce this. You can work around it by defining an empty hashtable in the -UiSchema property. 

```
New-UDForm -Id 'formExtraGuestDrives' -Schema @{
                            title = "Extra guest drives (press submit to save)"
                            type  = "array"
                            items = @{
                                type       = "object"
                                properties = @{
                                    driveLetter = @{
                                        type = "string"
                                        enum = (65..90) | Foreach-Object { [char]$_ } | Where-Object {$_ -notin 'A','C'} # alphabet
                                    }
                                    capacityGB    = @{
                                        type = "integer"
                                    }
                                }
                            }
                        } -UiSchema @{} -OnSubmit {}
```

**Comment by gitbute** [comment]
@adamdriscoll 

Thanks for the workaround - i can confirm that it works on my end too 👍
