### ISSUE TITLE
On start of Visual Studio 2019 VS Powershell Tools gives popup error: The named pipe target process has ended.

### ISSUE THREAD

**Issue by abelbraaksma** [ironmansoftware/powershell-universal#16]
When I open Visual Studio 2019, it suddenly started showing the following error in a popup window, essentiall **The named pipe target process has ended.**:

```

---------------------------
PowerShell Tools for Visual Studio Error
---------------------------
Failed to initialize PowerShell Tools for Visual StudioSystem.Management.Automation.Remoting.PSRemotingTransportException: The background process reported an error with the following message: "The named pipe target process has ended.".
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at PowerShellTools.HostService.ServiceManagement.Debugging.PowerShellDebuggingService.InitializeRunspace(Int32 processId, PSHost psHost, Boolean sta)
   at PowerShellTools.HostService.ServiceManagement.Debugging.PowerShellDebuggingService..ctor(IDebugEngineCallback callback, Int32 processId, Boolean sta)
   at PowerShellTools.ServiceManagement.ConnectionManager.OpenClientConnection()
   at PowerShellTools.ServiceManagement.ConnectionManager..ctor()
   at PowerShellTools.PowerShellToolsPackage.<InitializePowerShellHostAsync>d__44.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.PowerShellToolsPackage.<InitializeInternalAsync>d__37.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.PowerShellToolsPackage.<InitializeAsync>d__33.MoveNext()
```

Sometimes it shows a different error, namely **Pipe is broken**:

```
---------------------------
PowerShell Tools for Visual Studio Error
---------------------------
Failed to initialize PowerShell Tools for Visual StudioSystem.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.WriteLine(String value)
   at System.Management.Automation.Remoting.OutOfProcessTextWriter.WriteLine(String data)
   at System.Management.Automation.Remoting.Client.OutOfProcessClientCommandTransportManager.CreateAsync()
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreatePowerShellOnServerAndInvoke(ClientRemotePowerShell shell)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreatePowerShellOnServerAndInvoke(ClientRemotePowerShell shell)
   at System.Management.Automation.PowerShell.CoreInvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state, PSDataCollection`1 asyncResultOutput)
   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.RemoteDebugger.SetDebugMode(DebugModes mode)
   at PowerShellTools.HostService.ServiceManagement.Debugging.PowerShellDebuggingService.InitializeRunspace(Int32 processId, PSHost psHost, Boolean sta)
   at PowerShellTools.HostService.ServiceManagement.Debugging.PowerShellDebuggingService..ctor(IDebugEngineCallback callback, Int32 processId, Boolean sta)
   at PowerShellTools.ServiceManagement.ConnectionManager.OpenClientConnection()
   at PowerShellTools.ServiceManagement.ConnectionManager..ctor()
   at PowerShellTools.PowerShellToolsPackage.<InitializePowerShellHostAsync>d__44.MoveNext()

   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.PowerShellToolsPackage.<InitializeInternalAsync>d__37.MoveNext()

   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.PowerShellToolsPackage.<InitializeAsync>d__33.MoveNext()
```

--------------

Essentially there's always an error, and I cannot use the "Powershell Interactive Window". I suspect it has something to do with a port that's expected to be open but isn't, but the error doesn't disclose any such information so I have no idea where to look.

Here's a screenshot of the same:

![image](https://user-images.githubusercontent.com/16015770/100547157-7d49b400-3265-11eb-964c-c02b8f1b1c73.png)

**Comment by abelbraaksma** [comment]
Since we're now in VS 2022, I haven't seen the issue come back again, so I'm gonna close this. I haven't seen any logs in the Event Viewer, that I recall, but that's moot now.
