### ISSUE TITLE
Session Timeout login results in error

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1751]
### Steps to Reproduce

Steps:
- Setting inside the editor for an api
- Wait for the session to time out
- click the log in/refresh button
- Page load Error

### Expected behavior

```console
no error
```

### Actual behavior

```console
TypeError: Cannot read properties of undefined (reading 'startsWith')

    at B (https://dev.psu.domain.com/psuSandbox/admin/static/js/33.7c7f00fb.chunk.js:1:1518)
    at d (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389246)
    at p (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389574)
    at c
    at d (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389246)
    at p (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389574)
    at n (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:3109673)
    at Suspense
    at u (https://dev.psu.domain.com/psuSandbox/admin/static/js/main.899d13a6.chunk.js:1:52982)
    at main
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:911817
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:911648
    at section
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:912052
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:911648
    at div
    at div
    at t (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:2880341)
    at ve (https://dev.psu.domain.com/psuSandbox/admin/static/js/main.899d13a6.chunk.js:1:140933)
    at section
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:912052
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:911648
    at section
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:912052
    at https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:911648
    at Bt (https://dev.psu.domain.com/psuSandbox/admin/static/js/main.899d13a6.chunk.js:1:159506)
    at d (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389246)
    at p (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389574)
    at h (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:389311)
    at u (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:377284)
    at n (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:3109673)
    at Suspense
    at u (https://dev.psu.domain.com/psuSandbox/admin/static/js/main.899d13a6.chunk.js:1:52982)
    at m (https://dev.psu.domain.com/psuSandbox/admin/static/js/main.899d13a6.chunk.js:1:131891)
    at s (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:940449)
    at c (https://dev.psu.domain.com/psuSandbox/admin/static/js/17.a9efa917.chunk.js:2:665677)
    at va
```

### Environment data

PSU: 3.5.5
IIS Nested Site

### Visuals

![image](https://user-images.githubusercontent.com/1987296/203399779-fa0122d6-fbdb-45d5-acdd-b3840f6b104b.png)

**Comment by Omzig** [comment]
THANK YOU SO MUCH!!!! i cannot wait till 3.6 is out :p
