### ISSUE TITLE
Initialize.ps1 cannot load NuGet provider

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#1784]
### Steps to Reproduce

Create Initialize.ps1, attempt to install module

### Expected behavior

```console
Module is installed
```

### Actual behavior

```console
System.Management.Automation.MethodInvocationException: Exception calling "ShouldContinue" with "2" argument(s): "A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: This version of PowerShellGet requires minimum version '2.8.5.201' of NuGet provider to publish an item to NuGet-based repositories. The NuGet provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or 'C:\Users\svc.PSUniversal\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import the NuGet provider now?"
 ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: This version of PowerShellGet requires minimum version '2.8.5.201' of NuGet provider to publish an item to NuGet-based repositories. The NuGet provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or 'C:\Users\svc.PSUniversal\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import the NuGet provider now?
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.ThrowPromptNotInteractive(String promptMessage)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt, Boolean hasSecurityImpact)
   at System.Management.Automation.MshCommandRuntime.DoShouldContinue(String query, String caption, Boolean hasSecurityImpact, Boolean supportsToAllOptions, Boolean& yesToAll, Boolean& noToAll)
   at System.Management.Automation.MshCommandRuntime.ShouldContinue(String query, String caption)
   at System.Management.Automation.Cmdlet.ShouldContinue(String query, String caption)
   at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object , Object )
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```
```


### Environment data

PSU v3.5.5

NuGet provider exists:
C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll

### Visuals

_No response_

**Comment by adamdriscoll** [comment]
I wonder why it's looking for an older version. If you put this at the top of the script does it work? 

```
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
```

**Comment by realslacker** [comment]
I tried that first, it didn't seem to help.

**Comment by adamdriscoll** [comment]
One thing that I would suggest trying is using the PSGetv3 cmdlets. We ship v3 with PSU. 

```
Install-PSResource -Name "MyModule" 
```

**Comment by realslacker** [comment]
Using Install-PSResource worked after some initial frustration caused by me using the latest version to test and PSU including beta 12... but I got it working the way I want. Thanks!
