### ISSUE TITLE
3.6.1 Issue reinstalling server

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1819]
### Steps to Reproduce

Tried to re-install PSU server with PSU 3.6.1, the server are already in the SQL DB but now I can't seem to get it up and running again.

Error log

````
2022-12-14 09:13:22.061 +01:00 [WRN] Failed to process the job '54018': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:33.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateScope()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.CreateScope()
   at Hangfire.AspNetCore.AspNetCoreJobActivator.BeginScope(JobActivatorContext context)
   at Hangfire.JobActivator.BeginScope(PerformContext context)
   at Hangfire.Server.CoreBackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_0.<PerformJobWithFilters>b__0()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_1.<PerformJobWithFilters>b__2()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
   at Hangfire.Server.BackgroundJobPerformer.<>c__DisplayClass9_1.<PerformJobWithFilters>b__2()
   at Hangfire.Server.BackgroundJobPerformer.PerformJobWithFilters(PerformContext context, IEnumerable`1 filters)
   at Hangfire.Server.BackgroundJobPerformer.Perform(PerformContext context)
   at Hangfire.Server.Worker.PerformJob(BackgroundProcessContext context, IStorageConnection connection, String jobId)

````

### Expected behavior

```console
That it will work
```

### Actual behavior

```console
It don't work the service are stopped
```

### Environment data

psu 3.6.1
sql 2019
win server 2022
ps 7.3.1

**Comment by adamdriscoll** [comment]
Can you send or upload a full log? I'm not sure this is exactly why the server isn't starting. Also, you might want to look in Event Viewer to see if anything is listed there.

**Comment by rwidmark** [comment]
> Can you send or upload a full log? I'm not sure this is exactly why the server isn't starting. Also, you might want to look in Event Viewer to see if anything is listed there. 

Did wipe it, but isolated the issue to the git in sql.

**Comment by adamdriscoll** [comment]
Did you have git configured prior to git to upgrading and switch over to SQL or was this fresh?

**Comment by rwidmark** [comment]
> Did you have git configured prior to git to upgrading and switch over to SQL or was this fresh?

iI did have git configured in the appsettings.json file before upgrade and switch over to SQL.
But after dropping the tables in the SQL it worked fine again so my guess it was some kind of conflict there somehow.
It didn't matter if I did remove the settings for git or not in appsettings.json
