### ISSUE TITLE
Maps broken?

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1985]
### Steps to Reproduce

i am getting an error when using the doc for heatmaps:

https://docs.powershelluniversal.com/userinterfaces/dashboards/components/data-visualization/map
```powershell
New-UDMap -Endpoint {
    New-UDMapRasterLayer -TileServer 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png' 
    New-UDMapHeatmapLayer -Points @(
        @(-37.9019339833, 175.3879181167, "625"),
        @(-37.90920365, 175.4053418167, "397"),
        @(-37.9057407667, 175.39478875, "540"),
        @(-37.9243174333, 175.4220341833, "112"),
        @(-37.8992012333, 175.3666729333, "815"),
        @(-37.9110874833, 175.4102195833, "360"),
        @(-37.9027096, 175.3913196333, "591"),
        @(-37.9011183833, 175.38410915, "655"),
        @(-37.9234701333, 175.4155696333, "181"),
        @(-37.90254175, 175.3926162167, "582"),
        @(-37.92450575, 175.4246711167, "90"),
        @(-37.9242924167, 175.4289432833, "47"),
        @(-37.8986079833, 175.3685293333, "801")
    )
} -Height '100vh'
```

### Expected behavior

```console
a map
```

### Actual behavior

```console
no map and an error:

Error rendering component (ud-map)
TypeError: this.state.features.map is not a function

    at UDMap (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/Components_map_map_jsx.9153e966cc5f5368842c.bundle.js:63:197)
    at ErrorBoundary (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:83600:197)
    at Suspense
    at div
    at UDElementContent (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/ud-element.2a35579d72d4a13f81d5.bundle.js:140:197)
    at UdElement (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/ud-element.2a35579d72d4a13f81d5.bundle.js:48:197)
    at Suspense
    at main
    at UDPage (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:80730:23)
    at highOrderComponent (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:85582:55)
    at Route (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:122602:29)
    at Switch (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:122808:29)
    at div
    at Suspense
    at highOrderComponent (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:85582:55)
    at Suspense
    at InnerThemeProvider (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:44155:70)
    at ThemeProvider (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:42493:5)
    at ThemeProvider (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:44175:5)
    at StyledEngineProvider (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:42678:5)
    at n (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:135974:58)
    at https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:135974:1060
    at Dashboard (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:84529:22)
    at Route (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:122602:29)
    at Switch (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:122808:29)
    at div
    at Router (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:122233:30)
    at BrowserRouter (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:121858:35)
    at App (https://dev.psu.jhacorp.com/psuSandbox/dashboard/psu-themes/index.1f22647572be8364e77c.bundle.js:82595:197)
```

### Environment data

PSU: 3.7.7

### Visuals

![image](https://user-images.githubusercontent.com/1987296/214400720-d57dc695-85a9-403c-8cd1-efaff6d7fe74.png)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/error-loading-udmap/8453/5

**Comment by adamdriscoll** [comment]
We have a partial fix for this but the tile layer isn't showing up properly so still tracking down what is happening. honestly, not sure why this works on the demo site.
