### ISSUE TITLE
Error With MU-List-Item and Single Child Item

### ISSUE THREAD

**Issue by axisfx24** [ironmansoftware/powershell-universal#2152]
### Steps to Reproduce

Upgrading from 3.7.13 to 3.7.14 introduced the bug.

I have a navigation array for my dashboard, built using New-UDListItem, with some of those leveraging the -Children param.

If -Children is not used or the if -Children has more than 1 nested New-UDListItem, the menu loads as expected. If there is only 1 nested ListItem, the error is present. I was able to confirm this by adding a second ListItem where I only had 1, the menus loaded as expected.

#### Error details ####

Error rendering component (mu-list-item)
TypeError: props.children.find is not a function

    at highOrderComponent (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:85619:55)
    at UDListItem
    at ErrorBoundary (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:83634:197)
    at Suspense
    at ul
    at https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:190:66
    at List (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:24869:82)
    at div
    at div
    at https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:190:66
    at Paper (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:27270:82)
    at https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:190:66
    at div
    at https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:190:66
    at Drawer (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:18308:83)
    at UdNavbar (https://psu.domain.com/Dashboard/Components_framework_ud-navbar_jsx.4e7ec801d6c453ffdb77.bundle.js:506:17)
    at highOrderComponent (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:85619:55)
    at div
    at Suspense
    at highOrderComponent (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:85619:55)
    at Suspense
    at InnerThemeProvider (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:44155:70)
    at ThemeProvider (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:42493:5)
    at ThemeProvider (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:44175:5)
    at StyledEngineProvider (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:42678:5)
    at n (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:136011:58)
    at https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:136011:1060
    at Dashboard (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:84561:22)
    at Route (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:122639:29)
    at Switch (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:122845:29)
    at div
    at Router (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:122270:30)
    at BrowserRouter (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:121895:35)
    at App (https://psu.domain.com/Dashboard/index.86e8de7b1c73ab12c588.bundle.js:82629:197)

### Expected behavior

```console
No errors building the menu
```

### Actual behavior

```console
Errors building the menu
```

### Environment data

Version: 3.7.14
Environment: Default (PS 7.3.3)
Framework: Latest
Runs as: Default
Authentication: Required
Webserver: IIS with Windows Auth and also in another Docker instance

### Visuals

![image](https://user-images.githubusercontent.com/11793959/222584698-f6af1825-4a2a-494f-92b1-beee5f9f7dbe.png)

**Comment by donlent** [comment]
I confirm exact the same issue... just upgraded from 3.7.9 to 3.7.14
Thanks @axisfx24 for reporting that. ;-)

**Comment by rwidmark** [comment]
I can also confirm this it did start with 3.7.14

**Comment by rwidmark** [comment]
@adamdriscoll

**Comment by rstolpe** [comment]
I tried to rewert back to PSU 3.7.13 but the issue are the same.

**Comment by rwidmark** [comment]
Any news on this one @adamdriscoll
