### ISSUE TITLE
-LoadingComponent of UDDynamic fails when just text is returned

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2217]
### Steps to Reproduce

Error

```
        New-UDDynamic -Content {
            Start-SLeep 5
        } -LoadingComponent {
"Loading"
        }
```

Work around

```
        New-UDDynamic -Content {
            Start-SLeep 5
        } -LoadingComponent {
            New-UDTypography "Loading"
        }
```

### Expected behavior

```console
Displays text
```

### Actual behavior

```console
Displays error
```

### Environment data

3.8.3

**Comment by Omzig** [comment]
![image](https://user-images.githubusercontent.com/1987296/226361064-999a3935-9ee4-41d5-b754-f46a3f65ba0e.png)

```console
Error rendering component (dynamic)
SyntaxError: Unexpected token '.', "... Loading ..." is not valid JSON

    at highOrderComponent (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:112277:55)
    at ErrorBoundary (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:83927:197)
    at Suspense
    at Cell (https://server.domain.com/NestedIISName/dashboard/TestingDash/Components_table_v2_table_js.33687c063ba127058897.bundle.js:1135:32)
    at td
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at TableCell (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:33702:83)
    at tr
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at TableRow (https://server.domain.com/NestedIISName/dashboard/TestingDash/vendors-node_modules_mui_material_TableBody_TableBody_js-node_modules_mui_material_TableConta-c0f201.55cd79f20b547ae6071f.bundle.js:656:82)
    at tbody
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at TableBody (https://server.domain.com/NestedIISName/dashboard/TestingDash/vendors-node_modules_mui_material_TableBody_TableBody_js-node_modules_mui_material_TableConta-c0f201.55cd79f20b547ae6071f.bundle.js:61:82)
    at BaseTableBody (https://server.domain.com/NestedIISName/dashboard/TestingDash/Components_table_v2_table_js.33687c063ba127058897.bundle.js:161:33)
    at table
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at Table (https://server.domain.com/NestedIISName/dashboard/TestingDash/vendors-node_modules_mui_material_TableBody_TableBody_js-node_modules_mui_material_TableConta-c0f201.55cd79f20b547ae6071f.bundle.js:1067:82)
    at div
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at Paper (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:27326:82)
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at TableContainer (https://server.domain.com/NestedIISName/dashboard/TestingDash/vendors-node_modules_mui_material_TableBody_TableBody_js-node_modules_mui_material_TableConta-c0f201.55cd79f20b547ae6071f.bundle.js:200:82)
    at TableBase (https://server.domain.com/NestedIISName/dashboard/TestingDash/Components_table_v2_table_js.33687c063ba127058897.bundle.js:1074:19)
    at ErrorBoundary (https://server.domain.com/NestedIISName/dashboard/TestingDash/vendors-node_modules_mui_icons-material_FirstPage_js-node_modules_mui_icons-material_Keyboard-990a4a.73dd00f8948c4e3c7670.bundle.js:18030:37)
    at highOrderComponent (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:112277:55)
    at ErrorBoundary (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:83927:197)
    at Suspense
    at highOrderComponent (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:112277:55)
    at ErrorBoundary (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:83927:197)
    at Suspense
    at div
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:190:66
    at Paper (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:27326:82)
    at highOrderComponent (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:112277:55)
    at ErrorBoundary (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:83927:197)
    at Suspense
    at main
    at UDPage (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:80926:23)
    at highOrderComponent (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:112277:55)
    at Route (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:149297:29)
    at Switch (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:149503:29)
    at div
    at Suspense
    at highOrderComponent (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:112277:55)
    at Suspense
    at InnerThemeProvider (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:44211:70)
    at ThemeProvider (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:42549:5)
    at ThemeProvider (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:44231:5)
    at StyledEngineProvider (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:42734:5)
    at n (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:162669:58)
    at https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:162669:1060
    at Dashboard (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:111201:22)
    at Route (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:149297:29)
    at Switch (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:149503:29)
    at div
    at Router (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:148928:30)
    at BrowserRouter (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:148553:35)
    at App (https://server.domain.com/NestedIISName/dashboard/TestingDash/index.4fa66b9e637efcebb2b6.bundle.js:82923:197)
```
