### ISSUE TITLE
Nested IIS: Windows authentication not working

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2305]
### Steps to Reproduce

not sure what i am doing wrong, but it is not auto logging in

### Expected behavior

```console
login
```

### Actual behavior

```console
prompt
```

### Environment data

PSU: 4.0.0 BETA 1
IIS: Nested

logs
```console
[12:11:15 VRB] Performing unprotect operation to key {1c2199cf-8768-4e70-b086-8d04b8e1d271} with purposes ('E:\src\psu\Beta\', 'SessionMiddleware').
[12:11:15 WRN] Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
[12:11:15 VRB] Performing protect operation to key {1c2199cf-8768-4e70-b086-8d04b8e1d271} with purposes ('E:\src\psu\Beta\', 'SessionMiddleware').
[12:11:15 DBG] Static files was skipped as the request already matched an endpoint.
[12:11:15 DBG] Static files was skipped as the request already matched an endpoint.
[12:11:15 DBG] Endpoint 'UniversalAutomation.GitStatusController.IsEditing (Universal.Server)' already set, skipping route matching.
[12:11:15 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[12:11:15 INF] AuthenticationScheme: Cookies was challenged.
[12:11:15 INF] AuthenticationScheme: Bearer was challenged.
[12:11:15 DBG] Connection id "0HMPQLUTSU6IS" completed keep alive response.
[12:11:15 INF] Request finished HTTP/1.1 GET http://dev.psu.jhacorp.com/Beta/api/v1/gitstatus/edit - - - 401 0 - 12.5199ms
```

### Visuals

![image](https://user-images.githubusercontent.com/1987296/231235349-47482ab9-94b1-493d-a5d7-394c6fd6cb40.png)

**Comment by Omzig** [comment]
@adamdriscoll, let me know if you want to see it

**Comment by adamdriscoll** [comment]
This could be various things. We have a checklist of things you can run through here: https://support.ironmansoftware.com/portal/en/kb/articles/kb0017-windows-auth-checklist

**Comment by Omzig** [comment]
> This could be various things. We have a checklist of things you can run through here: https://support.ironmansoftware.com/portal/en/kb/articles/kb0017-windows-auth-checklist

ahhhhhhhhhhhhhhhhhhhhhhhhh, is the dumb ```forwardWindowsAuthToken="true"``` in the web config file, sorry to bother you.

/pull hair out

**Comment by Omzig** [comment]
> forwardWindowsAuthToken="true"

can you add ```forwardWindowsAuthToken="true"``` to the wonderful check list you have?

I also found out that the beta license wont let you enable windows auth, so i had to install my license.

**Comment by Omzig** [comment]
@adamdriscoll, is this something we can put in the health checks? 

web.config: forwardWindowsAuthToken = false

**Comment by adamdriscoll** [comment]
Yep. I was thinking that too. Really easy to miss that.
