### ISSUE TITLE
New-UDStepper: Usage of "New-Item" breaks the Stepper...

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2320]
### Version

3.8.8

### Severity

High

### Steps to Reproduce

Unfortunately the use of "New-Item" breaks the Stepper functionality.
Thanks a lot for fixing this...

Here is a fully functional example. Just copy / paste into your environment and proceed... :-)

```
New-UDDashboard -Title 'PowerShell Universal' -DefaultTheme Dark -DisableThemeToggle -Pages @(
    New-UDPage -Icon (New-UDIcon -Icon 'bug') -Name 'New-Item Bug'  -Content {

        $session:targetDir = "$Repository\data\Tests"

        New-UDStepper -Id "stepper" -Steps {
            New-UDStep -OnLoad {
                New-UDElement -Tag 'h3' -Content { "Let's begin... Click Next..." }

            } -Label "Step 1"
            New-UDStep -OnLoad {
                New-UDElement -Tag 'h3' -Content { "Clicking on `"Next`" will break ud-step... :-)" }

                New-UDTextbox -Id "folderName" -Label "Type the name of the folder you wish to create..." -FullWidth

            } -Label "Step 2"
        } -OnFinish {
            if (Test-Path -Path "$session:targetDir\$session:folderName") {
                New-UDIcon -Icon 'ThumbsUp' -Beat -Size 10x
                New-UDTypography "It only worked because the folder $session:targetDir\$session:folderName already exists... ;-)"
            }
        } -OnValidateStep {
            if ($EventData.currentStep -eq 1) {
                $session:folderName = (Get-UDElement -Id "folderName").value

                if ([string]::IsNullOrEmpty($session:folderName)) {
                    New-UDValidationResult -ValidationError "Please type a Foldername first..."
                }
                else {
                    New-Item -Path "$session:targetDir\$session:folderName" -ItemType Directory
                    New-UDValidationResult -Valid
                }
            }
            else {
                New-UDValidationResult -Valid
            }
        }
    }
)
```

### Expected behavior

```console
The stepper should not break
```

### Actual behavior

```console
The stepper breaks if a New-Item gets created (in this example type = directory). If the directory already exists it does not break.

Here are the error details:
----------------
Error rendering component (mu-stepper)
TypeError: Cannot read properties of undefined (reading 'disablePrevious')

    at highOrderComponent (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:112261:55)
    at ErrorBoundary (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:83927:197)
    at Suspense
    at main
    at UDPage (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:80926:23)
    at highOrderComponent (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:112261:55)
    at Route (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:149281:29)
    at Switch (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:149487:29)
    at div
    at Suspense
    at highOrderComponent (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:112261:55)
    at Suspense
    at InnerThemeProvider (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:44211:70)
    at ThemeProvider (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:42549:5)
    at ThemeProvider (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:44231:5)
    at StyledEngineProvider (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:42734:5)
    at n (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:162653:58)
    at http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:162653:1060
    at Dashboard (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:111201:22)
    at Route (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:149281:29)
    at Switch (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:149487:29)
    at div
    at Router (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:148912:30)
    at BrowserRouter (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:148537:35)
    at App (http://localhost:5000/stepperbug01/index.9c08ba05011ad78a9478.bundle.js:82923:197)
```

### Environment data

3.8.8

### Visuals

![image](https://user-images.githubusercontent.com/11975745/232483481-373d6158-a3ea-4950-8048-dacace4c68a2.png)

**Comment by adamdriscoll** [comment]
The issue is that New-Item returns an object. Can you try this? 

```
New-Item -Path "$session:targetDir\$session:folderName" -ItemType Directory | Out-Null
```

**Comment by donlent** [comment]
Hey @adamdriscoll 
Thank you very much!! Indeed, that's the solution to my issue! it works now.

Just a question: Do you think the error message that is raised can be improved a bit? Because from the details you really don't see that the issue is related to such a simple thing and not really to your psu component...

In any case I'm going to close this issue now. :-)

As alway, thanks a lot for your much appreciated and quick help!
