### ISSUE TITLE
[Live doc] stops working at some point after editing/using another nested site

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2358]
### Version

4.0.2

### Severity

High

### Steps to Reproduce

when i visit live doc after i let it sit there for a moment, then try to visit another page it wont load

I have seen this on other dashboards, but mostly right after a save and auto reload

### Expected behavior

```console
load next page
```

### Actual behavior

```console
Request URL: https://dev.servername.domain.com/Beta/api/internal/component/element/f9e812b4-6f17-45d1-bcd1-7212af6563c1?
Request Method: GET
Status Code: 200 OK

Response:
{"type":"error","errorRecords":[{"message":"Value cannot be null. (Parameter 'source')"}]}
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://user-images.githubusercontent.com/1987296/235158670-325639a2-7af9-4ed9-acd1-06dcf5915263.png)

### Workaround
F5

**Comment by adamdriscoll** [comment]
I left my docs open for over an hour and this didn't happen. Can you do me a favor and grab some dashboard logs?

**Comment by Omzig** [comment]
No new logs when i click on stuff.

```
[6/6/2023 9:05:02 AM] [Information] [App-PowerShell Universal Apps Documentation] Dashboard configuration complete. 
[6/6/2023 9:05:02 AM] [Information] [App-PowerShell Universal Apps Documentation] Starting scheduler. 
[6/6/2023 9:05:01 AM] [Information] [App-PowerShell Universal Apps Documentation] Creating services. 
[6/6/2023 9:05:01 AM] [Information] [App-DemoPage] Dashboard configuration complete. 
[6/6/2023 9:05:01 AM] [Information] [App-DemoPage] Starting scheduler. 
[6/6/2023 9:05:01 AM] [Information] [App-DemoPage] Creating services. 
[6/6/2023 9:05:01 AM] [Information] [App-test] Dashboard configuration complete. 
[6/6/2023 9:05:00 AM] [Information] [App-test] Starting scheduler. 
[6/6/2023 9:04:56 AM] [Information] [App-test] Creating services. 
[6/6/2023 9:04:56 AM] [Error] [App-Test App Builder] Startup: at <ScriptBlock>, <No file>: line 1 
[6/6/2023 9:04:56 AM] [Error] [App-Test App Builder] Startup:    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 
[6/6/2023 9:04:56 AM] [Error] [App-Test App Builder] Failed to get dashboard. Dashboard was null. Make sure to return a dashboard from your script. 
[6/6/2023 9:04:56 AM] [Error] [App-Test App Builder] Startup: The term 'Pode\' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
[6/6/2023 9:04:55 AM] [Information] [App-Test App Builder] Creating services. 
[6/6/2023 8:38:14 AM] [Information] [App-PowerShell Universal Apps Documentation] Dashboard configuration complete. 
[6/6/2023 8:38:14 AM] [Information] [App-PowerShell Universal Apps Documentation] Starting scheduler. 
[6/6/2023 8:38:13 AM] [Information] [App-PowerShell Universal Apps Documentation] Creating services. 
[6/6/2023 8:38:13 AM] [Information] [App-DemoPage] Dashboard configuration complete. 
[6/6/2023 8:38:13 AM] [Information] [App-DemoPage] Starting scheduler. 
[6/6/2023 8:38:13 AM] [Information] [App-DemoPage] Creating services. 
[6/6/2023 8:38:13 AM] [Information] [App-test] Dashboard configuration complete. 
[6/6/2023 8:38:13 AM] [Information] [App-test] Starting scheduler. 
[6/6/2023 8:38:05 AM] [Information] [App-test] Creating services. 
[6/6/2023 8:38:05 AM] [Error] [App-Test App Builder] Failed to get dashboard. Dashboard was null. Make sure to return a dashboard from your script. 
[6/6/2023 8:38:05 AM] [Error] [App-Test App Builder] Startup: The term 'Pode\' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
[6/6/2023 8:38:05 AM] [Error] [App-Test App Builder] Startup: at <ScriptBlock>, <No file>: line 1 
[6/6/2023 8:38:05 AM] [Error] [App-Test App Builder] Startup:    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 
[6/6/2023 8:38:04 AM] [Information] [App-Test App Builder] Creating services. 
[6/6/2023 8:18:12 AM] [Information] [App-DemoPage] Dashboard configuration complete. 
[6/6/2023 8:18:12 AM] [Information] [App-DemoPage] Starting scheduler. 
[6/6/2023 8:18:08 AM] [Information] [App-DemoPage] Creating services. 
```
![image](https://github.com/ironmansoftware/issues/assets/1987296/6f3883e1-b2a2-4a6b-8db3-5fae3e82eab0)

![image](https://github.com/ironmansoftware/issues/assets/1987296/2fe73fce-f42b-4842-b788-5c3e51a834d1)

**Comment by Omzig** [comment]
# Trigger
- I believe the trigger is to open up another nested site, and edit the dashboard and save it and let it auto reload
- go back to beta site and try to click on something after playing with another nested iis site

**Comment by Omzig** [comment]
4.0.2 did not fix this

**Comment by Omzig** [comment]
i have a suggestion, how about if you prefix the cookies with their respective subsite name?

if the BasePath says /someSiteName then trim '/'. Then the cookie would be `someSiteName.RequestVerificationToken` and `someSiteName.AspNetCore.Session`

**Comment by adamdriscoll** [comment]
Done. This has been implemented in 4.x and 3.x branches and will be in tonight's nightly.

**Comment by Omzig** [comment]
i will be back Monday to verify, so if you release it production before i get back, i will get on and double check that my sites work with the new enhancement

**Comment by Omzig** [comment]
did it go into 3.9.8?

**Comment by Omzig** [comment]
the beta live doc is working with the feature at the same time as the other nested site, this seems to have fixed the issue

**Comment by adamdriscoll** [comment]
This was in the v4 branch. v3 doesn't have the live docs. Glad that it seems to have resolved it. I'll close this. Feel free to reopen if you see anything else.

**Comment by Omzig** [comment]
> This was in the v4 branch. v3 doesn't have the live docs. Glad that it seems to have resolved it. I'll close this. Feel free to reopen if you see anything else.

ya, now i am wondering if it fixes our SQL problem with multi nested sites ;)
