### ISSUE TITLE
Dashboard Map Error

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2457]
### Version

Other Please Specify

### Severity

Low

### Steps to Reproduce

```
Error rendering component (map-raster-layer)
TypeError: this.props.removeLayer is not a function

at TileLayer (http://projekt:5000/dashboard/Components_map_raster-layer_jsx.29805cd3382ac3275b47.bundle.js:668:23)
at Leaflet(TileLayer)
at UDRasterLayer (http://projekt:5000/dashboard/Components_map_raster-layer_jsx.29805cd3382ac3275b47.bundle.js:247:197)
at ErrorBoundary (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:80928:197)
at Suspense
at BaseLayer (http://projekt:5000/dashboard/Components_map_UDLayerControl_jsx.f467360186405f772257.bundle.js:268:31)
at UDLayerControlBaseLayer (http://projekt:5000/dashboard/Components_map_UDLayerControlBaseLayer_jsx.ab5450e4c267367eceff.bundle.js:38:197)
at ErrorBoundary (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:80928:197)
at Suspense
at LayersControl (http://projekt:5000/dashboard/Components_map_UDLayerControl_jsx.f467360186405f772257.bundle.js:328:26)
at Leaflet(LayersControl)
at UDLayerControl (http://projekt:5000/dashboard/Components_map_UDLayerControl_jsx.f467360186405f772257.bundle.js:38:197)
at ErrorBoundary (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:80928:197)
at Suspense
at div
at Map (http://projekt:5000/dashboard/vendors-node_modules_glamor-jss_lib_glamor-jss_cjs_js-node_modules_react-leaflet_es_Map_js-no-e3baa9.fdbb72a9dc337128ee17.bundle.js:7691:25)
at UDMap (http://projekt:5000/dashboard/Components_map_map_jsx.0b1127340eed6556df35.bundle.js:63:197)
at ErrorBoundary (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:80928:197)
at Suspense
at main
at UDPage (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:77939:23)
at highOrderComponent (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:109221:55)
at Route (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:146241:29)
at Switch (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:146447:29)
at div
at Suspense
at highOrderComponent (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:109221:55)
at Suspense
at InnerThemeProvider (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:41224:70)
at ThemeProvider (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:39562:5)
at ThemeProvider (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:41244:5)
at StyledEngineProvider (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:39747:5)
at n (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:159613:58)
at http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:159613:1060
at Dashboard (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:108206:22)
at Route (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:146241:29)
at Switch (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:146447:29)
at div
at Router (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:145872:30)
at BrowserRouter (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:145497:35)
at App (http://projekt:5000/dashboard/index.8c89c95e064821eead7c.bundle.js:79924:197)

First of 4 Errors in
map-raster-layer
map-overlay
```

### Expected behavior

```console
No Error
```

### Actual behavior

```console
Error
```

### Additional Environment data

Unknown version

**Comment by adamdriscoll** [comment]
Duplicate of #2535
