### ISSUE TITLE
Error after Upgrade , Null environmet Variable

### ISSUE THREAD

**Issue by SignalR-Dev** [ironmansoftware/powershell-universal#2471]
### Version

4.0.0

### Severity

Low

### Steps to Reproduce

Upgrage Via Module 3.9.5 -> 4.0.1  . , PSU is Running in IIS

App stops with 503

Message from Event Viewer

Application: w3wp.exe
CoreCLR Version: 7.0.222.60605
.NET Version: 7.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Environment.ExpandEnvironmentVariables(String name)
   at Universal.Server.Program.CreateHostBuilder(String[] args, Options options) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Program.cs:line 253
   at Universal.Server.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Program.cs:line 63
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Universal.Server.Program.Main(String[] args) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Program.cs:line 52

Unclear which Variable has missing Value 

### Expected behavior

```console
200
```

### Actual behavior

```console
503
```

**Comment by adamdriscoll** [comment]
It's failing to find the SystemLogPath setting. In appsettings.json, it should be: 

```
"SystemLogPath": "%ProgramData%\\PowerShellUniversal\\systemLog.txt",
```

**Comment by SignalR-Dev** [comment]
Well it is 
    "Logging":  {
                    "Path":  "%PROGRAMDATA%/PowerShellUniversal/log.txt",
                    "RetainedFileCountLimit":  31,
                    "LogLevel":  {
                                     "Default":  "Information",
                                     "Microsoft":  "Warning",
                                     "Microsoft.Hosting.Lifetime":  "Information",
                                     "Grpc":  "Information"
                                 }
                }

Checked the Log Location , no new Records get added

**Comment by SignalR-Dev** [comment]
Issue Solved
Our Update Script Copies web.config and  Appsettings to a Folder , Upgrades and Copies them Back
The Schema of the Appsettings has changed as Part of Major Upgrade.
Loging.path has been moved to  SystemLogPath
Downloaded a Fresh version as ZIP , Swapped the Setting in the Fresh one , works fine
Thanks for the Hint
