### ISSUE TITLE
New-UDExpansionPanelGroup Does Not Work with a single Panel

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2481]
### Version

3.9.7

### Severity

Critical

### Steps to Reproduce

expansion panels stopped working

### Expected behavior

```console
no error
```

### Actual behavior

```console
Error rendering component (mu-expansion-panel-group)
TypeError: children.map is not a function

    at AccordionGroup (https://server.domain.com/iisInstance/apps/apiProductBaseline/Components_expansion-panel_jsx.c3b8186a40c6a8a28941.bundle.js:120:17)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at div
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:190:66
    at Stack (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:28420:87)
    at highOrderComponent (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:109221:55)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at div
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:190:66
    at Grid (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:18079:87)
    at UDGrid (https://server.domain.com/iisInstance/apps/apiProductBaseline/Components_grid_jsx.1d7db2fb2b85af6f2f52.bundle.js:24:16)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at div
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:190:66
    at Grid (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:18079:87)
    at UDGrid (https://server.domain.com/iisInstance/apps/apiProductBaseline/Components_grid_jsx.1d7db2fb2b85af6f2f52.bundle.js:24:16)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at highOrderComponent (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:109221:55)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at div
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:190:66
    at Paper (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:24339:82)
    at highOrderComponent (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:109221:55)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at div
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:190:66
    at Grid (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:18079:87)
    at UDGrid (https://server.domain.com/iisInstance/apps/apiProductBaseline/Components_grid_jsx.1d7db2fb2b85af6f2f52.bundle.js:24:16)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at div
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:190:66
    at Grid (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:18079:87)
    at UDGrid (https://server.domain.com/iisInstance/apps/apiProductBaseline/Components_grid_jsx.1d7db2fb2b85af6f2f52.bundle.js:24:16)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at highOrderComponent (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:109221:55)
    at ErrorBoundary (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:80928:197)
    at Suspense
    at main
    at UDPage (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:77939:23)
    at highOrderComponent (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:109221:55)
    at Route (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:146241:29)
    at Switch (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:146447:29)
    at div
    at Suspense
    at highOrderComponent (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:109221:55)
    at Suspense
    at InnerThemeProvider (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:41224:70)
    at ThemeProvider (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:39562:5)
    at ThemeProvider (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:41244:5)
    at StyledEngineProvider (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:39747:5)
    at n (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:159613:58)
    at https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:159613:1060
    at Dashboard (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:108206:22)
    at Route (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:146241:29)
    at Switch (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:146447:29)
    at div
    at Router (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:145872:30)
    at BrowserRouter (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:145497:35)
    at App (https://server.domain.com/iisInstance/apps/apiProductBaseline/index.b621e76d941a6c1cf457.bundle.js:79924:197)
```

### Additional Environment data

It was supposed to be fixed in 3.9.2
- https://docs.powershelluniversal.com/v/v3/changelog#3.9.2-5-14-2023

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/18a7e179-af09-4575-8fcc-056d924c3ec1)

**Comment by Omzig** [comment]
my bad, i think i am in the wrong, i thought i was on 3.9.7, i reverted that server because of another problem /facepalm, i reverted it to 3.9.0!!!!!!!!!!! and 3.9.2 has the fix in it, i moved it to the correct milestone, 3.9.2
