### ISSUE TITLE
Maps component in live doc has errors

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2535]
### Version

4.0.5

### Severity

Low

### Steps to Reproduce

something is wrong with the maps

### Expected behavior

```console
no errors
```

### Actual behavior

```console
lots of errors


Error rendering component (map-raster-layer)
TypeError: this.props.removeLayer is not a function

    at TileLayer (https://server.domain.com/Beta/apps/docs/Components_map_raster-layer_jsx.5aa0a263957eecb6aa5d.bundle.js:628:23)
    at Leaflet(TileLayer)
    at UDRasterLayer (https://server.domain.com/Beta/apps/docs/Components_map_raster-layer_jsx.5aa0a263957eecb6aa5d.bundle.js:211:164)
    at ErrorBoundary (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:84827:164)
    at Suspense
    at BaseLayer (https://server.domain.com/Beta/apps/docs/Components_map_UDLayerControl_jsx.54a57e7e79a22d6bb507.bundle.js:248:31)
    at UDLayerControlBaseLayer (https://server.domain.com/Beta/apps/docs/Components_map_UDLayerControlBaseLayer_jsx.19acf6aacb5bdfc4609c.bundle.js:34:164)
    at ErrorBoundary (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:84827:164)
    at Suspense
    at LayersControl (https://server.domain.com/Beta/apps/docs/Components_map_UDLayerControl_jsx.54a57e7e79a22d6bb507.bundle.js:308:26)
    at Leaflet(LayersControl)
    at UDLayerControl (https://server.domain.com/Beta/apps/docs/Components_map_UDLayerControl_jsx.54a57e7e79a22d6bb507.bundle.js:34:164)
    at ErrorBoundary (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:84827:164)
    at Suspense
    at div
    at Map (https://server.domain.com/Beta/apps/docs/vendors-node_modules_glamor-jss_lib_glamor-jss_cjs_js-node_modules_react-leaflet_es_Map_js-no-e3baa9.1895c9bcc85d32582c46.bundle.js:7691:25)
    at UDMap (https://server.domain.com/Beta/apps/docs/Components_map_map_jsx.288109b9481535ef06ea.bundle.js:59:164)
    at ErrorBoundary (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:84827:164)
    at Suspense
    at div
    at https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:825:66
    at Paper (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:29147:83)
    at highOrderComponent (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:86560:55)
    at ErrorBoundary (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:84827:164)
    at Suspense
    at main
    at UDPage (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:79376:23)
    at highOrderComponent (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:86560:55)
    at Route (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:321747:29)
    at Switch (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:321953:29)
    at div
    at Suspense
    at highOrderComponent (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:86560:55)
    at Suspense
    at ThemeProvider (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:40664:5)
    at ThemeProvider (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:42044:5)
    at ThemeProvider (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:39028:14)
    at StyledEngineProvider (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:40839:5)
    at n (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:336640:58)
    at https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:336640:1060
    at Dashboard (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:85662:22)
    at Route (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:321747:29)
    at Switch (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:321953:29)
    at div
    at Router (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:321378:30)
    at BrowserRouter (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:321003:35)
    at QueryClientProvider (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:319723:21)
    at n (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:336640:58)
    at https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:336640:1060
    at App (https://server.domain.com/Beta/apps/docs/index.09eeac8ddc0dc120d4ce.bundle.js:81311:89)
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/ff725a24-8e51-454e-b5b5-845aa78ba21b)

![image](https://github.com/ironmansoftware/issues/assets/1987296/68ee497c-a914-4c01-8926-3919f4fb2c3c)

**Comment by Omzig** [comment]
4.2.4 still has this issue ;)
