### ISSUE TITLE
Exception: Failed to create admin account

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#2814]
### Version

4.1.7

### Severity

Low

### Steps to Reproduce

Upgraded to 4.1.8, saw this in the logs:

2023-10-31 09:11:17.159 -04:00 [INF] Starting security proxy.
2023-10-31 09:11:17.160 -04:00 [INF] Security service already started
2023-10-31 09:11:17.160 -04:00 [INF] Enabling autoreload.
2023-10-31 09:11:17.183 -04:00 [ERR] Failed to create admin account.
System.Exception: Identity 'admin' already exists.
   at UniversalAutomation.IdentityService.CreateIdentity(Identity identity) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Authentication\IdentityService.cs:line 122
   at UniversalAutomation.StartupService.RunStartup() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\StartupService.cs:line 379
2023-10-31 09:11:17.308 -04:00 [INF] Running health check: Disk Space

### Expected behavior

```console
No exception
```

### Actual behavior

```console
Exception
```

### Additional Environment data

Windows Server 2019
SQL Server 2019
PSU 4.1.8

**Comment by adamdriscoll** [comment]
I dont see this in recent versions.
