### ISSUE TITLE
A dashboard with a base url of "/" will present "App is not running" error

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2986]
### Version

4.2.6

### Severity

Low

### Steps to Reproduce

1. Creating a working dashboard
2. Stop the PowerShell Universal service
3. Edit the dashboards.ps1 file located in the .universal directory of the PSU repository
4. Change the base url of the dashboard from `/something` to `/`
5. Start the PowerShell Universal service
6. Browse to the console logon page
7. Observe "App is not running" error page instead of the console logon page

Reverting the change resumes normal service.

### Expected behavior

```console
An app (formerly dashboard) with an empty base url of "/" should not be loaded by PowerShell Universal
```

### Actual behavior

```console
PowerShell Universal attempts to load an app (formerly dashboard) with an empty base url of "/"
```

### Additional Environment data

![image](https://github.com/ironmansoftware/issues/assets/537287/7e9b71e9-eb03-40ff-b77f-d64d1a3c4bea)

### Visuals

```
2023-12-18 09:39:08.106 -05:00 [ERR] Failed to read configuration file. dashboards.ps1
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\UniversalAutomation\Repository\dashboards\dashboard\dashboard.ps1'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at UniversalAutomation.Services.DashboardsConfigurationScript.OnReadAfterAddAsync(Dashboard dashboard) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Dashboards.cs:line 126
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(String rootPath, Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 286
```

**Comment by adamdriscoll** [comment]
I'm assuming the file it's referring to exists. It seems like dashboard.ps1 is missing. Can you double check that?

**Comment by adamdriscoll** [comment]
The base URL isn't the issue here. I just tried it myself and it works.

**Comment by DataTraveler1** [comment]
@adamdriscoll, you are correct that the file did not exist which I overlooked to include in this Issue. My bad on that. Although I was sure it was related to the URL, try as I might, I am also unable to reproduce this. I will come back to this someday when I do 👍
