### ISSUE TITLE
Groom job fails when using LiteDB

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3021]
### Version

4.2.8

### Severity

Low

### Steps to Reproduce

```
2024-01-03 12:26:02.664 -05:00 [INF] Starting heartbeat job.
2024-01-03 12:26:02.668 -05:00 [INF] Script has 1 jobs to delete.
2024-01-03 12:26:02.730 -05:00 [INF] Finished heartbeat job.
2024-01-03 12:26:02.734 -05:00 [ERR] Failed to groom.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method3033(Closure, Job)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at UniversalAutomation.LiteDBTable`1.DeleteRange(Func`2 query) in C:\actions-runner\_work\universal\universal\src\UniversalAutomation.LiteDBv5\LiteDBDatabase.cs:line 909
   at UniversalAutomation.GroomService.ScriptLevelGroom() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\GroomService.cs:line 185
   at UniversalAutomation.GroomService.Groom() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\GroomService.cs:line 297
2024-01-03 12:26:02.735 -05:00 [INF] Finished groom job.
```

### Expected behavior

```console
Runs successfully
```

### Actual behavior

```console
Fails
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/groom-job-fails-after-upgrade-to-4-2-7/10181/6
