### ISSUE TITLE
Error Rendering Transfer List

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3048]
### Version

4.2.9

### Severity

Low

### Steps to Reproduce

Create a transfer list. 

```
Error rendering component (mu-transfer-list)

TypeError: e.item.filter is not a function

 

    at x (https:///dashboard/az/azureaccount/4815.8c1fe3aaa713d019dda9.bundle.js:1:3180)

    at https:///dashboard/az/azureaccount/index.3e88fc674d14ae74847c.bundle.js:152:643947

    at r (https:///dashboard/az/azureaccount/index.3e88fc674d14ae74847c.bundle.js:152:1602333)
```

### Expected behavior

```console
Renders properly
```

### Actual behavior

```console
Error.
```

**Comment by mattselle** [comment]
Can we get any example code for this? I tried with a basic list and it renders fine.

**Comment by adamdriscoll** [comment]
@mattselle - It looks like it happens when there are no transfer items. 

```
    New-UDTransferList -Item {
    } -Id 'transferlist1'
```

**Comment by adamdriscoll** [comment]
Sorry. Nabbed this one cuz gotta get the release out.
