### ISSUE TITLE
Page designer - Adding divider throws render error

### ISSUE THREAD

**Issue by pbknl** [ironmansoftware/powershell-universal#3165]
### Version

4.2.13

### Severity

Low

### Steps to Reproduce

I am using the 4.2.13 docker build.
When trying to add a divider through the page designer it throws an error:

Steps to reproduce the issue:
PSU
User Interfaces
App
Edit Details on app
New Page
Name: tester
Use Designer: on
OK
Add Component
Divider

Error rendering component (mu-divider)
TypeError: Cannot add property __version, object is not extensible

    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:644664
    at r (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1603050)
    at Suspense
    at div
    at div
    at Le (https://ds1821p.home.mylan.org:13143/app/4574.13608b8df8c04d0760b3.bundle.js:1:27771)
    at div
    at i (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1363176)
    at d (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1212411)
    at p (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1230270)
    at div
    at x (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1241577)
    at y (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1256787)
    at g (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1262947)
    at main
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:2:10117
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:2:45138
    at div
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:2:10117
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:2:45138
    at Be (https://ds1821p.home.mylan.org:13143/app/4574.13608b8df8c04d0760b3.bundle.js:1:30181)
    at Ke (https://ds1821p.home.mylan.org:13143/app/4574.13608b8df8c04d0760b3.bundle.js:1:34721)
    at t (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1382363)
    at t (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1384346)
    at div
    at Suspense
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:644664
    at Suspense
    at u (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:63924)
    at m (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:64431)
    at g (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:64648)
    at s (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:77866)
    at r (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1438024)
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1438900
    at Dashboard (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:571643)
    at t (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1382363)
    at t (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1384346)
    at div
    at qe (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1616066)
    at Ye (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1617271)
    at Xe (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1616702)
    at nt (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1620055)
    at t (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1379084)
    at t (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1373668)
    at d (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1350279)
    at l (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1070112)
    at r (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1438024)
    at https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1438900
    at ht (https://ds1821p.home.mylan.org:13143/app/index.ca2de8e7155f915e5dd1.bundle.js:152:1622125)

### Expected behavior

```console
Add the divider element to the page
```

### Actual behavior

```console
Adds the divider element but unable to render correctly and throws error
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/162833487/9b371e71-9cd1-4dd8-a587-e91204b4d0ee)

**Comment by adamdriscoll** [comment]
Page designer is deprecated and will no longer be receiving fixes.
