### ISSUE TITLE
"Failed to load API definition." in swagger Doc on the default 'Endpoints'

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3287]
### Version

4.2.19

### Severity

High

### Environment

Nested IIS

### Steps to Reproduce

when i view the swagger doc on the default endpoint, it fails to load

### Expected behavior

```console
good json from https://psu.domain.com/InstanceName/endpoints.json
```

### Actual behavior

```console
Object reference not set to an instance of an object.
```

### Additional Environment data

Logs:
```

2024-04-22 09:51:08.190 -05:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PowerShellUniversal.EndpointDocService.ProcessDocument(OpenApiDocument document, HttpContext context) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\API\EndpointDocService.cs:line 233
   at PowerShellUniversal.EndpointDocService.Handle(HttpContext context) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\API\EndpointDocService.cs:line 173
   at Universal.Server.Middleware.RoutingMiddleware.Invoke(HttpContext httpContext, IPolicyEvaluator policyEvaluator) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\RoutingMiddleware.cs:line 126
   at PowerShellUniversal.PSUMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\PowerShellMiddleware.cs:line 43
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Universal.Server.Middleware.SwaggerAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\SwaggerAuthMiddleware.cs:line 51
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\actions-runner\_work\universal\universal\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 109
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/1987296/98b79cf6-cfa2-4785-a817-597f25c12b2f)

**Comment by Omzig** [comment]
Even if i go to my demo instance and remove all the api's the swagger doc fails to generate.

**Comment by Omzig** [comment]
@adamdriscoll, TYTYTYTYTYTYTYTYTYTY.
