### ISSUE TITLE
Endpoints - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#3295]
### Version

4.2.19

### Severity

Medium

### Environment

msi

### Steps to Reproduce

PSU 4.2.19
SQL 2022
Windows 2022

Since upgrading to 4.2.19 we are seeing higher memory usage. Memory on an unused server startup is between 5-10GB. Before upgrading from 4.2.15 has been a few hundred when idle. Upon service start I see memory quickly jump to 3GB then slowly rises. Eventually it hits ~10GB and stays around there.

Additionally, i'm seeing random failures in the GUI when working with endpoints that require restarting the PSU service (I didn't catch a screenshot before restarting, ill add it when I see it again). 

I have been making small changes to an endpoint through the GUI as I test some new functionality. Like adding or removing a Write-Information, so nothing large. When updating environments and endpoints PSU seems to randomly bog down temporarily. I have seen the error below occur even when just updating an environment and not just endpoints.  

![image](https://github.com/ironmansoftware/issues/assets/136116901/6bb369ca-5da0-46a5-b7ea-3a27c2a97f38)

Debug logs show the error below. Overall it feels like there is an intermittent stability issue introduced in 4.2.19 but I can't put my finger on it. After restart the same endpoints and environments work fine. Strange.. 

2024-04-26 13:37:16.816 -04:00 [DBG] File .universal\endpoints.ps1 changed. Syncing...
2024-04-26 13:37:16.816 -04:00 [DBG] Reading configuration file dashboards.ps1
2024-04-26 13:37:16.816 -04:00 [DBG] File exists. Deserializing items.
2024-04-26 13:37:16.834 -04:00 [DBG] Reading configuration file endpoints.ps1
2024-04-26 13:37:16.834 -04:00 [DBG] File exists. Deserializing items.
2024-04-26 13:37:16.879 -04:00 [DBG] Removing endpoint: (System.String[]) /web/gk/feedback
2024-04-26 13:37:16.880 -04:00 [ERR] Failed to read configuration file. endpoints.ps1
2024-04-26 13:37:16.880 -04:00 [ERR] Failed to read configuration file. endpoints.ps1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal.Server.Services.ApiGrpc.RemoveEndpointAsync(Endpoint endpoint) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\API\ApiGrpc.cs:line 189
   at Universal.Server.Services.ApiService.RemoveEndpointAsync(Endpoint endpoint) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\API\ApiService.cs:line 249
   at UniversalAutomation.Services.EndpointsConfigurationScript.OnReadAfterUpdateAsync(Endpoint endpoint) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Endpoints.cs:line 96
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(String rootPath, Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 331

2024-04-26 13:37:16.925 -04:00 [INF] Request starting HTTP/2 GET https://***/api/v1/notification/last - -
2024-04-26 13:37:16.925 -04:00 [INF] Request starting HTTP/2 GET https://***/api/v1/notification/last - -
2024-04-26 13:37:16.926 -04:00 [DBG] AuthenticationScheme: Cookies was successfully authenticated.
2024-04-26 13:37:16.926 -04:00 [DBG] AuthenticationScheme: Cookies was successfully authenticated.
2024-04-26 13:37:16.927 -04:00 [DBG] The request path /api/v1/notification/last does not match a supported file type
2024-04-26 13:37:16.927 -04:00 [DBG] The request path  does not match the path filter
2024-04-26 13:37:16.927 -04:00 [DBG] 1 candidate(s) found for the request path '/api/v1/notification/last'
2024-04-26 13:37:16.927 -04:00 [DBG] Endpoint 'UniversalAutomation.NotificationController.GetLast (Universal.Server)' with route pattern 'api/v1/notification/last' is valid for the request path '/api/v1/notification/last'
2024-04-26 13:37:16.927 -04:00 [DBG] The request path /api/v1/notification/last does not match a supported file type
2024-04-26 13:37:16.927 -04:00 [DBG] Request matched endpoint 'UniversalAutomation.NotificationController.GetLast (Universal.Server)'
2024-04-26 13:37:16.927 -04:00 [DBG] The request path  does not match the path filter
2024-04-26 13:37:16.927 -04:00 [DBG] 1 candidate(s) found for the request path '/api/v1/notification/last'

### Expected behavior

```console
Environment is stable
```

### Actual behavior

```console
Random endpoint crashes
```

**Comment by adamdriscoll** [comment]
The API error is a symptom of something else. It happens when the API process fails to start. We've put in a better error message in for the next version. This could be due to the memory issue you are facing. Can you open a support case and capture a memory dump of the process? We can communicate on how best to send that over the support case.

**Comment by adamdriscoll** [comment]
Let's track this on the support case. I'll open specific issues as need be.
