### ISSUE TITLE
PostgreSQL is having trouble with dates

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3342]
### Version

5.0.0-beta4

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

when i use the PostgreSQL driver it complains

### Expected behavior

```console
200 OK
```

### Actual behavior

```console
Request URL: https://dev.psu.domain.com/Beta/admin 
Request Method: GET
500 Internal Server Error

Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')
```
## Logs Error
```console
An unhandled exception has occurred while executing the request.
System.ArgumentException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')
   at Npgsql.Internal.Converters.DateTimeConverterResolver`1.Get(DateTime value, Nullable`1 expectedPgTypeId, Boolean validateOnly)
```

### Additional Environment data

```console
2024-05-20 11:49:37.906 -05:00 [INF] Start installing Hangfire SQL objects...
2024-05-20 11:49:37.956 -05:00 [INF] Hangfire SQL objects installed.
2024-05-20 11:49:38.309 -05:00 [INF] User profile is available. Using 'C:\Users\svc-eisportal-dev\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2024-05-20 11:49:38.405 -05:00 [INF] Starting PowerShell Universal...
2024-05-20 11:49:39.098 -05:00 [INF] PowerShell Universal Version: 5.0.0-beta4
2024-05-20 11:49:39.100 -05:00 [INF] OS Version: Microsoft Windows NT 10.0.17763.0
2024-05-20 11:49:39.100 -05:00 [INF] OS Architecture: x64
2024-05-20 11:49:39.100 -05:00 [INF] Process Architecture: x64
2024-05-20 11:49:39.102 -05:00 [INF] Node Name: myServerNAME
2024-05-20 11:49:39.103 -05:00 [INF] Running startup complete.
2024-05-20 11:49:39.138 -05:00 [INF] Starting PowerShell Universal...
2024-05-20 11:49:39.154 -05:00 [INF] Starting management service...
2024-05-20 11:49:39.347 -05:00 [INF] Loading app tokens...
2024-05-20 11:49:39.375 -05:00 [INF] Initializing database...
2024-05-20 11:49:39.422 -05:00 [INF] RPC services being provided by UniversalAutomation.IPublicSecretManagerService: 1
2024-05-20 11:49:39.442 -05:00 [INF] RPC services being provided by PowerShellUniversal.IdentityClient: 6
2024-05-20 11:49:39.467 -05:00 [INF] RPC services being provided by PowerShellUniversal.JobDataService: 11
2024-05-20 11:49:39.477 -05:00 [WRN] Type cannot be serialized; ignoring: PowerShellUniversal.AuthenticationMethod
2024-05-20 11:49:39.477 -05:00 [WRN] Signature not recognized for PowerShellUniversal.IPublicClient.NewAuthenticationMethod; method will not be bound
2024-05-20 11:49:39.481 -05:00 [WRN] Type cannot be serialized; ignoring: PowerShellUniversal.Translation
2024-05-20 11:49:39.481 -05:00 [WRN] Signature not recognized for PowerShellUniversal.IPublicClient.NewTranslation; method will not be bound
2024-05-20 11:49:39.489 -05:00 [WRN] Signature not recognized for PowerShellUniversal.IPublicClient.SyncComponent; method will not be bound
2024-05-20 11:49:39.528 -05:00 [INF] RPC services being provided by PowerShellUniversal.PublicClient: 31
2024-05-20 11:49:39.539 -05:00 [INF] RPC services being provided by PowerShellUniversal.ComputerClient: 5
2024-05-20 11:49:39.555 -05:00 [INF] RPC services being provided by Universal.Server.Services.DashboardGrpcClient: 7
2024-05-20 11:49:39.565 -05:00 [INF] RPC services being provided by Universal.Server.Services.Configuration.BlazorPageService: 5
2024-05-20 11:49:39.569 -05:00 [INF] RPC services being provided by Universal.Server.Services.Automation.JobInvokerService: 2
2024-05-20 11:49:39.579 -05:00 [INF] RPC services being provided by Universal.Server.Services.Authentication.AppTokenClient: 6
2024-05-20 11:49:39.587 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.ComputerGroupService: 5
2024-05-20 11:49:39.595 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.EndpointDocumentationService: 5
2024-05-20 11:49:39.605 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.EndpointService: 5
2024-05-20 11:49:39.613 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.EnvironmentConfigService: 5
2024-05-20 11:49:39.621 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.EventHubService: 5
2024-05-20 11:49:39.630 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.FolderService: 5
2024-05-20 11:49:39.639 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.HealthCheckConfigService: 5
2024-05-20 11:49:39.648 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.ModuleConfigService: 5
2024-05-20 11:49:39.658 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.PublishedFolderCommand: 5
2024-05-20 11:49:39.670 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.RoleService: 5
2024-05-20 11:49:39.679 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.ScriptService: 5
2024-05-20 11:49:39.688 -05:00 [INF] Loading configuration files...
2024-05-20 11:49:39.689 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.TagService: 5
2024-05-20 11:49:39.698 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.TerminalService: 5
2024-05-20 11:49:39.709 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.TriggerService: 5
2024-05-20 11:49:39.717 -05:00 [INF] RPC services being provided by UniversalAutomation.Services.VariableService: 5
2024-05-20 11:49:39.724 -05:00 [INF] RPC services being provided by PowerShellUniversal.IGitSettingsService: 4
2024-05-20 11:49:39.791 -05:00 [INF] RPC services being provided by UniversalAutomation.IPublicGitService: 3
2024-05-20 11:49:39.798 -05:00 [INF] RPC services being provided by UniversalAutomation.IPublicApiService: 1
2024-05-20 11:49:39.807 -05:00 [INF] RPC services being provided by UniversalAutomation.IPublicGitSyncService: 5
2024-05-20 11:49:39.812 -05:00 [INF] RPC services being provided by PowerShellUniversal.IBrandingService: 1
2024-05-20 11:49:39.957 -05:00 [INF] Overriding endpoints defined via IConfiguration and/or UseKestrel() because PreferHostingUrls is set to true. Binding to address(es) 'http://127.0.0.1:6401' instead.
2024-05-20 11:49:39.963 -05:00 [INF] Now listening on: http://127.0.0.1:6401
2024-05-20 11:49:40.121 -05:00 [INF] Application started. Press Ctrl+C to shut down.
2024-05-20 11:49:40.121 -05:00 [INF] Hosting environment: Production
2024-05-20 11:49:40.121 -05:00 [INF] Content root path: E:\src\psu\Beta
2024-05-20 11:49:40.267 -05:00 [INF] Request starting HTTP/1.1 GET http://localhost/Beta/ - null null
2024-05-20 11:49:40.500 -05:00 [INF] Executing ChallengeResult with authentication schemes ([]).
2024-05-20 11:49:40.505 -05:00 [INF] AuthenticationScheme: Cookies was challenged.
2024-05-20 11:49:40.508 -05:00 [INF] Request finished HTTP/1.1 GET http://localhost/Beta/ - 302 0 null 242.2587ms
2024-05-20 11:49:44.304 -05:00 [ERR] Failed to read configuration file. settings.ps1
System.InvalidOperationException: No service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at UniversalAutomation.Services.SettingsConfigurationScript.OnReadAfterAllAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Settings.cs:line 156
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(String rootPath, Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 370
2024-05-20 11:49:45.423 -05:00 [INF] Configuring authentication methods...
2024-05-20 11:49:45.431 -05:00 [INF] Synchronizing with git...
2024-05-20 11:49:45.440 -05:00 [INF] Running git sync, if configured.
2024-05-20 11:49:45.823 -05:00 [INF] Logging enabled at level Debug
2024-05-20 11:49:45.837 -05:00 [INF] Scheduling git sync service.
2024-05-20 11:49:45.837 -05:00 [INF] Scheduling background jobs...
2024-05-20 11:49:45.846 -05:00 [INF] Scheduling heartbeat job.
2024-05-20 11:49:45.862 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/admin - null null
2024-05-20 11:49:45.900 -05:00 [INF] Executing ChallengeResult with authentication schemes ([]).
2024-05-20 11:49:45.902 -05:00 [INF] AuthenticationScheme: Cookies was challenged.
2024-05-20 11:49:45.903 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/admin - 302 0 null 41.4965ms
2024-05-20 11:49:45.946 -05:00 [INF] Scheduling update check.
2024-05-20 11:49:45.953 -05:00 [INF] Starting heartbeat job.
2024-05-20 11:49:45.984 -05:00 [INF] Running health check: IIS WebSocket Feature Enabled
2024-05-20 11:49:45.987 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/login?ReturnUrl=%2FBeta%2Fadmin - null null
2024-05-20 11:49:46.015 -05:00 [INF] Finished heartbeat job.
2024-05-20 11:49:46.039 -05:00 [INF] Executing endpoint '/Login'
2024-05-20 11:49:46.063 -05:00 [INF] Route matched with {page = "/Login", action = "", controller = ""}. Executing page /Login
2024-05-20 11:49:46.077 -05:00 [INF] Executing handler method PowerShellUniversal.Login.OnGet - ModelState is "Valid"
2024-05-20 11:49:46.082 -05:00 [INF] Starting security service...
2024-05-20 11:49:46.091 -05:00 [INF] Starting security proxy.
2024-05-20 11:49:46.097 -05:00 [INF] Enabling autoreload.
2024-05-20 11:49:46.105 -05:00 [INF] Executed handler method OnGet, returned result .
2024-05-20 11:49:46.108 -05:00 [INF] Executing an implicit handler method - ModelState is "Valid"
2024-05-20 11:49:46.108 -05:00 [INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
2024-05-20 11:49:46.138 -05:00 [INF] Executed page /Login in 71.6366ms
2024-05-20 11:49:46.138 -05:00 [INF] Executed endpoint '/Login'
2024-05-20 11:49:46.140 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/login?ReturnUrl=%2FBeta%2Fadmin - 200 null text/html; charset=utf-8 152.2073ms
2024-05-20 11:49:46.296 -05:00 [INF] Startup complete.
2024-05-20 11:49:46.568 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/assets/css/site.css - null null
2024-05-20 11:49:46.575 -05:00 [INF] The file /css/site.css was not modified
2024-05-20 11:49:46.576 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/assets/css/site.css - 304 null text/css 7.7696ms
2024-05-20 11:49:46.577 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/assets/logo.png - null null
2024-05-20 11:49:46.579 -05:00 [INF] The file /logo.png was not modified
2024-05-20 11:49:46.579 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/assets/logo.png - 304 null image/png 2.541ms
2024-05-20 11:49:46.579 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/assets/webfonts/fonts.css - null null
2024-05-20 11:49:46.630 -05:00 [INF] The file /webfonts/fonts.css was not modified
2024-05-20 11:49:46.630 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/assets/webfonts/fonts.css - 304 null text/css 50.7182ms
2024-05-20 11:49:46.887 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/assets/webfonts/SFProDisplay-Semibold.ttf - null null
2024-05-20 11:49:46.894 -05:00 [INF] CORS policy execution failed.
2024-05-20 11:49:46.894 -05:00 [INF] Request origin https://dev.psu.domain.com does not have permission to access the resource.
2024-05-20 11:49:46.896 -05:00 [INF] The file /webfonts/SFProDisplay-Semibold.ttf was not modified
2024-05-20 11:49:46.896 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/assets/webfonts/SFProDisplay-Semibold.ttf - 304 null application/x-font-ttf 8.4947ms
2024-05-20 11:49:46.896 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/assets/webfonts/SFProDisplay-Black.ttf - null null
2024-05-20 11:49:46.898 -05:00 [INF] CORS policy execution failed.
2024-05-20 11:49:46.898 -05:00 [INF] Request origin https://dev.psu.domain.com does not have permission to access the resource.
2024-05-20 11:49:46.899 -05:00 [INF] The file /webfonts/SFProDisplay-Black.ttf was not modified
2024-05-20 11:49:46.899 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/assets/webfonts/SFProDisplay-Black.ttf - 304 null application/x-font-ttf 2.6933ms
2024-05-20 11:49:50.536 -05:00 [INF] Running health check: CPU Usage
2024-05-20 11:49:51.018 -05:00 [INF] PowerShell Universal performance counters do not exist.
2024-05-20 11:49:51.768 -05:00 [INF] Request starting HTTP/1.1 POST http://dev.psu.domain.com/Beta/api/v1/signin/form - application/x-www-form-urlencoded 29
2024-05-20 11:49:51.771 -05:00 [INF] CORS policy execution failed.
2024-05-20 11:49:51.772 -05:00 [INF] Request origin https://dev.psu.domain.com does not have permission to access the resource.
2024-05-20 11:49:51.777 -05:00 [INF] Executing endpoint 'UniversalDashboard.Controllers.AuthenticationController.SignInForm (Universal.Server)'
2024-05-20 11:49:51.805 -05:00 [INF] Route matched with {action = "SignInForm", controller = "Authentication", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] SignInForm(PowerShellUniversal.Credential) on controller UniversalDashboard.Controllers.AuthenticationController (Universal.Server).
2024-05-20 11:49:51.885 -05:00 [INF] Evaluting claims for admin, Cache: False
2024-05-20 11:49:51.952 -05:00 [INF] AuthenticationScheme: Cookies signed in.
2024-05-20 11:49:51.957 -05:00 [INF] Executing RedirectResult, redirecting to /Beta/admin.
2024-05-20 11:49:51.958 -05:00 [INF] Executed action UniversalDashboard.Controllers.AuthenticationController.SignInForm (Universal.Server) in 152.7007ms
2024-05-20 11:49:51.959 -05:00 [INF] Executed endpoint 'UniversalDashboard.Controllers.AuthenticationController.SignInForm (Universal.Server)'
2024-05-20 11:49:51.964 -05:00 [INF] Request finished HTTP/1.1 POST https://dev.psu.domain.com/Beta/api/v1/signin/form - 302 0 null 195.8409ms
2024-05-20 11:49:52.016 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/Beta/admin - null null
2024-05-20 11:49:52.032 -05:00 [INF] Executing endpoint '/_Host'
2024-05-20 11:49:52.038 -05:00 [INF] Route matched with {page = "/_Host", action = "", controller = ""}. Executing page /_Host
2024-05-20 11:49:52.039 -05:00 [INF] Executing an implicit handler method - ModelState is "Valid"
2024-05-20 11:49:52.039 -05:00 [INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
2024-05-20 11:49:52.162 -05:00 [INF] Running health check: Memory Utilization
2024-05-20 11:49:52.327 -05:00 [INF] Running health check: Disk Space
2024-05-20 11:49:52.332 -05:00 [INF] Running health check: PSScriptAnalyzer
2024-05-20 11:49:52.384 -05:00 [INF] Running health check: Conflicting Module
2024-05-20 11:49:52.396 -05:00 [INF] Running health check: Missing Environment
2024-05-20 11:49:52.606 -05:00 [INF] Executed page /_Host in 568.4557ms
2024-05-20 11:49:52.606 -05:00 [INF] Executed endpoint '/_Host'
2024-05-20 11:49:52.631 -05:00 [ERR] An unhandled exception has occurred while executing the request.
System.ArgumentException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')
   at Npgsql.Internal.Converters.DateTimeConverterResolver`1.Get(DateTime value, Nullable`1 expectedPgTypeId, Boolean validateOnly)
   at Npgsql.Internal.Converters.DateTimeConverterResolver.<>c.<CreateResolver>b__0_0(DateTimeConverterResolver`1 resolver, DateTime value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.Converters.DateTimeConverterResolver`1.Get(T value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.PgConverterResolver`1.GetAsObjectInternal(PgTypeInfo typeInfo, Object value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.PgResolverTypeInfo.GetResolutionAsObject(Object value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.PgTypeInfo.GetObjectResolution(Object value)
   at Npgsql.NpgsqlParameter.ResolveConverter(PgTypeInfo typeInfo)
   at Npgsql.NpgsqlParameter.ResolveTypeInfo(PgSerializerOptions options)
   at Npgsql.NpgsqlParameterCollection.ProcessParameters(PgSerializerOptions options, Boolean validateValues, CommandType commandType)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at PowerShellUniversal.MemoryTable`1..ctor(IEnumerable`1 items) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\MemoryTable.cs:line 10
   at PowerShellUniversal.Extensibility.EFTable`2.Where(Expression`1 predicate) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 366
   at Universal.Server.Pages.Index.OnInitializedAsync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Pages\Index.razor:line 115
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.<>c__DisplayClass36_0.<PrerenderComponentAsync>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<InvokeAsync>g__Execute|9_0[TResult](ValueTuple`3 state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.PrerenderComponentAsync(HttpContext httpContext, Type componentType, IComponentRenderMode prerenderMode, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at PowerShellUniversal.Pages__Host.<>c__DisplayClass11_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Pages\_Host.cshtml:line 32
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at PowerShellUniversal.Pages__Host.ExecuteAsync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Pages\_Host.cshtml:line 10
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at PowerShellUniversal.FeatureMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\FeatureMiddleware.cs:line 42
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at PowerShellUniversal.DisallowedModeMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\ModeMiddleware.cs:line 41
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at PowerShellUniversal.CspMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\CspMiddleware.cs:line 20
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Universal.Server.Middleware.RoutingMiddleware.Invoke(HttpContext httpContext, IPolicyEvaluator policyEvaluator) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\RoutingMiddleware.cs:line 152
   at PowerShellUniversal.PSUMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\PowerShellMiddleware.cs:line 43
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Universal.Server.Middleware.SwaggerAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\SwaggerAuthMiddleware.cs:line 51
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\actions-runner\_work\universal\universal\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 109
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
2024-05-20 11:49:52.711 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/Beta/admin - 500 null text/plain 694.9251ms
2024-05-20 11:50:11.033 -05:00 [INF] Starting heartbeat job.
2024-05-20 11:50:11.066 -05:00 [INF] Finished heartbeat job.

```

**Comment by adamdriscoll** [comment]
This was the issue I mentioned in #3341. I'll get the doc updated as well.

**Comment by Omzig** [comment]
This is a new issue using the new driver.

```json
  "Plugins": [
    "PostgreSQL"
  ],
  "SystemLogPath": "E:\\src\\psu\\Beta_data\\PowerShellUniversal\\systemLog.txt",
  "Data": {
    "RepositoryPath": "E:\\src\\psu\\Beta_data\\UniversalAutomation\\Repository",
    "ConnectionString": "User ID=me;Password=mySuperPass;Host=localhost;Port=5432;Database=PSUv5",
```

**Comment by adamdriscoll** [comment]
Sorry. I wasn't clear. I meant that the DateTime issue is the one I was mentioning in my comment on 3341. This has been resolved and will be in beta5. We'll be releasing in a day or two.

**Comment by Omzig** [comment]
> e'll be releasing in a day or two.

THANK you buddy!
