### ISSUE TITLE
[WRN] Error unprotecting the session cookie.

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#3369]
### Summary of the feedback

```2024-06-07 20:16:58.596 +01:00 [DBG] Using managed symmetric algorithm 'System.Security.Cryptography.Aes'.
2024-06-07 20:16:58.596 +01:00 [DBG] Using managed keyed hash algorithm 'System.Security.Cryptography.HMACSHA256'.
2024-06-07 20:16:58.597 +01:00 [DBG] Using key {a2f68a4b-7e38-48e0-972a-73de5c17f8de} as the default key.
2024-06-07 20:16:58.598 +01:00 [WRN] Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The key {bc782187-c871-4984-937a-59388eaea827} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

**Comment by alexrgreenwood** [comment]
only seem to get this when using the docker container 🤔

**Comment by adamdriscoll** [comment]
Adding the keys to the database rather than the file system. If they are stored in a non-persistent manner, this will happen when cookies are used that were generated with previous runs of the server.
