### ISSUE TITLE
Notification: Error	Invalid configuration: dashboards.ps1	No Execution Environment found

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3376]
### Version

5.0.0-beta5 (9424572094)

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

visit /admin/platform/notifications

is it invalid because i don't have dashboards.ps1?

![image](https://github.com/ironmansoftware/issues/assets/1987296/e92d2929-b69d-41a1-a942-a827f91d47d1)

### Expected behavior

```console
valid errors
```

### Actual behavior

```console
Error	Invalid configuration: dashboards.ps1	No Execution Environment found


 at UniversalAutomation.Common.Extensions.DatabaseExtensions.GetExecutionEnvironment(IDatabase database, String environmentName) in C:\actions-runner\_work\universal\universal\src\UniversalAutomation.Common\DatabaseExtensions.cs:line 34
   at Universal.Server.Services.DashboardProxy.Start(Dashboard dashboard) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Dashboard\DashboardProxy.cs:line 82
   at Universal.Server.Services.DashboardManager.StartOnNode(Dashboard dashboard) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Dashboard\DashboardManager.cs:line 87
   at UniversalAutomation.Services.DashboardsConfigurationScript.OnReadAfterAllAsync(Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Dashboards.cs:line 175
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(String rootPath, Boolean initialSync) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 380
```

**Comment by adamdriscoll** [comment]
It's the docs dashboard trying to start. It could be because of your environments.ps1 error because it uses the integrated environment.
