### ISSUE TITLE
	Value cannot be null. (Parameter 'name')

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3396]
### Version

5.0.0-beta6 (9491506309)

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

install current v5 beta

### Expected behavior

```console
no error in notification
```

### Actual behavior

```console
Error	Git Synchronization Failed	Value cannot be null. (Parameter 'name')


2024-06-13 10:07:07.503 -05:00 [ERR] Failed to sync: Value cannot be null. (Parameter 'name')    at LibGit2Sharp.Core.Ensure.ArgumentNotNull(Object argumentValue, String argumentName) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 24
   at LibGit2Sharp.Core.Ensure.ArgumentNotNullOrEmptyString(String argumentValue, String argumentName) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 50
   at LibGit2Sharp.Identity..ctor(String name, String email) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Identity.cs:line 21
   at UniversalAutomation.Git.GitService.Pull() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitService.cs:line 621
   at UniversalAutomation.GitSyncService.TrySync(GitStatus status, Boolean force, GitSettings settings) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 177
   at UniversalAutomation.GitSyncService.Sync(Boolean force) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 89
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/1987296/77c1c7c8-829d-43ef-877d-b8ede85b96c2)

**Comment by Omzig** [comment]
# Build
Beta7 (9637475131)

# Reopen
this is still a problem

![image](https://github.com/ironmansoftware/issues/assets/1987296/baaab700-7beb-4766-913e-9e6e63ee6b38)

**Comment by adamdriscoll** [comment]
This is because database isn't a valid URL. We dropped support for that in v5. We added a check for a valid URL in the UI now.

**Comment by Omzig** [comment]
> This is because database isn't a valid URL. We dropped support for that in v5. We added a check for a valid URL in the UI now.

is this in beta 7?

**Comment by adamdriscoll** [comment]
Yep. That's what you are seeing in #3439. There is an error under the remote input box.

**Comment by Omzig** [comment]
- #3439 fixes it
