### ISSUE TITLE
.\Universal.Agent not found

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3478]
### Version

4.3.2

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

```

2024-07-22 00:34:04.242 -05:00 [ERR] Error discovering modules
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'E:\src\psu\Beta\Agents\5.1\Universal.Agent' with working directory 'E:\src\psu\Beta_data\UniversalAutomation\Repository'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at UniversalAutomation.JobProcessManager.StartProcessAsCurrentUser(String powerShellPath, String commandLine, Variable credential, Action`1 onAgentOutput, Dictionary`2 environmentVariables) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 468
   at UniversalAutomation.JobProcessManager.StartModuleDiscovery(ExecutionEnvironment environment) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 344
   at Universal.Server.Services.ModuleService.Discover(ExecutionEnvironment environment, Boolean wait) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\ModuleService.cs:line 324
```

### Expected behavior

```console
no error
```

### Actual behavior

```console
Error discovering modules
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'E:\src\psu\Beta\Agents\5.1\Universal.Agent' with working directory 'E:\src\psu\Beta_data\UniversalAutomation\Repository'. The system cannot find the file specified.
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/a97c7443-ad50-499b-b5c3-76bea1c18ea0)

**Comment by Omzig** [comment]
Upgraded to RC4 with windows authentication enabled and we are seeing this error again...

```
2024-07-31 11:53:24.189 -05:00 [ERR] Error discovering modules
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'E:\src\psu\psuBlank\Agents\5.1\Universal.Agent.exe' with working directory 'E:\src\psu\psuBlank_data\UniversalAutomation\Repository'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at UniversalAutomation.JobProcessManager.StartProcessAsCurrentUser(String powerShellPath, String commandLine, Variable credential, Action`1 onAgentOutput, Dictionary`2 environmentVariables) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 474
   at UniversalAutomation.JobProcessManager.StartModuleDiscovery(ExecutionEnvironment environment) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 350
   at Universal.Server.Services.ModuleService.Discover(ExecutionEnvironment environment, Boolean wait) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\ModuleService.cs:line 324
```

**Comment by adamdriscoll** [comment]
Ack. That's my bad. We have this slight difference between the integration tests and the release package that I need to fix. This should be fixed now.
