### ISSUE TITLE
Issue with First Run page 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3492]
### Version

5.0.0-rc2

### Severity

Low

### Environment

msi

### Steps to Reproduce

https://forums.ironmansoftware.com/t/first-run-5-0-0rc3-not-working/11025

### Expected behavior

```console
Can change password
```

### Actual behavior

```console
Cannot change user\password
```

**Comment by alexrgreenwood** [comment]
with  5.0.0-rc4 (10153820210) 

I get nothing happening when clicking submit on the first-run page, logs say ...

```
2024-07-30 09:40:47.460 +01:00 [INF] Executing endpoint '/_Host'
2024-07-30 09:40:47.503 +01:00 [INF] Request finished HTTP/1.1 GET http://localhost:5001/assets/webfonts/SFProDisplay-Semibold.ttf - 200 435008 application/x-font-ttf 694.7983ms
2024-07-30 09:40:47.534 +01:00 [INF] Route matched with {page = "/_Host", action = "", controller = ""}. Executing page /_Host
2024-07-30 09:40:47.594 +01:00 [INF] Executing an implicit handler method - ModelState is "Valid"
2024-07-30 09:40:47.631 +01:00 [INF] Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
2024-07-30 09:40:47.862 +01:00 [INF] Executed page /_Host in 260.2398ms
2024-07-30 09:40:47.872 +01:00 [INF] Executed endpoint '/_Host'
2024-07-30 09:40:47.889 +01:00 [INF] Request finished HTTP/1.1 GET http://localhost:5001/js/timezone.js - 200 null text/html; charset=utf-8 1044.813ms
2024-07-30 09:40:47.988 +01:00 [WRN] Unhandled exception rendering component: Failed to fetch dynamically imported module: http://localhost:5001/js/timezone.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5001/js/timezone.js
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:5001/js/timezone.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5001/js/timezone.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at PowerShellUniversal.InitializeTimeZone.OnAfterRenderAsync(Boolean firstRender) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Components\InitializeTimeZone.cs:line 18
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-07-30 09:40:48.288 +01:00 [ERR] Unhandled exception in circuit 'Up-p3yHFaHnXm6td9aVGwJ_IZ0P-FHN0JHiwPqCO8to'.
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://localhost:5001/js/timezone.js
TypeError: Failed to fetch dynamically imported module: http://localhost:5001/js/timezone.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at PowerShellUniversal.InitializeTimeZone.OnAfterRenderAsync(Boolean firstRender) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Components\InitializeTimeZone.cs:line 18
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```
