### ISSUE TITLE
time picker, timezone broke

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3505]
### Version

5.0.0-rc4

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- go to /apps/docs/Time-Picker
- scroll down to TimeZone

### Expected behavior

```console
control shown
```

### Actual behavior

```console
Error rendering component (mu-timepicker)
RangeError: Invalid time zone specified: #<Object>

    at https://dev.psu.domain.com/Beta/apps/docs/4408.0c365afec301e59b223a.bundle.js:1:1648
    at c (https://dev.psu.domain.com/Beta/apps/docs/6157.1017a371da6d8a110ea2.bundle.js:1:14281)
    at https://dev.psu.domain.com/Beta/apps/docs/4408.0c365afec301e59b223a.bundle.js:1:36565
    at https://dev.psu.domain.com/Beta/apps/docs/4408.0c365afec301e59b223a.bundle.js:1:41803
    at c (https://dev.psu.domain.com/Beta/apps/docs/6157.1017a371da6d8a110ea2.bundle.js:1:14281)
    at div
    at v (https://dev.psu.domain.com/Beta/apps/docs/9972.38b0378f1be2cf5f205e.bundle.js:1:499)
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:655014
    at r (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1611087)
    at Suspense
    at div
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:2:10117
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:102:107817
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:655014
    at r (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1611087)
    at Suspense
    at main
    at F (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:530810)
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:655014
    at t (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1390358)
    at t (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1392341)
    at div
    at Suspense
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:655014
    at Suspense
    at u (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:63924)
    at m (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:64431)
    at g (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:64648)
    at s (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:77866)
    at r (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1446019)
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1446895
    at Dashboard (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:581932)
    at t (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1390358)
    at t (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1392341)
    at div
    at qe (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1624103)
    at Ye (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1625308)
    at Xe (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1624739)
    at nt (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1628092)
    at t (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1387079)
    at t (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1381663)
    at d (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1358274)
    at l (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1080462)
    at r (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1446019)
    at https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1446895
    at bt (https://dev.psu.domain.com/Beta/apps/docs/index.f1205c274e2cc29cda28.bundle.js:152:1630162)
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/1e850f98-871b-4185-9167-3d913ca6a721)

**Comment by adamdriscoll** [comment]
This is also present in 4.3.4 and a fix should be merged back.
