### ISSUE TITLE
Unable to go to roles

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3519]
### Version

5.0.0-rc4

### Severity

Critical

### Environment

Nested IIS

### Steps to Reproduce

- go to Security
- then Roles

### Expected behavior

```console
access to roles
```

### Actual behavior

```console
Paywall
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/ce31f075-07bb-4ba6-b47f-709a0b012b01)

**Comment by adamdriscoll** [comment]
I can't reproduce this. 

![image](https://github.com/user-attachments/assets/b66fec68-5fae-4132-be2c-e3cf877c88d9)

I have my license set in an environment variable, though that _shouldn't_ matter. 

![image](https://github.com/user-attachments/assets/c152cbbe-37c8-4dc8-8109-b37678581abb)

**Comment by Omzig** [comment]
its also in the db, and i cannot see it in the list, but i can open the db and see it there. does that matter?

**Comment by adamdriscoll** [comment]
It shouldn't matter. Let me double check this on my IIS nested site (also shouldn't matter)... 

Do you have this problem trying to view other licensed pages? Terminals, triggers etc.

**Comment by Omzig** [comment]
even with debug on, i do not see anything in the logs that would help me figure out why roles kicks a 'Roles requires a license. Please enter a license key to use this feature.' message :(

**Comment by adamdriscoll** [comment]
Yeah that's pretty weird. The license check code is the same throughout the console so I would expect if one page did it, all of them would. I'll mess around with it to see if I can get it to barf.

**Comment by Omzig** [comment]
i wonder if it is a nested iis thing?

**Comment by mwatts-seg** [comment]
@adamdriscoll 
I am also experiencing this issue with RC5 nightly. 
We were able to access roles for a while, started messing with SSO, then started getting the paywall screen.

**Comment by adamdriscoll** [comment]
@mwatts-seg Are you IIS or Kestrel? I kinda don't think that's the issue but good data point.

**Comment by mwatts-seg** [comment]
> @mwatts-seg Are you IIS or Kestrel? I kinda don't think that's the issue but good data point.

We are using Kestrel. When I first installed RC5 Nightly (7/30), it resolved the first run issue I had. Was able to get the branding & license installed. From that point, we were working on configuring SSO with Entra. We were noticing some oddities with the group, so we went to change the claim for 'Administrators' role and hit the paywall.

So it did not manifest until we started messing with SSO.

**Comment by Omzig** [comment]
> It shouldn't matter. Let me double check this on my IIS nested site (also shouldn't matter)...
> 
> Do you have this problem trying to view other licensed pages? Terminals, triggers etc.

yes, all the other pages work, even documentation.

**Comment by mwatts-seg** [comment]
@adamdriscoll  Definitely odd. It seems to be the only page that does this: 

![image](https://github.com/user-attachments/assets/65a9b8ad-6220-42ac-ae6c-528f8c8ed8bb)

Clicking 'Roles' takes awhile for the screen to pop up, here is what I seen in the console: 

```
blazor.server.js:1  [2024-08-02T15:06:13.842Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at PowerShellUniversal.PermissionDrawer.OnParametersSetAsync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Security\PermissionDrawer.razor:line 60
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

Edit: 
I did experience this today briefly on Authentication page. 
I added OpenID, went to enable it before modifying it. Page became unresponsive (could not disable or edit), refreshing page caused a pay wall screen to show. I was able to refresh 2-3 times and it went away on that page.

**Comment by Omzig** [comment]
# Build 5.0.0-rc5 (10241831296)
Does not allow /roles to be access now, it just goes to a white page
or sometimes it goes to Page Not Found

## Logs found
```console
2024-08-06 11:26:46.469 -05:00 [ERR] Navigation failed when changing the location to ./admin/security/roles
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
2024-08-06 11:26:46.470 -05:00 [ERR] Unhandled exception in circuit 'K39PbIW_kl__efb8bnISHwHFqo2qU6GN7t0Hu3t4waE'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
```

**Comment by adamdriscoll** [comment]
I didn't change anything in the last few nightly builds for this. That said, after seeing this log message, I was able to reproduce this and it should be resolved. 

```
blazor.server.js:1  [2024-08-02T15:06:13.842Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at PowerShellUniversal.PermissionDrawer.OnParametersSetAsync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Security\PermissionDrawer.razor:line 60
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

@Omzig - You don't have this error message in your logs at all? It might have been before the one you posted. 

I've also put in some better error boundaries around the console to provide a better idea of where errors are coming from and prevent the console from becoming completely unresponsive.

**Comment by Omzig** [comment]
oh i found this one:

```console
2024-08-06 11:25:46.551 -05:00 [WRN] Unhandled exception rendering component: Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at PowerShellUniversal.PermissionDrawer.OnParametersSetAsync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Security\PermissionDrawer.razor:line 60
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

2024-08-06 11:25:46.560 -05:00 [ERR] Unhandled exception in circuit 'K39PbIW_kl__efb8bnISHwHFqo2qU6GN7t0Hu3t4waE'.
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at PowerShellUniversal.PermissionDrawer.OnParametersSetAsync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Security\PermissionDrawer.razor:line 60
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2024-08-06 11:25:46.566 -05:00 [WRN] Unhandled exception rendering component: Cannot access a disposed object.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-08-06 11:25:46.567 -05:00 [ERR] Unhandled exception in circuit 'K39PbIW_kl__efb8bnISHwHFqo2qU6GN7t0Hu3t4waE'.
System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by adamdriscoll** [comment]
Awesome. That's the one. This should be resolved. 

Blazor's default exception behavior is to blow up into a fireball of errors. Trying to mitigate that a bit....
