### ISSUE TITLE
psudb.exe Unhandled exception. System.InvalidOperationException

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3520]
### Version

5.0.0-rc4

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

i am getting an error when i run this:
- `psudb.exe -p E:\src\psu\psuSandbox_data\UniversalAutomation\databaseOLD.db`

### Expected behavior

```console
new db file
```

### Actual behavior

```console
E:\src\psu\psuSandbox>psudb.exe -p E:\src\psu\psuSandbox_data\UniversalAutomation\databaseOLD.db
Converting LiteDB database to SQLite at E:\src\psu\psuSandbox_data\UniversalAutomation\databaseOLD.db.
Creating backup at E:\src\psu\psuSandbox_data\UniversalAutomation\databaseOLD.bak.
Moving identities.
Moving app tokens.
Unhandled exception. System.InvalidOperationException: The instance of entity type 'Identity' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at PSUDatabase.LiteDBConverter.Convert(String path) in C:\actions-runner\_work\universal\universal\src\PSUDatabase\LiteDBConverter.cs:line 35
   at PSUDatabase.Program.<>c.<Main>b__0_0(Options o) in C:\actions-runner\_work\universal\universal\src\PSUDatabase\Program.cs:line 18
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PSUDatabase.Program.Main(String[] args) in C:\actions-runner\_work\universal\universal\src\PSUDatabase\Program.cs:line 15
```

**Comment by adamdriscoll** [comment]
Can you share this DB file?

**Comment by Omzig** [comment]
@adamdriscoll, sent you the old db in an email

**Comment by adamdriscoll** [comment]
Can you send me the LiteDB file? It looks like you sent the SQLite one.

**Comment by Omzig** [comment]
databaseOLD.7z is the LiteDB file

**Comment by adamdriscoll** [comment]
I dont have that attachment. Just database.zip.

**Comment by Omzig** [comment]
#FacePalm, i cannot send an 8mb file to you, email blocked it
