### ISSUE TITLE
Fatal Error: No authenticationScheme was specified

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3523]
### Version

5.0.0-rc4

### Severity

Critical

### Environment

Nested IIS

### Steps to Reproduce

- install a blank psu instance v4.3.4
- enable windows authentication
- upgrade to v5.0.0-rc4
- go to /nestedSite/admin

### Expected behavior

```console
takes you to the admin site after it authenticates
```

### Actual behavior

```console
Request URL: https://dev.psu.domain.com/psuBlank/admin
Request Method: GET
Status Code: 500 Internal Server Error

No authentication handler is registered for the scheme 'Windows'. The registered schemes are: PSU, Bearer, Identity.External, Cookies, Basic. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Windows",...)?

----------- logs:
2024-07-31 12:02:13.741 -05:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Universal.Server.Middleware.RoutingMiddleware.Invoke(HttpContext httpContext, IPolicyEvaluator policyEvaluator) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\RoutingMiddleware.cs:line 175
   at PowerShellUniversal.PSUMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\PowerShellMiddleware.cs:line 43
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Universal.Server.Middleware.WindowsAuthMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\WindowsAuthMiddleware.cs:line 27
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Universal.Server.Middleware.SwaggerAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Middleware\SwaggerAuthMiddleware.cs:line 51
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\actions-runner\_work\universal\universal\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 109
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
2024-07-31 12:02:13.754 -05:00 [DBG] No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
2024-07-31 12:02:13.759 -05:00 [DBG] Connection id "0HN5HG53RNFU7" completed keep alive response.
2024-07-31 12:02:13.759 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/psuBlank/admin - 500 null text/plain 54.9495ms
```

### Additional Environment data

Before the upgrade, windows auth was working.

**Comment by Omzig** [comment]
@adamdriscoll, let me know if you need to see it ;)

**Comment by Omzig** [comment]
# authentication.ps1
```powershell
Set-PSUAuthenticationMethod -Type "Form" -ScriptBlock {
    param(
        [PSCredential]$Credential
    )

    #
    #   You can call whatever cmdlets you like to conduct authentication here.
    #   Just make sure to return the $Result with the Success property set to $true
    #

    New-PSUAuthenticationResult -ErrorMessage 'Bad username or password'
} 
Set-PSUAuthenticationMethod -Type "Windows"
```

# web.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\Universal.Server.exe" arguments="--appsettings E:\src\psu\appsettings.psuBlank.json" forwardWindowsAuthToken="true" stdoutLogEnabled="true" stdoutLogFile=".\logs\log" hostingModel="OutOfProcess" />
         <security>
            <authentication>
                <windowsAuthentication enabled="true" useKernelMode="true">
                    <extendedProtection tokenChecking="Allow" />
                    <providers>
                        <clear />
                        <add value="NTLM" />
                    </providers>
                </windowsAuthentication>
            </authentication>
        </security>
  </system.webServer>
</configuration>
<!--ProjectGuid: 588ACF2E-9AE5-4DF1-BC42-BCE16A4C4EDE-->
```

# appsettings.json
```json
{
	"Kestrel": {
		"Endpoints": {
			"HTTP": {
				"Url": "http://*:5000"
			}
		},
		"RedirectToHttps": "false",
		"UseHttpSys": "false",
		"BasePath": "/psuBlank",
		"Hsts": {
			"MaxAgeDays": 365
		},
		"CookiePolicy": "",
		"CookiePrefix": "dd-cookie-monster"
	},
	"ApplicationInsights": {
		"InstrumentationKey": ""
	},
	"AllowedHosts": "*",
	"CorsHosts": "",
	"Plugins": [
		"SQLite"
	],
	"SystemLogPath": "E:\\src\\psu\\psuBlank_data\\PowerShellUniversal\\systemLog.txt",
	"SystemLogLevel": "Debug",
	"Data": {
		"RepositoryPath": "E:\\src\\psu\\psuBlank_data\\UniversalAutomation\\Repository",
		"ConnectionString": "filename=E:\\src\\psu\\psuBlank_data\\UniversalAutomation\\database.db",
		"RunMigrations": true,
		"GitRemote": "",
		"GitUserName": "",
		"GitPassword": "",
		"GitBranch": "",
		"GitSyncBehavior": "TwoWay",
		"GitInitializeBehavior": "",
		"GitSyncInterval": "1",
		"GitSyncTimeout": 60,
		"ConfigurationScript": "",
		"Mode": "Manual"
	},
	"Api": {
		"OpenAPI": {
			"Name": "Endpoints",
			"Description": "Endpoints defined within the PowerShell Universal admin console.",
			"Url": "v2",
			"Version": "v2"
		},
		"Url": "/psuBlank",
		"GrpcPort": 0
	},
	"Authentication": {
		"Windows": {
			"Enabled": "false"
		},
		"WSFed": {
			"Enabled": "false",
			"MetadataAddress": "",
			"Wtrealm": "",
			"CallbackPath": "/auth/signin-wsfed",
			"Wreply": "",
			"UseTokenLifetime": true,
			"CorrelationCookieSameSite": ""
		},
		"OIDC": {
			"Enabled": "false",
			"CallbackPath": "/auth/signin-oidc",
			"ClientID": "",
			"ClientSecret": "",
			"Resource": "",
			"Authority": "",
			"ResponseType": "",
			"SaveTokens": "false",
			"CorrelationCookieSameSite": "",
			"UseTokenLifetime": true,
			"Scope": "openid profile groups",
			"GetUserInfo": false
		},
		"ClientCertificate": {
			"Enabled": "false"
		},
		"SessionTimeout": "25"
	},
	"Jwt": {
		"SigningKey": "PleaseUseYourOwnSigningKeyHere",
		"Issuer": "IronmanSoftware",
		"Audience": "PowerShellUniversal"
	},
	"UniversalAutomation": {
		"Queues": [],
		"JobHandshakeTimeout": 30,
		"JobDebugging": false,
		"ContinueJobOnServerStop": false,
		"HangfireWorkerCount": 100
	},
	"UniversalDashboard": {
		"AssetsFolder": "E:\\src\\psu\\psuBlank_data\\PowerShellUniversal\\Dashboard",
		"DashboardStartupTimeout": 10
	},
	"Secrets": {
		"SecretStore": {
			"Password": "PSUSecretStore"
		},
		"Database": {
			"EncryptionKey": "xxxxxxxxxxxxxxx"
		}
	},
	"ShowDevTools": false,
	"HideAdminConsole": false,
	"Profiling": false,
	"NodeName": ""
}
```

**Comment by adamdriscoll** [comment]
Will give it a go and let you know.

**Comment by adamdriscoll** [comment]
I can reproduce this.

**Comment by Omzig** [comment]
> I can reproduce this.

i have 2 instances that do this currently
