### ISSUE TITLE
Clicking Save causes Page Not Found

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3577]
### Version

5.0.0-rc5

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- configure git
- click edit
- make some changes
- click save

### Expected behavior

```console
goes to a commit site
```

### Actual behavior

```console
page not found
```

### Additional Environment data

Logs that i think are related:
```console
2024-08-09 14:30:13.335 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/psuSandbox/admin/settings/git/commit - 200 null text/html 14.4061ms
2024-08-09 14:30:13.602 -05:00 [INF] Executed endpoint '/_blazor'
2024-08-09 14:30:13.602 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/psuSandbox/_blazor?id=aDifqRFBOiduDLpPiBAt3w - 101 null null 40582.0859ms
2024-08-09 14:30:13.916 -05:00 [INF] Request starting HTTP/1.1 POST http://dev.psu.domain.com/psuSandbox/_blazor/disconnect - multipart/form-data; boundary=----WebKitFormBoundaryMhWT0cvUnIzYPV8U 359
2024-08-09 14:30:13.920 -05:00 [INF] Evaluating claims for username, Cache: True
2024-08-09 14:30:13.924 -05:00 [INF] CORS policy execution failed.
2024-08-09 14:30:13.924 -05:00 [INF] Request origin https://dev.psu.domain.com does not have permission to access the resource.
2024-08-09 14:30:13.927 -05:00 [INF] Executing endpoint 'Blazor disconnect'
2024-08-09 14:30:13.961 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/psuSandbox/api/v1/alive - null null
2024-08-09 14:30:13.963 -05:00 [INF] Evaluating claims for username, Cache: True
2024-08-09 14:30:13.977 -05:00 [INF] Executing endpoint 'UniversalAutomation.AliveController.Get (Universal.Server)'
2024-08-09 14:30:13.977 -05:00 [INF] Route matched with {action = "Get", controller = "Alive", page = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller UniversalAutomation.AliveController (Universal.Server).
2024-08-09 14:30:13.977 -05:00 [INF] Executing action method UniversalAutomation.AliveController.Get (Universal.Server) - Validation state: "Valid"
2024-08-09 14:30:13.980 -05:00 [INF] Executed action method UniversalAutomation.AliveController.Get (Universal.Server), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 2.1937ms.
2024-08-09 14:30:13.981 -05:00 [INF] Executing OkObjectResult, writing value of type '<>f__AnonymousType1`7[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
2024-08-09 14:30:13.981 -05:00 [INF] Executed action UniversalAutomation.AliveController.Get (Universal.Server) in 3.8743ms
2024-08-09 14:30:13.981 -05:00 [INF] Executed endpoint 'UniversalAutomation.AliveController.Get (Universal.Server)'
2024-08-09 14:30:13.981 -05:00 [INF] Request finished HTTP/1.1 GET https://dev.psu.domain.com/psuSandbox/api/v1/alive - 200 142 application/json; charset=utf-8 20.6609ms
2024-08-09 14:30:14.165 -05:00 [INF] Request starting HTTP/1.1 GET http://dev.psu.domain.com/psuSandbox/api/internal/dashboard - null null
2024-08-09 14:30:14.166 -05:00 [ERR] Unhandled error invoking circuit handler type PowerShellUniversal.AdminConsoleCircuitHandler.OnConnectionDownAsync: SQLite Error 5: 'database is locked'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at PowerShellUniversal.Extensibility.EFTable`2.Update(T item) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 181
   at PowerShellUniversal.AdminConsoleCircuitHandler.OnConnectionDownAsync(Circuit circuit, CancellationToken cancellationToken) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\AdminConsoleCircuit.cs:line 36
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.OnConnectionDownAsync(CancellationToken cancellationToken)

restarted the app pool

2024-08-09 14:39:30.948 -05:00 [WRN] Failed to process the job 'ab69a3a4-6fe6-4a76-bc26-5ad6315cb93c': an exception occured. Job was automatically deleted because the retry attempt count exceeded 0.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at PowerShellUniversal.Extensibility.EFTable`2.Update(T item) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 181
   at UniversalAutomation.HeartBeatService.Run() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\HeartBeatService.cs:line 81
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by adamdriscoll** [comment]
I cannot reproduce this. Clicking saving forwards to the commit page in a nested site for me.

**Comment by Omzig** [comment]
since i have installed 5.0.0, this is no longer a problem, we can close this, i think.
