### ISSUE TITLE
Build Error when using Visual Studio 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#360]
```
------ Build started: Project: REMOVED, Configuration: Debug Any CPU ------
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\PowerShell Tools for Visual Studio\PowerShellProTools.targets(4,5): error MSB4018: The "PowerShellPackageTask" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at PowerShellToolsPro.MsBuild.PowerShellPackageTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Done building project "REMOVED.pssproj" -- FAILED.
```

https://forums.ironmansoftware.com/t/getting-error-while-generating-exe/5347/9

**Comment by adamdriscoll** [comment]
Resolved and will be available in 2021.9.0.
