### ISSUE TITLE
Transfer list not working in v5

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3634]
### Version

5.0.0

### Severity

Low

### Environment

msi

### Steps to Reproduce

Error in docs page when viewing transfer list. 

### Expected behavior

```console
Works
```

### Actual behavior

```console
JS error
```

**Comment by ad-85** [comment]
Also experiencing this. Fresh v5 MSI install, manually uninstalled v4 beforehand and deleted the database & appsettings.json files from ProgramData.

Here are the error details from the page at `/apps/docs/Transfer-List`:

```
Error rendering component (mu-transfer-list)
ReferenceError: handleAllLeft is not defined

    at x (http://localhost:5000/apps/docs/6121.f97c1295a5480d0e6483.bundle.js:1:2797)
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:638895
    at r (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1594297)
    at Suspense
    at div
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:2:10115
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:102:107829
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:638895
    at r (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1594297)
    at Suspense
    at main
    at L (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:523864)
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:638895
    at t (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1373894)
    at t (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1375877)
    at div
    at Suspense
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:638895
    at Suspense
    at u (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:63917)
    at h (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:64424)
    at g (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:64641)
    at s (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:77858)
    at r (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1429565)
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1430441
    at Dashboard (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:567347)
    at t (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1373894)
    at t (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1375877)
    at div
    at $e (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1606122)
    at Je (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1607328)
    at Ye (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1606758)
    at tt (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1608767)
    at t (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1370615)
    at t (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1365213)
    at d (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1341825)
    at l (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1064332)
    at r (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1429565)
    at http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1430441
    at dt (http://localhost:5000/apps/docs/index.99ce6cb36c0e1b4d6228.bundle.js:152:1610243)
```

![image](https://github.com/user-attachments/assets/eb684b0c-8821-4f04-91d5-8fa82ee882bc)
