### ISSUE TITLE
Unable to create schedule / Created schedules will not run

### ISSUE THREAD

**Issue by tempest918** [ironmansoftware/powershell-universal#3647]
### Version

5.0.0

### Severity

Critical

### Environment

msi

### Steps to Reproduce

When creating a simple or CRON schedule I receive an error upon saving the file which  states "Invalid configuration: schedules.ps1 Object reference not set to an instance of an object."  The schedule is formatted correctly when looking at the schedules.ps1 file but the schedule that shows up in the dashboard will never execute.

 at UniversalAutomation.JobService.AddOrUpdateRecurringJob(Script script, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobService.cs:line 595
   at UniversalAutomation.JobService.ScheduleJob(Script script, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobService.cs:line 534
   at UniversalAutomation.Services.SchedulesConfigurationScript.OnReadAfterUpdateAsync(Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Schedules.cs:line 130
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(SyncContext syncContext) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 446

### Expected behavior

```console
Schedule is created successfully and schedule runs as expected.
```

### Actual behavior

```console
An error is thrown and no schedule in the schedules.ps1 file will execute.
```

### Additional Environment data

Windows Server 2016

### Screenshots/Animations

https://github.com/user-attachments/assets/13361bda-13a5-49f0-99e2-c5d7846a375e

**Comment by adamdriscoll** [comment]
Aside from WinServer 2016, anything else interesting in this configuration? It seems pretty bare bones. Are you running Kestrel or IIS? I don't see this on 2019 or Win11. Not sure if that's related but could spin up a 2016 server to see if I can reproduce.

**Comment by tempest918** [comment]
It is a brand new installation of 5.0.0 on Windows Server 2016.  Installed
directly from the MSI, the only configuration change was the port number
which is running on 80.  It is using the built in Kestrel, not IIS.
