### ISSUE TITLE
psudb.exe error

### ISSUE THREAD

**Issue by emoeckel** [ironmansoftware/powershell-universal#3670]
### Version

4.3.4

### Severity

Critical

### Environment

msi

### Steps to Reproduce

run the psudb.exe against the litedb database

### Expected behavior

```console
A new SQLite db.
```

### Actual behavior

```console
Some errors:

PS SomeDirectory> .\psudb.exe --Path "$ENV:ProgramData\UniversalAutomation\database.db"
[00:00:00.0005002] Converting LiteDB database to SQLite at C:\ProgramData\UniversalAutomation\database.db.
[00:00:00.0022555] Creating backup at C:\ProgramData\UniversalAutomation\database.bak.
[00:00:10.8934532] Moving identities.
[00:00:11.0761565] Moving app tokens.
[00:00:11.3057755] Moving git statuses.
[00:00:11.3103505] Moving git settings.
[00:00:11.3169164] Moving licenses.
[00:00:11.3219499] Moving secrets.
[00:00:11.3774027] Moving terminal instances.
[00:00:11.3782709] Moving terminal history.
[00:00:11.3790827] Moving notifications.
[00:00:11.3805691] Moving health checks.
[00:00:11.4077836] Moving computers.
[00:00:11.4085425] Moving variable values.
[00:00:11.4291456] Moving 118 jobs.
[00:00:11.4292696] Loading 2178 job output....
[00:00:11.5744863] Moving job 2008.
[00:00:11.6851584] Moving job 2009.
[00:00:11.6910545] Moving job 2010.
[00:00:11.6965622] Moving job 2011.
[00:00:11.7016792] Moving job 2012.
[00:00:11.7068115] Moving job 2013.
[00:00:11.7118104] Moving job 2014.
[00:00:11.7166065] Moving job 2015.
[00:00:11.7216315] Moving job 2016.
[00:00:11.7300254] Moving job 2017.
[00:00:11.7827127] Batch complete. Processed 10 jobs.
[00:00:11.7940805] Moving job 2018.
[00:00:11.7992986] Moving job 2019.
[00:00:11.8045726] Moving job 2020.
[00:00:11.8095121] Moving job 2021.
[00:00:11.8143635] Moving job 2022.
[00:00:11.8196557] Moving job 2023.
[00:00:11.8245065] Moving job 2024.
[00:00:11.8332232] Moving job 2025.
[00:00:11.8382007] Moving job 2026.
Unhandled exception. System.InvalidOperationException: The instance of entity type 'AppToken' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at PSUDatabase.LiteDBConverter.Convert(String path) in C:\actions-runner\_work\universal\universal\src\PSUDatabase\LiteDBConverter.cs:line 173
   at PSUDatabase.Program.<>c.<Main>b__0_0(Options o) in C:\actions-runner\_work\universal\universal\src\PSUDatabase\Program.cs:line 18
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PSUDatabase.Program.Main(String[] args) in C:\actions-runner\_work\universal\universal\src\PSUDatabase\Program.cs:line 15

```

### Additional Environment data

4.3.4 is where I currently am, I am using the psudb.exe from 5.0.4 zip. As a side note, I tried just proceeding with the install of 5, and ran into issues as well, so looks like this error for the DB is a show stopper for me upgrading. Thanks!

**Comment by adamdriscoll** [comment]
Thanks the log was helpful. I was able to setup a configuration that reproduced this.
