### ISSUE TITLE
Error reading message

### ISSUE THREAD

**Issue by emoeckel** [ironmansoftware/powershell-universal#3700]
### Version

5.0.5

### Severity

High

### Environment

msi

### Steps to Reproduce

Writing large amounts of data to the cache (persistent or not)

### Expected behavior

```console
Just caching the data/objects.
```

### Actual behavior

```console
Receiving the following error in my script.

2024-09-03 14:15:57.723 -07:00 [INF] Request starting HTTP/1.1 POST http://localhost:443/PowerShellUniversal.PublicClient/SetCacheItem - application/grpc-web null
2024-09-03 14:15:57.729 -07:00 [INF] Executing endpoint 'gRPC - /PowerShellUniversal.PublicClient/SetCacheItem'
2024-09-03 14:15:57.729 -07:00 [INF] Error reading message.
Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.TryReadMessage(ReadOnlySequence`1& buffer, HttpContextServerCallContext context, ReadOnlySequence`1& message)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
2024-09-03 14:15:57.730 -07:00 [INF] Error status code '"ResourceExhausted"' with detail 'Received message exceeds the maximum configured message size.' raised.
2024-09-03 14:15:57.730 -07:00 [INF] Executed endpoint 'gRPC - /PowerShellUniversal.PublicClient/SetCacheItem'
2024-09-03 14:15:57.730 -07:00 [INF] Request finished HTTP/1.1 POST http://localhost:443/PowerShellUniversal.PublicClient/SetCacheItem - 200 0 application/grpc-web 6.8254ms
2024-09-03 14:15:57.730 -07:00 [INF] Connection id "0HN6CATHP47J1", Request id "0HN6CATHP47J1:00000001": the application completed without reading the entire request body.
2024-09-03 14:15:57.794 -07:00 [INF] Job 2186 completed
```

### Additional Environment data

FWIW I am pulling RVTools data (vCenter Exports) into powershell with Import-Excel and then pushing that data as cache for use with APIs and whatever else. I have went though my script adding "Write-Hosts" to see exactly where this is occuring, and its with the Set-PSUCache. For example here is some code pulled out, using -Persist or not, same behavior

$RvTools_Import_vInfo += Import-Excel -Path $file -WorksheetName vInfo
Set-PSUCache -Key "Cache_RVTools_vInfo" -Value ($RvTools_Import_vInfo) -Persist -AbsoluteExpirationFromNow ([TimeSpan]::FromHours(25))

**Comment by emoeckel** [comment]
I should also add, this has been working before upgrading to 5.

**Comment by adamdriscoll** [comment]
We've changed the max message size from 4mb (default) to unlimited.

**Comment by emoeckel** [comment]
I installed the 5.0.5 recent nightly, I saw in the change log that this fix was included. But still running into the same issue. Is this expected?

**Comment by rwidmark** [comment]
@adamdriscoll  you should re-open this issue, it's not fixed in nightly
