### ISSUE TITLE
Schedules still won't work in PSU 5.0.6

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3721]
### Version

5.0.5

### Severity

Critical

### Environment

msi

PSU: 5.0.6
Database: SQLLite
OS: WIndows Server 2022
PowerShell: 7.4.5

### Steps to Reproduce

_(I have also opened a support case for this, ticket ID 9208)_
I have tried everything now but Schedules still won't work for me in PSU 5 I have even tried PSU 5.0.6.
Re-installed everything, made it completely fresh etc. but nothing works.
Triggers works perfectly and also if I do execute the scripts directly.
And everything works in PSU 4.4.0
If I go to admin and then click to view the code for the script I can view the code etc. so the path are nothing wrong with but still the schedule won't work.

settings.ps1
```
ScriptBaseFolder = "Scripts"
```

schedules.ps1
```
$Parameters = @{
    Cron               = "*/10 * * * *"
    Script             = "Cache\test.ps1"
    TimeZone           = "Europe/Stockholm"
    Environment        = "Standard"
    Name               = "Test"
    Timeout            = 15
    RandomDelay        = $true
    RandomDelayMaximum = 5
}
New-PSUSchedule @Parameters
```

It do seem as it loads the schedules if I read the log file but it also show some errors if (error you can see under Acutal behavior)
```
2024-09-09 08:45:24.065 +02:00 [INF] Scheduling script 6 on schedule */10 * * * * with time zone Europe/Stockholm.
2024-09-09 08:45:24.067 +02:00 [INF] Scheduling job 'xxxx' with schedule Cache persistent VDI assignment on time zone Europe/Stockholm
```

### Expected behavior

```console
Schedule should work
```

### From Log

Under Schedule everything is empty, see screenshot
![CleanShot 2024-09-09 at 08 34 52](https://github.com/user-attachments/assets/2364e506-86fc-4fe2-915b-6b68b7885afc)

I did find the following from the log file:

```
2024-09-09 08:45:15.820 +02:00 [WRN] Signature not recognized for PowerShellUniversal.IConfigurationSystemWatcher.Pause; method will not be bound
2024-09-09 08:45:15.820 +02:00 [WRN] Signature not recognized for PowerShellUniversal.IConfigurationSystemWatcher.CheckSum; method will not be bound
```

```
2024-09-09 08:45:15.775 +02:00 [WRN] Signature not recognized for PowerShellUniversal.IPublicClient.NewAuthenticationMethod; method will not be bound
2024-09-09 08:45:29.153 +02:00 [INF] Request finished HTTP/2 POST https://xxx.xx.com/_blazor/negotiate?negotiateVersion=1 - 200 316 application/json 103.3439ms
2024-09-09 08:45:29.188 +02:00 [INF] Request starting HTTP/1.1 GET https://xxx.xx.com/_blazor?id=OPbJqs_RCBFDeDnL9Cdstw - null null
2024-09-09 08:45:29.193 +02:00 [INF] CORS policy execution failed.
2024-09-09 08:45:29.193 +02:00 [INF] Request origin https://xxx.xx.com does not have permission to access the resource.
```

```
2024-09-09 08:45:25.960 +02:00 [INF] Scheduler meta-data: Quartz Scheduler (v3.3.3.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 100 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.
```

### Screenshots/Animations

![CleanShot 2024-09-09 at 08 34 52](https://github.com/user-attachments/assets/2364e506-86fc-4fe2-915b-6b68b7885afc)

**Comment by adamdriscoll** [comment]
Do you have any error notifications? I used the same schedule and they are running. 

![image](https://github.com/user-attachments/assets/2a1592fa-c860-4224-be5d-5acfbe7bf380)

![image](https://github.com/user-attachments/assets/c41db64a-f43b-481c-8df4-757ee579e8d1)

![image](https://github.com/user-attachments/assets/10709b94-c4e1-47bf-870c-b820dce187e6)

**Comment by rwidmark** [comment]
This is strange, have the same issue with two different servers and when I'm rolling back to 4.4.0 everything works.

I'll try again later (2h from now) and replay back.

**Comment by rwidmark** [comment]
@adamdriscoll Here is a error message that I haven't posted 
```
   at UniversalAutomation.Cmdlets.NewScheduleCommand.ProcessRecord() in C:\actions-runner\_work\universal\universal\src\Cmdlets\Automation\NewScheduleCommand.cs:line 121
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

Update with one more error:
```
2024-09-09 22:53:24.580 +02:00 [WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal.Server.Pages.Automation.Schedules.<>c__DisplayClass0_0.<BuildRenderTree>b__11(RenderTreeBuilder __builder4) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Pages\Automation\Schedules.razor:line 63
   at AntDesign.Column`1.<BuildRenderTree>b__170_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by rwidmark** [comment]
@adamdriscoll I did delete schedules.ps1 and then it's OK and I can add a schedule but after I do it crashes.
![CleanShot 2024-09-09 at 23 02 43](https://github.com/user-attachments/assets/0392bf8f-44e6-4371-a605-ee5d05e00be6)

**Comment by rwidmark** [comment]
@adamdriscoll  FOUND IT!
if you specify Environment in the schedules.ps1 then you get this issue.
If I remove `Environment = "PowerShell 7"` then I don't get an issue but when I do add it I do get the issue.

This is on a clean server

This works:
```
$Parameters = @{
    Cron        = "0 * * * *"
    Script      = "Test.ps1"
    TimeZone    = "Europe/Berlin"
    Name        = "TestS"
    Timeout     = 5
    RandomDelay = $true
}
New-PSUSchedule @Parameters
```

This will not work
```
$Parameters = @{
    Cron        = "0 * * * *"
    Script      = "Test.ps1"
    TimeZone    = "Europe/Berlin"
    Environment = "PowerShell 7"
    Name        = "TestS"
    Timeout     = 5
    RandomDelay = $true
}
New-PSUSchedule @Parameters
```


And here is how the script.ps1 looks like
```
$Parameters = @{
    Name           = "Test.ps1"
    Description    = "test"
    TimeOut        = "5"
    Path           = "Test.ps1"
	Environment = "PowerShell 7"
    MaxHistory     = 10
    ConcurrentJobs = 2
    RetryLimit     = 3
}
New-PSUScript @Parameters
```

**Comment by adamdriscoll** [comment]
Nice! That's what I needed. I can reproduce this.
