### ISSUE TITLE
Powershell 7 not working after upgrade to 4.4.0

### ISSUE THREAD

**Issue by DanielMalmgren** [ironmansoftware/powershell-universal#3733]
### Version

Other Please Specify

### Severity

Medium

### Environment

msi

### Steps to Reproduce

I am trying to upgrade a PSU environment from 4.2.13 to 4.4.0, but after the upgrade my Powershell 7 environment simply refuses to do anything. For more info and discussion see [forum thread](https://forums.ironmansoftware.com/t/powershel-7-not-working-after-upgrade-to-4-4-0/11330). I have now tried with debug logging enabled. Unfortunately I can't see anything more informative in the log than "Failed to connect to terminal. Timed out.", I hope the logs say more to you. At the time stamp 15:49:03.508 in the log I tried to start a terminal using the Powershell 7 environment.

### Expected behavior

```console
Things should work like in the old version
```

### Actual behavior

```console
Nothing using the Powershell 7 environment starts. The most obvious example is starting a terminal, but this affects also API endpoints etc.
```

### Additional Environment data

PSU 4.4.0, Powershell 7.4.5, Windows Server 2019 Datacenter
[systemLog20240910_004.txt](https://github.com/user-attachments/files/16945985/systemLog20240910_004.txt)
[systemLog20240910_005.txt](https://github.com/user-attachments/files/16945986/systemLog20240910_005.txt)

**Comment by adamdriscoll** [comment]
Can you try loading the hosting DLLs manually into a pwsh process? I wonder if we have some sort of assembly conflict or something. I don't see anything too clear in the logs either. It just seems like anything (APIs or Terminals) is just failing to communicate back to the server. 

```powershell
Import-Module C:\Program Files (x86)\Universal\UniversalHost.psm1
Start-PSUHost -Id 0 -Environment 'PowerShell 7' -Type Terminal -Port 0 -ParentProcessId $PID -UniversalPort 0
```

This will either display an error or hang. Hopefully an error. :)

**Comment by DanielMalmgren** [comment]
Ok, I hope this tells you more than it tells me...

I also tried the same with the PowerShell 5 environment, though I'm not really sure what was supposed to happen :-)

```
PowerShell 7.4.5
PS C:\> Import-Module 'C:\Program Files (x86)\Universal\UniversalHost.psm1'
PS C:\> Start-PSUHost -Id 0 -Environment 'PowerShell 7' -Type Terminal -Port 0 -ParentProcessId $PID -UniversalPort 0
Received: ParentProcessId: 7648 UniversalPort: 0 InstanceId: 0
Connecting to universal.
D0917 16:11:30.006833 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Program Files (x86)\Universal\Host\grpc_csharp_ext.x64.dll"
D0917 16:11:30.039705 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
Server port:60648
Failed to start terminal. Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1726582290.306000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1726582290.306000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
PS C:\> Start-PSUHost -Id 0 -Environment 'PowerShell 5' -Type Terminal -Port 0 -ParentProcessId $PID -UniversalPort 0
Received: ParentProcessId: 7648 UniversalPort: 0 InstanceId: 0
Connecting to universal.
Server port:60682
Failed to start terminal. Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1726582463.806000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1726582463.806000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
PS C:\> 
```

**Comment by johnwhirsch** [comment]
I had these same symptoms with the following setup below until I enabled "Require Server Name Indication" on both of the IIS bindings and restarted the IIS service. I don't know if this the same issue you are having, but hope it helps.
Hosted on IIS with 2 site bindings for Port 443 on "All Unassigned" IPs:
- A record for the subdomain.domain.com, "Require Server Name Indication" checked.
- FQDN for the server servername01.domain.com, "Require Server Name Indication" **not** checked.

**Comment by DanielMalmgren** [comment]
Thanks for the  input! In this PSU environment actually there is no IIS, but I'm thinking it might be relevant anyway. Did you have multiple IIS bindings even before this? My installation only answers on one port and currently doesn't care about hostname at all... Pasting my appsettings.json below:
```
{
  "Kestrel": {
    "Endpoints": {
      "HTTPS": {
         "Url": "https://*:5464",
           "Certificate": {
             "Subject": "*.<redacted>.se",
             "Store": "My",
             "Location": "LocalMachine",
             "AllowInvalid": "false"
           }
      }
   }
},
  "Plugins": [
    "UniversalAutomation.LiteDBv5"
  ],
  "Data": {
    "RepositoryPath": "%ProgramData%\\UniversalAutomation\\Repository",
    "ConnectionString": "%ProgramData%\\UniversalAutomation\\database.db"
  }
}
```

**Comment by eizedev** [comment]
we are having the same problem.

But something even more complicated. If we run it in IIS as a standalone website with HTTPS + Binding + SSL Cert and with Wildcard as hostname it works. If our developers are running it in a development environment on different ports on same server with developer license etc., without HTTPS (only HTTP with wildcard as hostname) the identical configuration as in production does not work (anymore). We are still running on 4.4.1 and it worked before. We are starting Universal in our development environment inside visual studio code in the integrated terminal.
Universal starts but nothing configured to use the powershell 7 environment will work. We are using PowerShell 7.4.6.

If we change the environment to “Integrated”, starting apps, environments etc. works again, but of course due to the limitations of the integrated environment, other things do not. Since some of our modules like PSFramework does not work in the Integrated Environment, we cannot use the integrated environment as workaround for our apps, scripts or APIs at the moment.
So it must be related to the powershell 7 environment in my opinion.

Has anyone already found a solution from you? or @adamdriscoll 

Development Config (shortened)

```json
{
  "Kestrel": {
    "Endpoints": {
      "HTTP": {
        "Url": "http://*:5002"
      }
    },
    "RedirectToHttps": false,
    "UseHttpSys": "false",
    "Hsts": {
      "MaxAgeDays": 365
    },
    "CookiePolicy": "",
    "AddServerHeader": "true",
    "Headers": {}
  },
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "AllowedHosts": "*",
  "CorsHosts": "",
  "Plugins": [
    "UniversalAutomation.LiteDBv5"
  ],
  "SystemLogPath": "C:\\Users\\<username>\\Documents\\data\\universal\\logs\\systemLog.log",
  "SystemLogLevel": "Information",
  "Data": {
    "RepositoryPath": "C:\\Users\\<username>\\Documents\\data\\universal",
    "ConnectionString": "filename=C:\\Users\\<username>\\Documents\\data\\universal\\UniversalAutomation\\database.db;upgrade=true",
    "RunMigrations": true,
    "GitPassword": ""
  },
  "UniversalAutomation": {
    "Queues": [],
    "JobHandshakeTimeout": 30,
    "JobDebugging": false,
    "ContinueJobOnServerStop": false,
    "HangfireWorkerCount": 100
  },
  "UniversalDashboard": {
    "AssetsFolder": "C:\\Users\\<username>\\Documents\\data\\universal\\UniversalDashboard",
    "DashboardStartupTimeout": 30
  },
  "ShowDevTools": true,
  "HideAdminConsole": false,
  "Profiling": true,
  "NodeName": ""
}
```

@adamdriscoll 

```powershell
Import-Module .\universal\PowerShellUniversal\UniversalHost.psm1

Start-PSUHost -Id 0 -Environment 'PowerShell 7' -Type Terminal -Port 0 -ParentProcessId $PID -UniversalPort 0

Received: ParentProcessId: 21380 UniversalPort: 0 InstanceId: 0
Connecting to universal.
D1210 13:17:12.908990 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Host\grpc_csharp_ext.x64.dll"
D1210 13:17:12.945972 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
Server port:50472
Failed to start terminal. Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1733833033.243000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1733833033.243000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
```

Starting with an existing environment in our configuration:

```powershell
Start-PSUHost -Id 0 -Environment 'pwsh' -Type Terminal -Port 0 -ParentProcessId $PID -UniversalPort 0 
Received: ParentProcessId: 21380 UniversalPort: 0 InstanceId: 0
Connecting to universal.
Server port:50582
Failed to start terminal. Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1733833213.306000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1733833213.306000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
```

`New-PSUEnvironment -Name "pwsh" -Version "7.4.6" -Path "C:\Program Files\PowerShell\7\pwsh.exe" -Variables @('*') -RunspaceRecycling -Description "Our version of PowerShell 7."`

Changing the Kestrel config from the wildcard operator for all addresses to f.e. `"Url": "http://localhost:5002"` does not change anything.

Thanks
René

**Comment by adamdriscoll** [comment]
@eizedev - The external Kestrel\IIS configuration does not come into play when using the internal communication channel. On the backend, PSU opens a random port for the job process to communicate back to the server. We actually open a port on either end. PSU itself opens a port when it starts of backend, internal communication and then whenever a job starts, it opens a random port that is then sent back to PSU for by directional communication. 

These errors are what I would expect to see because the UniversalPort is set to 0. I was mostly wondering if it was loading all the assemblies properly, which it looks like it is. It is likely something else. 

Based on the logs posted by @DanielMalmgren, it looks like the terminal process starts but never communicates back to the server to notify that it is up and running and ready for sommands. 

Have either of you looked in event viewer to see if the pwsh.exe or powershell.exe processes are crashing? We may need to port back from of v5 agent logging we added so we can see what is actually happening in these processes. We added it just for this reason.

**Comment by DanielMalmgren** [comment]
> Have either of you looked in event viewer to see if the pwsh.exe or powershell.exe processes are crashing? We may need to port back from of v5 agent logging we added so we can see what is actually happening in these processes. We added it just for this reason.

I can't really remember, but I don't think I saw anything like that. But then again, I wasn't looking for it. I could do another test upgrade and check. Exactly where and what should I look for?

**Comment by eizedev** [comment]
@adamdriscoll 
 
At startup i can see the following message in powershell core eventlog:

`PowerShell console is ready for user input`  
`PowerShell console is ready for user input`  
`Windows PowerShell has started an IPC listening thread on process: 9192 in AppDomain: DefaultAppDomain.`  
`Windows PowerShell has started an IPC listening thread on process: 6600 in AppDomain: DefaultAppDomain`  

Then a lot of loading stuff for modules, functions etc.

And then after 11 seconds another powershell console `Windows PowerShell has started an IPC listening thread on process: 8896 in AppDomain: DefaultAppDomain.`

And after additional 30 seconds a lot of other powershell processes starting - but no errors.

But i am seeing this in the Windows PowerShell Eventlog:

Starting on random port:

```log
Engine state is changed from Available to Stopped. 
  
Details: 
        NewEngineState=Stopped
        PreviousEngineState=Available
  
        SequenceNumber=15
  
        HostName=ConsoleHost
        HostVersion=5.1.20348.2849
        HostId=dc9f35b0-84cf-4115-9ff5-87f886e947c9
        HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -Command & { Import-Module '<truncated>\universal\PowerShellUniversal\UniversalHost.psm1'; Start-PSUHost -Id 0 -Environment 'PowerShell5.1' -Type ModuleDiscovery -Port 0 -ParentProcessId 0 -UniversalPort 50646 }
        EngineVersion=5.1.20348.2849
        RunspaceId=b315e24e-497f-44b8-8805-3015d6b9c2c0
        PipelineId=
        CommandName=
        CommandType=
        ScriptName=
        CommandPath=
        CommandLine=
```

Stopping on random port (3 seconds later):

```log
Engine state is changed from Available to Stopped. 
  
Details: 
        NewEngineState=Stopped
        PreviousEngineState=Available
  
        SequenceNumber=15
  
        HostName=ConsoleHost
        HostVersion=5.1.20348.2849
        HostId=dc9f35b0-84cf-4115-9ff5-87f886e947c9
        HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -Command & { Import-Module '<truncated>\universal\PowerShellUniversal\UniversalHost.psm1'; Start-PSUHost -Id 0 -Environment 'PowerShell5.1' -Type ModuleDiscovery -Port 0 -ParentProcessId 0 -UniversalPort 50646 }
        EngineVersion=5.1.20348.2849
        RunspaceId=b315e24e-497f-44b8-8805-3015d6b9c2c0
        PipelineId=
        CommandName=
        CommandType=
        ScriptName=
        CommandPath=
        CommandLine=
```

The only errors i see are in powershell universal during startup:

```log
[15:06:51 INF] User profile is available. Using '<truncated>\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
[15:06:52 INF] RPC services being provided by PowerShellUniversal.IGitSettingsService: 4
[15:06:52 INF] RPC services being provided by UniversalAutomation.IPublicGitService: 3
[15:06:52 INF] RPC services being provided by UniversalAutomation.IPublicGitSyncService: 5
[15:06:53 INF] Now listening on: http://[::]:5002
[15:06:53 INF] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
[15:06:53 INF] Using the following options for Hangfire Server:
    Worker count: 100
    Listening queues: 'default', '<truncated>'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
[15:06:53 INF] Application started. Press Ctrl+C to shut down.
[15:06:53 INF] Hosting environment: Production
[15:06:53 INF] Content root path: <truncated>
[15:06:53 INF] Server <truncated>:5344:c6939458 successfully announced in 8,7363 ms
[15:06:53 INF] Server <truncated>:5344:c6939458 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...
[15:06:53 INF] Server <truncated>:5344:c6939458 all the dispatchers started
[15:06:53 INF] PowerShell Universal Version: 4.5.0
[15:06:53 INF] OS Version: Microsoft Windows NT 10.0.20348.0
[15:06:53 INF] OS Architecture: x64
[15:06:53 INF] Process Architecture: x64
[15:06:53 INF] Node Name: <truncated>
[15:06:53 INF] Request starting HTTP/1.1 GET http://localhost:5002/ - -
[15:06:53 INF] Executing ChallengeResult with authentication schemes ([]).
[15:06:53 INF] AuthenticationScheme: Cookies was challenged.
[15:06:53 INF] Request finished HTTP/1.1 GET http://localhost:5002/ - - - 302 0 - 468.0148ms
[15:06:53 INF] Request starting HTTP/1.1 GET http://localhost:5002/login?ReturnUrl=%2F - -
[15:06:53 INF] Request finished HTTP/1.1 GET http://localhost:5002/login?ReturnUrl=%2F - - - 200 - text/html 77.1971ms
[15:06:54 INF] PowerShell Universal performance counters do not exist.
[15:06:58 INF] Starting module discovery using Process.
[15:06:58 INF] Starting module discovery using Process.
[15:07:08 INF] Starting groom job.
....
....
[15:07:41 ERR] API process did not start in 30 seconds.
....
....
[15:08:48 INF] Error executing job 4: PowerShell did not respond in a timely fashion. PowerShell Universal is currently waiting 60 seconds for PowerShell to start running the script.
You can increase the timeout by setting the 'Job Handshake Timeout' setting in the Settings \ General \ Automation page.
If you are still experiencing issues, you may need to consider increasing the resources available on your system or take advantage of the Random Delay parameter for schedules to stagger jobs.
    at UniversalAutomation.Services.GrpcExecutionService.ExecuteScript(Job job, ExecutionEnvironment environment, ExecuteScriptRequest request, ExecutionCallback executionCallback) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\GrpcExecutionService.cs:line 113
   at UniversalAutomation.ExecutionService.ExecutePowerShell(Script script, IEnumerable`1 parameters, Job job, Schedule schedule, ExecutionCallback callback) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 730
   at UniversalAutomation.ExecutionService.TryExecute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 370
   at UniversalAutomation.ExecutionService.TryExecute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 473
   at UniversalAutomation.ExecutionService.Execute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 197 System.Exception
....
....
[15:08:49 INF] Error executing job 1: PowerShell did not respond in a timely fashion. PowerShell Universal is currently waiting 60 seconds for PowerShell to start running the script.
You can increase the timeout by setting the 'Job Handshake Timeout' setting in the Settings \ General \ Automation page.
If you are still experiencing issues, you may need to consider increasing the resources available on your system or take advantage of the Random Delay parameter for schedules to stagger jobs.
    at UniversalAutomation.Services.GrpcExecutionService.ExecuteScript(Job job, ExecutionEnvironment environment, ExecuteScriptRequest request, ExecutionCallback executionCallback) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\GrpcExecutionService.cs:line 113
   at UniversalAutomation.ExecutionService.ExecutePowerShell(Script script, IEnumerable`1 parameters, Job job, Schedule schedule, ExecutionCallback callback) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 730
   at UniversalAutomation.ExecutionService.TryExecute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 370
   at UniversalAutomation.ExecutionService.TryExecute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 473
   at UniversalAutomation.ExecutionService.Execute(Job job, Schedule schedule) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\ExecutionService.cs:line 197 System.Exception
```

**Comment by adamdriscoll** [comment]
Thanks. I don't see anything obvious from this as to why this is happening. I'm adding a new logging setting to the PSU agent process to help get more information. The `$ENV:PSUAgentLogLevel` environment variable will be added in 4.5.1 to accommodate this. You'll be able to set it to something like Information to have it generate log files that will be written to the PSU log file folder as "agent.{pid}.txt". This will capture what is happening within the agent when it fails to start so we can gather more information on how to move forward.

**Comment by eizedev** [comment]
> Thanks. I don't see anything obvious from this as to why this is happening. I'm adding a new logging setting to the PSU agent process to help get more information. The `$ENV:PSUAgentLogLevel` environment variable will be added in 4.5.1 to accommodate this. You'll be able to set it to something like Information to have it generate log files that will be written to the PSU log file folder as "agent.{pid}.txt". This will capture what is happening within the agent when it fails to start so we can gather more information on how to move forward.

ok, thanks. As soon as 4.5.1 is released, we will test it.

**Comment by DanielMalmgren** [comment]
I noticed 4.5.1 has been released, thought I'd give it a try. Any more info about where and how $ENV:PSUAgentLogLevel needs to be configured?

**Comment by adamdriscoll** [comment]
@DanielMalmgren  - You can set that environment variable in the machines environment variable settings. 

I would recommend setting PSUAgentLogLevel to Debug so we get the most information possible.

**Comment by eizedev** [comment]
@adamdriscoll 

EDIT: Solution in next comment - keeping this comment for troubleshooting

--------
--------

I have now tried to implement this with the information on the new variable. Unfortunately, there is no log file for the agent that I could access? Which Universal version is required? (i am running `4.5.1`, should i upgrade to `4.5.2`?)

I have tried setting the variable on machine level and also in another test only for this session on Process or User level.

```powershell
> $env:PSUAgentLogLevel
Debug
> [System.Environment]::GetEnvironmentVariable('PSUAgentLogLevel','Machine')
Debug
```

I have also added `"PSUAgentLogLevel": "Debug"` to the appsettings_dev.json file that i use for our dev environment.

After that i started the UniversalServer with the following commands (shortened). Content of the `PathAppConfigDev` is the same as above in one of my comments.

```powershell
$User = 'username'
$PathRoot = "C:\Users\$($user)\git"
$PathConfiguration = (Join-Path $PathRoot 'universal-dev')
$PathUniversal = (Join-Path $PathConfiguration 'universal')
$PathAppConfigDev = (Join-Path $PathUniversal 'appsettings_dev.json')
$PathUniversalLog = (Join-Path $PathUniversal 'logs')

& "$($PathUniversal)\PowerShellUniversal\Universal.Server.exe" --appsettings $PathAppConfigDev
```

After the startup, the PowerShell 7 environment will not start but i cannot find a new file named `"agent.{pid}.txt"` in the logs folder (and also not at any other place). Also no additional information will be shown in the startup log.

`"SystemLogPath": "C:\\Users\\<username>\\Documents\\data\\universal\\logs\\systemLog.log"`  
`"RepositoryPath": "C:\\Users\\<username>\\Documents\\data\\universal",`

Am I doing something wrong?

Thanks
René

P.S. i also tried setting `DontLoadProfile     = $true` in the settings.ps1, also nothing changed

**Comment by eizedev** [comment]
@adamdriscoll 

ok, i found the logfile, the variable is working. to not fully remove my troubleshooting parts from above (perhaps we will need in the future) i found the logfile in `C:\ProgramData\PowerShellUniversal`. It looks like the PSUAgentLogLevel does not respect the appsettings log folder variable, that should be changed.

the startup produces 4 logfiles with 4 PIDs, see below - do you see anything helpful?

```log
-a---          11.02.2025    16:25           1195 agent.17820.log
-a---          11.02.2025    16:25           2682 agent.4084.log
-a---          11.02.2025    16:25            980 agent.7884.log
-a---          11.02.2025    16:25           1195 agent.5224.log
```

```log
> cat agent.5224.log
2025-02-11 16:25:38.565 +01:00 [INF] Agent Logging Enabled at level: "Debug"
2025-02-11 16:25:38.576 +01:00 [INF] PSModulePath: C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Users\<username>\scoop\modules;C:\Users\<username>\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Users\<username>\Documents\data\git\automatisierung\dashboard\arc-content\Modules;
2025-02-11 16:25:38.578 +01:00 [INF] Process: pwsh
2025-02-11 16:25:38.594 +01:00 [INF] OnAssemblyResolve: Xamarin.iOS, Culture=neutral, PublicKeyToken=null
2025-02-11 16:25:38.595 +01:00 [INF] OnAssemblyResolve: Mono.Android, Culture=neutral, PublicKeyToken=null

> cat agent.7884.log
2025-02-11 16:25:28.429 +01:00 [INF] Agent Logging Enabled at level: "Debug"
2025-02-11 16:25:28.441 +01:00 [INF] PSModulePath: C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Users\<username>\scoop\modules;C:\Users\<username>\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Users\<username>\Documents\data\git\automatisierung\dashboard\arc-content\Modules;
2025-02-11 16:25:28.442 +01:00 [INF] Process: pwsh

> cat agent.4084.log
2025-02-11 16:25:27.372 +01:00 [INF] Agent Logging Enabled at level: "Debug"
2025-02-11 16:25:27.374 +01:00 [INF] PSModulePath: C:\Users\<username>\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Users\<username>\scoop\modules;C:\Users\<username>\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;;;
2025-02-11 16:25:27.380 +01:00 [INF] Process: powershell
2025-02-11 16:25:27.431 +01:00 [INF] OnAssemblyResolve: Xamarin.iOS
2025-02-11 16:25:27.431 +01:00 [INF] OnAssemblyResolve: Xamarin.iOS
2025-02-11 16:25:27.436 +01:00 [INF] OnAssemblyResolve: Mono.Android
2025-02-11 16:25:27.436 +01:00 [INF] OnAssemblyResolve: Mono.Android
2025-02-11 16:25:28.195 +01:00 [INF] OnAssemblyResolve: System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2025-02-11 16:25:28.195 +01:00 [INF] Loading assembly C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Host\System.Runtime.CompilerServices.Unsafe.dll
2025-02-11 16:25:28.288 +01:00 [INF] OnAssemblyResolve: System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2025-02-11 16:25:28.288 +01:00 [INF] OnAssemblyResolve: System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2025-02-11 16:25:28.358 +01:00 [INF] OnAssemblyResolve: System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2025-02-11 16:25:28.358 +01:00 [INF] OnAssemblyResolve: System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2025-02-11 16:25:28.396 +01:00 [INF] OnAssemblyResolve: System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
2025-02-11 16:25:28.396 +01:00 [INF] OnAssemblyResolve: System.Management.Automation.resources, Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35

> cat agent.17820.log
2025-02-11 16:25:27.304 +01:00 [INF] Agent Logging Enabled at level: "Debug"
2025-02-11 16:25:27.315 +01:00 [INF] PSModulePath: C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Modules;C:\Users\<username>\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Users\<username>\scoop\modules;C:\Users\<username>\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Users\<username>\Documents\data\git\automatisierung\dashboard\arc-content\Modules;
2025-02-11 16:25:27.317 +01:00 [INF] Process: pwsh
2025-02-11 16:25:27.340 +01:00 [INF] OnAssemblyResolve: Xamarin.iOS, Culture=neutral, PublicKeyToken=null
2025-02-11 16:25:27.340 +01:00 [INF] OnAssemblyResolve: Mono.Android, Culture=neutral, PublicKeyToken=null
```

Information of the processes:

```powershell
> get-process -PID 17820 |select id, PRocessName, CommandLine |fl      
Get-Process: Cannot find a process with the process identifier 17820.

> get-process -PID 4084 |select id, PRocessName, CommandLine |fl        

Id          : 4084
ProcessName : svchost
CommandLine : 

> get-process -PID 7884 |select id, PRocessName, CommandLine |fl

Id          : 7884
ProcessName : pwsh
CommandLine : "C:\Program Files\PowerShell\7\pwsh.exe"    -NoProfile -Command "& { Import-Module 'C:\Users\<username>\Documents\data\universal\PowerShellUniversal\UniversalHost.psm1'; Start-PSUHost -Id 54831 -Environment     'pwsh' -Type Security -Port 54831 -ParentProcessId 16304 -UniversalPort 54830 }"

> get-process -PID 5224 |select id, PRocessName, CommandLine |fl

Id          : 5224
ProcessName : pwsh
CommandLine : "C:\Program Files\PowerShell\7\pwsh.exe"   -NonInteractive -NoProfile -Command "& { Import-Module 'C:\Users\<username>\Documents\data\universal\PowerShellUniversal\UniversalHost.psm1'; Start-PSUHost -Id 54845 -Environment 'pwsh' -Type Api -Port 54845 -ParentProcessId 16304 -UniversalPort 54830 }"

```

and the parent process

```powershell
get-process -PID 16304 |select id, PRocessName, CommandLine |fl

Id          : 16304
ProcessName : Universal.Server
CommandLine : "C:\Users\<username>\Documents\data\universal\PowerShellUniversal\Universal.Server.exe" --appsettings C:\Users\<username>\Documents\data\universal\appsettings_dev.json
```

**Comment by eizedev** [comment]
@adamdriscoll any news on this topic? Thanks

**Comment by DanielMalmgren** [comment]
Also wondering... I haven't done any more update trials since I don't think I can get any more info out than @eizedev already has. Or is there any more info that could provide?

**Comment by DanielMalmgren** [comment]
Bumping this again, I would really love to be able to upgrade my PSU environments higher than 4.2. @adamdriscoll any ideas what is happening?

**Comment by DanielMalmgren** [comment]
We are currently doing a market analyzis of integration platforms, considering changing platform and move all our (200+) integrations from PSU somewhere else, the heaviest argument being that we are on an old version that we actually can't upgrade any more. So I'm sorry to say, but either this bug needs to be solved quite soon or it won't matter any more for us.
