### ISSUE TITLE
Tokens - Copy button throws error `Could not find 'copyToClipboard'

### ISSUE THREAD

**Issue by jpomfret** [ironmansoftware/powershell-universal#3811]
### Version

5.0.6

### Severity

Medium

### Environment

msi

### Steps to Reproduce

> [!IMPORTANT]
> I'm on version 5.0.7 but that isn't an option in the drop down!

1. go to tokens page, e.g. http://localhost:5000/admin/security/tokens
2. press the copy button on an existing token (this doesn't matter if it's a token created in an older version, or a new token)
![image](https://github.com/user-attachments/assets/761877e6-c117-43ca-95b4-3113e4045bec)

### Expected behavior

```console
Token is copied into clipboard
```

### Actual behavior

Error occurs:
![image](https://github.com/user-attachments/assets/d97178b8-eb87-4143-85d5-c81cfa5c9d08)

Error text for easy searching:
```
An error occured. Could not find 'copyToClipboard' ('copyToClipboard' was undefined). Error: Could not find 'copyToClipboard' ('copyToClipboard' was undefined). at http://localhost:5000/_framework/blazor.server.js:1:537 at Array.forEach (<anonymous>) at l.findFunction (http://localhost:5000/_framework/blazor.server.js:1:505) at _ (http://localhost:5000/_framework/blazor.server.js:1:5248) at http://localhost:5000/_framework/blazor.server.js:1:3041 at new Promise (<anonymous>) at y.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.server.js:1:3004) at Xt._invokeClientMethod (http://localhost:5000/_framework/blazor.server.js:1:60890) at Xt._processIncomingData (http://localhost:5000/_framework/blazor.server.js:1:58279) at Xt.connection.onreceive (http://localhost:5000/_framework/blazor.server.js:1:51920)
at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) at PowerShellUniversal.AppTokenTable.CopyToken(AppToken token) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Security\AppTokenTable.razor:line 66 at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at AntDesign.Button.HandleOnClick(MouseEventArgs args) at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Additional Environment data

5.0.7

**Comment by adamdriscoll** [comment]
Thanks for the report. I thought we had this fixed, but I guess it's still a problem. It's a Chromium security setting that prevents this JS API from being called on non-HTTPS sites. We have a workaround in place but it's still trying to call the missing API for some reason.
