### ISSUE TITLE
Unsupported URL when setting up Git over SSH

### ISSUE THREAD

**Issue by Daniel0023** [ironmansoftware/powershell-universal#3925]
### Version

5.0.10

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Have created SSH keys and added them to my agent and repository following the guide here:
https://docs.powershelluniversal.com/config/git#example-ssh-and-github:~:text=Example%3A%20SSH%20and%20GitHub

Then after I insert branch and SSH remote URL into Git Settings and it report no errors. When I then do a commit it failed with returning "unsupported URL protocol"

### Expected behavior

```console
Able to commit to Git repository
```

### Actual behavior

```console
Failing to commit to Git repository. PSU is returning with "unsupported URL protocol"
```

### Screenshots/Animations

2024-10-17 08:33:30.100 +02:00 [INF][Microsoft.AspNetCore.Routing.EndpointMiddleware] Executing endpoint '/_blazor'
2024-10-17 08:33:34.915 +02:00 [WRN][Microsoft.AspNetCore.Components.Web.ErrorBoundary] Unhandled exception rendering component: unsupported URL protocol
LibGit2Sharp.LibGit2SharpException: unsupported URL protocol
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_remote_push(RemoteHandle remote, IEnumerable`1 refSpecs, GitPushOptions opts) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2246
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Network.cs:line 373
   at LibGit2Sharp.Network.Push(Remote remote, String pushRefSpec, PushOptions pushOptions) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Network.cs:line 332
   at LibGit2Sharp.Network.Push(IEnumerable`1 branches, PushOptions pushOptions) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Network.cs:line 256
   at LibGit2Sharp.Network.Push(Branch branch, PushOptions pushOptions) in C:\actions-runner\_work\universal\universal\src\libgit2sharp\LibGit2Sharp\Network.cs:line 217
   at UniversalAutomation.Git.GitService.Push() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitService.cs:line 658
   at UniversalAutomation.GitSyncService.CompleteEditing(GitCommit gitCommit) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 412
   at Universal.Server.Pages.Settings.GitCommitAdminPage.Commit() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Pages\Settings\GitCommitAdminPage.razor:line 164
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by adamdriscoll** [comment]
If you haven't done it, you will need to make sure to use the External Git Client setting. It looks like this is trying to use the integrated client which does not support SSH.

**Comment by adamdriscoll** [comment]
Closing as this requires external git client and not the built in client.
