### ISSUE TITLE
Git fails to sync - Too many redirects

### ISSUE THREAD

**Issue by serpentx** [ironmansoftware/powershell-universal#3934]
### Version

5.0.12

### Severity

Low

### Environment

msi

### Steps to Reproduce

When git synchronization is triggered, manually or automatically, a notification is posted with title "Git Synchronization Failed", description "Too many redirects or authentication replays". This actually began right after I installed 5.0.11 and is still a problem in 5.0.12. I have verified that the credentials used are valid

### Expected behavior

```console
Synchronization with our Azure DevOps server
```

### Actual behavior

```console
2024-10-16 11:07:05.526 -07:00 [ERR][UniversalAutomation.GitSyncService] Failed to sync: too many redirects or authentication replays    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage) in /_/LibGit2Sharp/Core/Proxy.cs:line 2289
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in /_/LibGit2Sharp/Commands/Fetch.cs:line 79
   at LibGit2Sharp.Commands.Pull(Repository repository, Signature merger, PullOptions options) in /_/LibGit2Sharp/Commands/Pull.cs:line 36
   at UniversalAutomation.Git.GitService.Pull() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitService.cs:line 713
   at UniversalAutomation.GitSyncService.TrySync(GitStatus status, Boolean force, GitSettings settings) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 194
   at UniversalAutomation.GitSyncService.Sync(Boolean force, Boolean throwOnFailure) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 95
```

### Additional Environment data

Running on a Windows 2022 VM, no IIS

**Comment by serpentx** [comment]
I tried the external Git client, and it seems to work fine
