### ISSUE TITLE
Invalid configuration: environments.ps1

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3956]
### Version

5.0.13

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

setup psu
recycle the app pool

In the environments.ps1 file that doesn't exist, with the cmdlet that i didn't call, i didn't specify a value for the parameter that doesn't exist. :P

i cannot reproduce this on demand :(

### Expected behavior

```console
no error
```

### Actual behavior

```console
at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Universal.Server.Services.ApiService.GetOrCreateProxy(Endpoint endpoint) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\API\ApiService.cs:line 158
   at Universal.Server.Services.ApiService.RemoveEndpointAsync(Endpoint endpoint) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\API\ApiService.cs:line 289
   at UniversalAutomation.Services.EndpointService.UpdateAsync(ModelOperationContext`1 context) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Endpoints.cs:line 265
   at UniversalAutomation.Services.EnvironmentConfigService.RemoveEnvironment[T](ModelOperationContext`1 context) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Environments.cs:line 163
   at UniversalAutomation.Services.EnvironmentConfigService.DeleteAsync(ModelOperationContext`1 context) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Environments.cs:line 144
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(SyncContext syncContext) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal\ConfigurationScript.cs:line 371
```

### Screenshots/Animations
![image](https://github.com/user-attachments/assets/3ecf3ce7-8fcd-4345-91bc-7e45daeab608)

**Comment by Omzig** [comment]
i was able to trigger:

Click edit for git, then click save, there is nothing to save
click cancel edit
it spins then u start getting notifications. 
![image](https://github.com/user-attachments/assets/5bef7771-d0c6-43f0-826b-2b5a98da9630)
![image](https://github.com/user-attachments/assets/ea40498c-ddb4-4e7b-9d16-4d6c8f19cb9b)

**Comment by Omzig** [comment]
i think this is related:


2024-10-24 11:46:16.882 -05:00 [ERR][PowerShellUniversal.GitEditButton] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.GitEditButton.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Settings\GitEditButton.razor:line 49
   at PowerShellUniversal.GitEditButton.<OnInitialized>b__13_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Settings\GitEditButton.razor:line 81

**Comment by Omzig** [comment]
and another one:

2024-10-24 12:19:32.622 -05:00 [ERR][PowerShellUniversal.NotificationsBadge] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.Extensibility.EFTable`2.Any(Expression`1 predicate) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 507
   at PowerShellUniversal.NotificationsBadge.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 53
   at PowerShellUniversal.NotificationsBadge.<OnAfterRender>b__4_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 33
2024-10-24 12:19:32.622 -05:00 [ERR][PowerShellUniversal.NotificationsBadge] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.Extensibility.EFTable`2.Any(Expression`1 predicate) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 507
   at PowerShellUniversal.NotificationsBadge.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 53
   at PowerShellUniversal.NotificationsBadge.<OnAfterRender>b__4_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 33

**Comment by JessePeden** [comment]
> i was able to trigger:
> 
> Click edit for git, then click save, there is nothing to save click cancel edit it spins then u start getting notifications. ![image](https://private-user-images.githubusercontent.com/1987296/379861928-5bef7771-d0c6-43f0-826b-2b5a98da9630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjA3MTQsIm5iZiI6MTcyOTg2MDQxNCwicGF0aCI6Ii8xOTg3Mjk2LzM3OTg2MTkyOC01YmVmNzc3MS1kMGM2LTQzZjAtODI2Yi0yYjVhOThkYTk2MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMTI0NjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIxYzRmMzhmMjc0NDY4NTdhYmUwYmZmYmMzYjRkZjJjN2UzZTQyY2JmZWM0M2U1YmM3YWExMTdlZDcxMzMyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nPxOms4sRmrIpzhTeJDsBOjzbDiYLeAq2JWFZgMu3l4) ![image](https://private-user-images.githubusercontent.com/1987296/379861962-ea40498c-ddb4-4e7b-9d16-4d6c8f19cb9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjA3MTQsIm5iZiI6MTcyOTg2MDQxNCwicGF0aCI6Ii8xOTg3Mjk2LzM3OTg2MTk2Mi1lYTQwNDk4Yy1kZGI0LTRlN2ItOWQxNi00ZDZjOGYxOWNiOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMTI0NjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU0MDI1Y2Q1N2VjOWNmYTM2YTk5ZmUyNDE1YmEzYjBmMzFlNGYzYTU4NzE5YjUwYThmZDE2ZjFmYzNhNGYyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oMxj9Jzxd__Fjj5ftoac4hsUe9W_bdUe3CjCW4LSW5s)

How do you get that Configuration Error button?

**Comment by Omzig** [comment]
> How do you get that Configuration Error button?

when you have an error it shows up on your tool bar at the top next to the light/dark switch

**Comment by JessePeden** [comment]
> > How do you get that Configuration Error button?
> 
> 
> 
> when you have an error it shows up on your tool bar at the top next to the light/dark switch

I'll check for it next time but I've never seen (or noticed) it in my instance when I've had configuration errors.
