### ISSUE TITLE
Certificate Error with LibGit2Sharp

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#4008]
### Description of Issue

If a certificate isn't trusted but the user wants to be able to use the git instance (GitLab in this case), then we need a way to allow the git library to trust the certificate. 

```
2024-10-31 15:04:16.087 -05:00 [ERR][UniversalAutomation.GitSyncService] Failed to sync: unknown certificate lookup failure: 16777280    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage) in /_/LibGit2Sharp/Core/Proxy.cs:line 2289
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in /_/LibGit2Sharp/Commands/Fetch.cs:line 79
   at LibGit2Sharp.Commands.Pull(Repository repository, Signature merger, PullOptions options) in /_/LibGit2Sharp/Commands/Pull.cs:line 36
   at UniversalAutomation.Git.GitService.Pull() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitService.cs:line 731
   at UniversalAutomation.GitSyncService.TrySync(GitStatus status, Boolean force, GitSettings settings) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 194
   at UniversalAutomation.GitSyncService.Sync(Boolean force, Boolean throwOnFailure) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Git\GitSyncService.cs:line 95
```

### Version

5.0.14

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Features

Git sync

**Comment by adamdriscoll** [comment]
This appears to be an error with the libgit2sharp library: https://github.com/libgit2/libgit2sharp/issues/2106
