### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#4018]
### Description of Issue

after running happily for a couple of hours , my PSUv5 test server starts logging below (once a second)
restarting the service fixes it for a while till it happens again

### Version

5.0.15 (11638100905)

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Additional Environment data

win 2019

### Screenshots/Animations

```
2024-11-03 10:30:24.356 +00:00 [ERR][PowerShellUniversal.Shared.ScriptOutput] An error occurred while loading the log.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.Extensibility.EFTable`2.WhereAsync(Expression`1 predicate) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 570
   at PowerShellUniversal.Shared.ScriptOutput.LoadData() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Automation\ScriptOutput.razor:line 44
   at PowerShellUniversal.Shared.ScriptOutput.<Callback>b__27_0() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Automation\ScriptOutput.razor:line 91
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at PowerShellUniversal.Shared.ScriptOutput.Callback(Object stateInfo) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Automation\ScriptOutput.razor:line 89

```

**Comment by bt-ndollimount** [comment]
I believe I've seen this in the logs on my Linux instance as well.

**Comment by alexrgreenwood** [comment]
i have some more instances of similar - is this the same issue that is fixed or do they need to be handled separately ?


```
2024-11-05 10:12:57.055 +00:00 [ERR][PowerShellUniversal.GitEditButton] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.GitEditButton.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Settings\GitEditButton.razor:line 49
   at PowerShellUniversal.GitEditButton.<OnInitialized>b__13_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Settings\GitEditButton.razor:line 81
2024-11-05 10:12:57.055 +00:00 [ERR][PowerShellUniversal.NotificationsBadge] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.Extensibility.EFTable`2.Any(Expression`1 predicate) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 507
   at PowerShellUniversal.NotificationsBadge.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 53
   at PowerShellUniversal.NotificationsBadge.<OnAfterRender>b__4_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 33
2024-11-05 10:12:57.055 +00:00 [ERR][Universal.Server.Pages.Automation.JobPage] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.Extensibility.EFTable`2.Include[K](Expression`1 dbref) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 595
   at Universal.Server.Pages.Automation.JobPage.<OnAfterRender>b__18_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Pages\Automation\JobPage.razor:line 177
2024-11-05 10:12:57.055 +00:00 [ERR][PowerShellUniversal.NotificationsBadge] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.Extensibility.EFTable`2.Any(Expression`1 predicate) in C:\actions-runner\_work\universal\universal\src\PowerShellUniversal.Extensibility\Persistence\EFTable.cs:line 507
   at PowerShellUniversal.NotificationsBadge.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 53
   at PowerShellUniversal.NotificationsBadge.<OnAfterRender>b__4_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Header\NotificationsBadge.razor:line 33
2024-11-05 10:12:57.056 +00:00 [ERR][PowerShellUniversal.GitEditButton] An error occurred while loading the status.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at PowerShellUniversal.GitEditButton.Load() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Settings\GitEditButton.razor:line 49
   at PowerShellUniversal.GitEditButton.<OnInitialized>b__13_1() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\Settings\GitEditButton.razor:line 81


```
