### ISSUE TITLE
EventHub reconnect still does not work in 4.5

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#4126]
### Description of Issue

Restarted the PSU service after upgrading both PSU instance and event hub service and reconnect did not occur. Logs show disconnect but not reconnect. 

### Version

4.5 Release

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Additional Environment data

Windows Server 2022, SQL Server 2022

**Comment by adamdriscoll** [comment]
Strange. It looks like we can configure some internal SignalR logging to get a better picker of why the retry policy didn't kick in. It should retry indefinitely, every 30 seconds.

**Comment by adamdriscoll** [comment]
I actually was able to reproduce this. If the hub tries to reconnect while the PSU server is running but not fully configured, it can cause the hub to fail and stop reconnecting. 

```
[08:44:43 ERR] Connection is shutting down due to an error.
Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: Connection closed with an error. Exception: Event Hub not found.
[08:44:43 VRB] The HubConnection is attempting to transition from the Connected state to the Disconnected state.
[08:44:43 VRB] Releasing Connection Lock in HandleConnectionClose (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:1548).
[08:44:43 DBG] Invoking the Closed event handler.
[08:44:43 WRN] Connection to server http://localhost:5000 at hub Hub closed. Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: Connection closed with an error. Exception: Event Hub not found.
```

As you can see, I also got the SignalR logging working, so we'll have way better insight into the connection status. 

```
en cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReconnectAsync(Exception closeException)
[08:44:12 VRB] Releasing Connection Lock in ReconnectAsync (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:1682).
[08:44:12 VRB] Reconnect attempt number 2 will start in 00:00:30.
[08:44:42 VRB] Waiting on Connection Lock in ReconnectAsync (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:1647).
[08:44:42 DBG] Starting HubConnection.
[08:44:42 DBG] Starting HttpConnection.
```
