### ISSUE TITLE
Code Editor for Apps throws error

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#4131]
### Description of Issue

https://forums.ironmansoftware.com/t/powershell-universal-5-1-0/11835/15?u=adam

### Version

5.1.0

### Severity

Critical

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

No

**Comment by adamdriscoll** [comment]
This I also cannot reproduce. I've tried on a few different instances without issue. Still trying to track it down. The error from the forums may not be the direct issue. It could be a side effect of something else. 

```
An error occured. Cannot access a disposed object. Object name: ‘Microsoft.JSInterop.DotNetObjectReference`1[[BlazorMonaco.Editor.Editor, BlazorMonaco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null]]’.

at Microsoft.JSInterop.DotNetObjectReference1.get_Value() at BlazorMonaco.Editor.Global.Create(IJSRuntime jsRuntime, String domElementId, StandaloneEditorConstructionOptions options, EditorOverrideServices overrideServices, DotNetObjectReference1 dotnetObjectRef) at BlazorMonaco.Editor.StandaloneCodeEditor.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by trackd** [comment]
i'm seeing this issue as well, when trying to edit an API.

```ps1
An error occured. Cannot access a disposed object. Object name: 'Microsoft.JSInterop.DotNetObjectReference`1[[BlazorMonaco.Editor.Editor, BlazorMonaco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null]]'.
at Microsoft.JSInterop.DotNetObjectReference`1.get_Value() at BlazorMonaco.Editor.Global.Create(IJSRuntime jsRuntime, String domElementId, StandaloneEditorConstructionOptions options, EditorOverrideServices overrideServices, DotNetObjectReference`1 dotnetObjectRef) at BlazorMonaco.Editor.StandaloneCodeEditor.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

this is running 5.1.0 on a Windows Server 2022 with an SQL database.

the editor seems to load fine when i browse through Settings -> Files.
Also works fine when opening from Scripts

It seems limited to Apps and API

**Comment by adamdriscoll** [comment]
I believe this is a side effect of https://github.com/ironmansoftware/powershell-universal/issues/4129. Both apps and APIs have a log tab that contains the log viewer control. 

I haven't run into this issue with 5.1.1 at all with the app or API editor. That said, I never actually saw the issue with 5.1.0 but was able to reproduce the issue with the log viewer.
