### ISSUE TITLE
4.5.0 - High Availability (2 Nodes) w/ Load Balancer

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#4166]
### Description of Issue

Hitting F5 Load Balancer (https://psu.ourdomain.com/) between Two Servers (Server01 & Server02) with a DFS Share between the two servers for repository. 

Server01 is showing the dashboard as Starting and Server02 is showing running. 
I did open a ticket. Not sure why the inconsistency between the dashboards in HA. 

I plan on opening a feature request to be able to monitor dashboard status between hosts for instances like ours that it is load balanced. 

### Version

4.5.0

### Severity

High

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Features

ADFS SSO

### Additional Environment data

Windows Server 2022

**Comment by mwatts-seg** [comment]
@adamdriscoll - Not sure if this is related or should I open a new issue? 
A script I created and scheduled is unable to execute: 

Error executing job: Unknown script: Retail\Citrix\Admin\CitrixRebootApplicationServers.ps1

The script is on a DFS Share between the two servers and I am able to see it on both nodes, but it refuses to launch it via Schedule.

![image](https://github.com/user-attachments/assets/f9506269-3419-47dc-8b48-8db17c4fffca)

**Comment by adamdriscoll** [comment]
Is this a new issue with 4.5? I know you've been using DFS for a while and I'm wondering if it stopped working at some point.

**Comment by mwatts-seg** [comment]
> Is this a new issue with 4.5? I know you've been using DFS for a while and I'm wondering if it stopped working at some point.

This does seem new. We've been running other jobs without any issues, but this particular one was created on 4.5 (or 4.4.1?). I logged into each node directly (not through the load balancer URL), and both nodes can see the scripts. 

The strange part is that it feels like the nodes aren’t aware of each other. They show up in "Computers," but some users were getting a "Dashboard not running" message. I opened a ticket and started digging and I found one of the nodes stuck in Starting.

On another note, I’ve noticed in the past that if I made a change to the dashboard, some users wouldn’t see the update right away. I always assumed it was just a caching issue, but now I’m wondering if that could’ve been a symptom of this problem.

I also found a bunch of failures in Hangfire, but they’re from two years ago.

![image](https://github.com/user-attachments/assets/791a7a22-50d2-45aa-8eec-b552b10670bf)
 
![image](https://github.com/user-attachments/assets/bc072c07-eaf5-4324-820f-0020261fda77)


On a side note, we’re planning to move our dashboards and scripts to Azure DevOps in the future, and we’ve started testing 5.X with it.

**Comment by adamdriscoll** [comment]
The fact that you are getting timeout errors in hangfire sometimes can be related to really large tables in the DB that aren't being cleaned up properly. Can you check the Hangfire.Job table? Usually, I see this with a large number of enqueued jobs so I'm not sure that is the case here. 

In terms of the script missing, it looks like it picked up the schedule but not the fact that the script exists. If you look in the scripts page, is it there? It sounds like it's on disk and not in the in-memory scripts table.

**Comment by mwatts-seg** [comment]
> The fact that you are getting timeout errors in hangfire sometimes can be related to really large tables in the DB that aren't being cleaned up properly. Can you check the Hangfire.Job table? Usually, I see this with a large number of enqueued jobs so I'm not sure that is the case here.
> 
> In terms of the script missing, it looks like it picked up the schedule but not the fact that the script exists. If you look in the scripts page, is it there? It sounds like it's on disk and not in the in-memory scripts table.

The Hangfire.Job table is pretty huge:
![image](https://github.com/user-attachments/assets/c28fbfe2-c042-4751-9d27-942368a215e2)


Yep, I can see the script on both servers browsing through file explorer or through the UI. I am not sure what happen. While I am tempting to upgrade to v5, this is our production system that our help desk heavily uses. I am not sure if everything would fire up without heavy modifications.

**Comment by adamdriscoll** [comment]
Notes for myself from our call today: 

- Changes from one node are not detected on the other node
- Upgrade was from 4.3.4 to 4.4.0, 4.4.1 to 4.5.0 and the issue started somewhere in there
- Manually refreshing the configuration on the node that failed to pick up the changes successfully picks up the changes 

Recommendations for now: 

- Edit on one node, and once complete, manually sync the configuration on the second node

**Comment by adamdriscoll** [comment]
After reviewing your logs, I'm seeing the file system watcher throw an exception. It's checking to see if it should reload the dashboards but is throwing. This actually affects all configuration reloads since it could be a different file it's checking. 

I will put a check in to avoid this issue. That said, it appears that one of the apps in your environment is return $null for it's FilePath. Can you check dashboards.ps1 to see if all the dashboards have paths? 

```
2024-12-19 19:33:39.149 -05:00 [WRN] Failed to sync
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.ArgumentNullException.Throw(String paramName)
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at UniversalAutomation.Services.DashboardsConfigurationScript.ShouldRead(String relativePath) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Configuration\Dashboards.cs:line 25
   at UniversalAutomation.Services.UniversalConfigurationService.<>c__DisplayClass22_0.<ProcessNotificationQueue>b__0(IConfigurationScript m) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\UniversalConfigurationService.cs:line 181
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at UniversalAutomation.Services.UniversalConfigurationService.ProcessNotificationQueue() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\UniversalConfigurationService.cs:line 200
```

**Comment by adamdriscoll** [comment]
Going to mark this as resolved for 4.5.1 because I believe this is root cause.  4.5.1 will be released next Tuesday. If you are still experiencing this issue then, we will have to investigate further.
