### ISSUE TITLE
Improve Git Sync

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#428]
Git sync is hard to get right. It fails pretty easily until it's running. It should be able to be configured in the UI.

**Comment by alexrgreenwood** [comment]
Hi Adam - in v3.0.3 i cant get the git sync to work (with the same settings i used just fine on prod 2.10.3 - it will partially sync but logs the failures below - can you help me understand what is null that shouldnt be ?



```

2022-06-21 21:47:04.677 +01:00 [ERR] Failed to sync: Value cannot be null. (Parameter 'objectish')    at LibGit2Sharp.Core.Ensure.ArgumentNotNullOrEmptyString(String argumentValue, String argumentName) in /_/LibGit2Sharp/Core/Ensure.cs:line 54
   at LibGit2Sharp.Repository.Lookup(String objectish, GitObjectType type, LookUpOptions lookUpOptions) in /_/LibGit2Sharp/Repository.cs:line 636
   at LibGit2Sharp.RepositoryExtensions.Lookup[T](IRepository repository, String objectish) in /_/LibGit2Sharp/RepositoryExtensions.cs:line 32
   at UniversalAutomation.Git.GitService.GetChangesSinceCommit(String sha)+MoveNext() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\GitService.cs:line 384
   at UniversalAutomation.GitSyncService.TrySync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\GitSyncService.cs:line 203
   at UniversalAutomation.GitSyncService.Sync() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\GitSyncService.cs:line 94


```

**Comment by adamdriscoll** [comment]
@alexrgreenwood - I'm not quite sure and will have to open another issue to take a look at this.

**Comment by adamdriscoll** [comment]
@alexrgreenwood - I can't reproduce this at the moment. Can you do me a favor and set your log level to debug? I'm specifically looking for this log message: 

```
_logger.LogDebug("Getting changes since {0}", lastSync.CommitId);
```

I want to make sure the CommitId is not null.

**Comment by adamdriscoll** [comment]
Git sync can now be configured in the UI and the settings are stored in the database rather than appsettings.json. You can still use appsettings.json if you are desire or have it configured already. We have also add options to synchronize immediately (for testing) and the ability to change how frequently git syncs happen to avoid issues with services like Bitbucket locking app tokens if they ping the server to often.
