### ISSUE TITLE
Universal Automation 1.3.2 when MSI-installed does not work on Windows Server 2019

### ISSUE THREAD

**Issue by jantari** [ironmansoftware/powershell-universal#52]
#### Description

When installing Universal Automation 1.3.2 from the MSI-installer on a Windows Server 2019 machine,
the service starts up but the Web-UI is inaccessible and the log files are spammed with the error below.

#### Additional Information

The error message is:

```plain
2020-09-21T06:29:07.7106706-07:00  [WRN] Connection processing ended abnormally. (21e125cb)
System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases' threw an exception.
 ---> System.IO.FileNotFoundException:
File name: 'Microsoft.AspNetCore.WebUtilities, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases.CreateStatusBytes(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases..cctor()


   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.ReasonPhrases.ToStatusBytes(Int32 statusCode, String reasonPhrase)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.WriteResponseHeadersInternal(BufferWriter`1& writer, Int32 statusCode, String reasonPhrase, HttpResponseHeaders responseHeaders, Boolean autoChunk)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.WriteResponseHeaders(Int32 statusCode, String reasonPhrase, HttpResponseHeaders responseHeaders, Boolean autoChunk, Boolean appComplete)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceEnd()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
2020-09-21T06:29:07.7154103-07:00 0HM2U68EFBVE5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5005/   (ca22a1cb)
2020-09-21T06:29:07.7187314-07:00 0HM2U68EFBVE5:00000001 [ERR] Connection id ""0HM2U68EFBVE5"", Request id ""0HM2U68EFBVE5:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.IO.FileNotFoundException:
File name: 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I had to change the port to 5005, as 5000 is already used on nearly all our machines but other than that didn't change anything.
It appears there are .NET Core assemblies missing, but this is not documented in the System Requirements: https://docs.ironmansoftware.com/system-requirements#windows

.NET Framework 4.7.2 is already installed, in fact .NET 4.8 is, and trying to install 4.7.2 again yields the error:

```plain
.NET Framework 4.7.2 or a later update is already installed on this computer.
```

Universal Automation 1.3.2 starts up without problems when running from the .ZIP download.

#### Version Information

- Universal: 1.3.2
- Universal Hosting Method (IIS, Executable, docker etc): Executable
- PowerShell: 5.1 and 7.0.3
- Operating System: Windows Server 2019 (Build 10.0.17763.1457)

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
We do all our integration testing on Core now so whatever issue this was has since been resolved.
