### ISSUE TITLE
All Authentication Broken when ClientCertificate is Enabled (2.5.2/2.5.3)

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#699]
### Steps to Reproduce

Access PSU via Web User Agent

### Expected behavior

```console
Perform OIDC authentication and return to PSU Admin Console.
```

### Actual behavior

HTTP Error 500

Log Output:
```console
[ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Universal.Server.Middleware.RoutingMiddleware.Invoke(HttpContext httpContext, IPolicyEvaluator policyEvaluator) in D:\a\universal\universal\src\Universal.Server\Middleware\RoutingMiddleware.cs:line 115
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Universal.Server.Middleware.SwaggerAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\a\universal\universal\src\Universal.Server\Middleware\SwaggerAuthMiddleware.cs:line 42
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in D:\a\universal\universal\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 109
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Environment data

PowerShell Universal 2.5.2
Windows Server 2019

**Comment by Viajaz** [comment]
You cannot have a route with `[Authorize]` attribute that doesn't specify Authentication Scheme when you haven't specified a default Authentication Scheme.

**Comment by adamdriscoll** [comment]
The problem is with authentication.ps1. It's likely failing to produce any valid authentication providers so none are registered. This is happening because the PS1 serializer we use is adding some parameters that dont match the default parameter sets. 

You can resolve this by remove the -SaveTokens, -UseTokenLifeTime and, GetClaimsFormUserInforEndpoint parameters from Set-PSUAuthenticationMethod calls. 

Looks like we will need to do a 2.5.3 release because this causes issues when you add new auth methods in the admin console. 

The second issue is that once this happens PSU is effectively broken. We have another issue tracking this. If authentication.ps1 fails, you should still be able to login somehow.

**Comment by Viajaz** [comment]
@adamdriscoll Issue also occurs when `authentication.ps1` is blank or has basic method:

```powershell
Set-PSUAuthenticationMethod -ScriptBlock {
    Param(
        [PSCredential]$Credential
    )
    New-PSUAuthenticationResult -Success -UserName $Credential.UserName
}
```
-but I think you refer to that part of the software as that and not necessarily only referring to the configuration PowerShell script file?

**Comment by Viajaz** [comment]
@adamdriscoll Problem still exists with PSU 2.5.3

**Comment by Viajaz** [comment]
@adamdriscoll Issue disappears when `Authentication.ClientCertificate.Enabled` in `appsettings.json` is `false`.

**Comment by Viajaz** [comment]
@adamdriscoll Something similar still occurs with API Endpoints.

When `Authentication.ClientCertificate.Enabled` in `appsettings.json` is `true` the following API Endpoint results in error 500:
```powershell
New-PSUEndpoint -Url "/app-api/v1.0/Test" -Endpoint { @($true) | ConvertTo-Json -Depth 2 } -Authentication -Role @('Administrator') -ErrorAction "Stop"
```

```
2021-11-16 09:20:35.888 +11:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal.Server.Services.UniversalAuthorizationService.AuthorizedAsync(HttpContext context, String[] roles, Boolean supportChallenge) in D:\a\universal\universal\src\Universal.Server\Services\UniversalAuthorizationService.cs:line 61
   at Universal.Server.Services.ApiService.ExecuteAsync(HttpContext httpContext) in D:\a\universal\universal\src\Universal.Server\Services\ApiService.cs:line 156
   at Universal.Server.Middleware.RoutingMiddleware.Invoke(HttpContext httpContext, IPolicyEvaluator policyEvaluator) in D:\a\universal\universal\src\Universal.Server\Middleware\RoutingMiddleware.cs:line 79
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Universal.Server.Middleware.SwaggerAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\a\universal\universal\src\Universal.Server\Middleware\SwaggerAuthMiddleware.cs:line 42
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in D:\a\universal\universal\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 109
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-11-16 09:20:35.890 +11:00 [WRN] No exception handler was found, rethrowing original exception.
2021-11-16 09:20:35.890 +11:00 [ERR] Connection id "FFFFFFFFFFFFF", Request id "FFFFFFFFFFFFF:000000A1": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal.Server.Services.UniversalAuthorizationService.AuthorizedAsync(HttpContext context, String[] roles, Boolean supportChallenge) in D:\a\universal\universal\src\Universal.Server\Services\UniversalAuthorizationService.cs:line 61
   at Universal.Server.Services.ApiService.ExecuteAsync(HttpContext httpContext) in D:\a\universal\universal\src\Universal.Server\Services\ApiService.cs:line 156
   at Universal.Server.Middleware.RoutingMiddleware.Invoke(HttpContext httpContext, IPolicyEvaluator policyEvaluator) in D:\a\universal\universal\src\Universal.Server\Middleware\RoutingMiddleware.cs:line 79
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Universal.Server.Middleware.SwaggerAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\a\universal\universal\src\Universal.Server\Middleware\SwaggerAuthMiddleware.cs:line 42
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in D:\a\universal\universal\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 109
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
