### ISSUE TITLE
Failed to start server on linux x64 (PowerShell Universal 2.6.2)

### ISSUE THREAD

**Issue by passcodex** [ironmansoftware/powershell-universal#804]
### Steps to Reproduce

1. Download Universal.linux-x64.2.6.2.zip and unzip it.
2. chmod +x ./Universal.Server
3. run ./Universal.Server

### Expected behavior

```console
server started
```

### Actual behavior

```console
server cannot be started

[root@localhost PSU]# ./Universal.Server 
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal.Server.Program.ConfigurationBuilderSetup(IConfigurationBuilder configBuilder, Boolean desktopMode) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 66
   at Universal.Server.Program.CreateHostBuilder(String[] args, Boolean desktopMode) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 159
   at Universal.Server.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 48
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Universal.Server.Program.Main(String[] args) in D:\a\universal\universal\src\Universal.Server\Program.cs:line 43
Aborted (core dumped)
```

### Environment data

**Operating System**:  CentOS Linux release 7.9.2009 (Core)
Linux version 3.10.0-1160.49.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Nov 30 15:51:32 UTC 2021

**PowerShell Universal**: Universal.linux-x64.2.6.2

**Comment by passcodex** [comment]
Universal.linux-x64.**2.6.1** can be started normally

**Comment by passcodex** [comment]
**started 2.6.1 on linux with exception**

2021-12-30 02:35:06 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server localhost:4186:57e8f99d successfully announced in 133.8688 ms
2021-12-30 02:35:06 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server localhost:4186:57e8f99d is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...
2021-12-30 02:35:06 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server localhost:4186:57e8f99d all the dispatchers started
[**14:35:07 ERR] Error registering vault BuiltInLocalVault
[14:35:07 ERR] Exception:
System.Management.Automation.PSInvalidOperationException: Could not load and retrieve module information for module: SecretManagement.JustinGrote.CredMan with error : The module to process 'SecretManagement.JustinGrote.Credman.Extension.dll', listed in field 'ModuleToProcess/RootModule' of module manifest '/root/installer/PSU/Modules/SecretManagement.JustinGrote.CredMan/1.0.0/SecretManagement.JustinGrote.CredMan.Extension/SecretManagement.JustinGrote.CredMan.Extension.psd1' was not processed because no valid module was found in any module directory..
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)**
[14:35:07 DBG] Loading framework from asset directory: /root/.PowerShellUniversal/Dashboard/Frameworks/UniversalDashboard/2.9.9
[14:35:07 DBG] Loading framework from asset directory: /root/.PowerShellUniversal/Dashboard/Frameworks/UniversalDashboard/3.9.0
[14:35:07 DBG] The specified RequiredModules entry 'UniversalDashboard' in the module manifest '/root/.PowerShellUniversal/Dashboard/Components/UniversalDashboard.CodeEditor/1.2.0/UniversalDashboard.CodeEditor.psd1' is invalid. Try again after updating this entry with valid values.
[14:35:07 DBG] The specified RequiredModules entry 'UniversalDashboard' in the module manifest '/root/.PowerShellUniversal/Dashboard/Components/UniversalDashboard.Map/1.0/UniversalDashboard.Map.psd1' is invalid. Try again after updating this entry with valid values.
[14:35:08 DBG] The specified RequiredModules entry 'UniversalDashboard' in the module manifest '/root/.PowerShellUniversal/Dashboard/Components/UniversalDashboard.Charts/1.3.2/UniversalDashboard.Charts.psd1' is invalid. Try again after updating this entry with valid values.
[14:35:08 DBG] Reading configuration file licenses.ps1
[14:35:08 DBG] Reading configuration file accessControls.ps1
[14:35:08 DBG] Reading configuration file tags.ps1
[14:35:08 DBG] Reading configuration file settings.ps1
2021-12-30 02:35:08 [INFO]  (Hangfire.BackgroundJobServer) Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
2021-12-30 02:35:08 [INFO]  (Hangfire.BackgroundJobServer) Using the following options for Hangfire Server:
    Worker count: 10
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2021-12-30 02:35:08 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server localhost:4186:651ee408 successfully announced in 0.0576 ms
2021-12-30 02:35:08 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server localhost:4186:651ee408 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...
2021-12-30 02:35:08 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server localhost:4186:651ee408 all the dispatchers started
