### ISSUE TITLE
Git sync on fresh install is not working

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#993]
### Steps to Reproduce

Fresh install PSU all version above 2.8.0 and then add OneWay and your creds.
Start the PSU service and you will not sync. I have even deleted the Repository folder but still it don't sync

### Expected behavior

```console
Sync git
```

### Actual behavior

```console
Don't sync as it thinks that the Repository folder already exist even if I delete it.
```

### Environment data

2022-02-19 20:07:04.660 +01:00 [ERR] Failed to sync: 'C:/ProgramData/UniversalAutomation/Repository' exists and is not an empty directory    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at UniversalAutomation.Git.GitService.Initialize() in D:\a\universal\universal\src\Universal.Server\Services\GitService.cs:line 140
   at UniversalAutomation.GitSyncService.TrySync() in D:\a\universal\universal\src\Universal.Server\Services\GitSyncService.cs:line 119
   at UniversalAutomation.GitSyncService.Sync() in D:\a\universal\universal\src\Universal.Server\Services\GitSyncService.cs:line 71

**Comment by adamdriscoll** [comment]
Is there anything in the directory after this happens or is it empty? I can't reproduce this one. 

I have removed the repository folder and database. 

![image](https://user-images.githubusercontent.com/1256531/155219317-6b29cc29-31c9-4e15-9fde-48f5e3a94357.png)

I set my appsettings to GitHub with OneWay sync on. 

![image](https://user-images.githubusercontent.com/1256531/155219403-00e42d07-fa6c-4de2-94ab-14f0bbbb0e6a.png)

Then I start up PSU. 

Log output:

```
[14:06:27 DBG] Hosting starting
[14:06:28 DBG] Opening CNG algorithm 'AES' from provider 'null' with chaining mode CBC.[14:06:28 DBG] Opening CNG algorithm 'SHA256' from provider 'null' with HMAC.
[14:06:28 DBG] Using key {ce4fd62a-d0cf-4950-b9ef-3c73f224fbec} as the default key.
[14:06:28 DBG] Key ring with default key {ce4fd62a-d0cf-4950-b9ef-3c73f224fbec} was loaded during application startup.
2022-02-22 02:06:28 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server adamdesk:4200:66aef352 successfully announced in 50.7208 ms      
2022-02-22 02:06:28 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server adamdesk:4200:66aef352 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...      
2022-02-22 02:06:28 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server adamdesk:4200:66aef352 all the dispatchers started
[14:06:29 DBG] Reading configuration file licenses.ps1
[14:06:29 DBG] Reading configuration file accessControls.ps1
[14:06:29 DBG] Reading configuration file tags.ps1
[14:06:29 DBG] Reading configuration file settings.ps1
[14:06:34 DBG] Configured logging.
[14:06:34 DBG] File .universal\variables.ps1 changed. Syncing...
[14:06:34 DBG] Reading configuration file variables.ps1
[14:06:34 DBG] Adding endpoint: (GET) /6
[14:06:34 DBG] Adding endpoint: (GET) /7
[14:06:34 DBG] Adding endpoint: (GET) /8
[14:06:34 DBG] Adding endpoint: (GET) /9
[14:06:34 DBG] Adding endpoint: (GET) /10
[14:06:34 DBG] Adding endpoint: (GET) /11
[14:06:34 DBG] Adding endpoint: (GET) /12
[14:06:34 DBG] Adding endpoint: (GET) /13
[14:06:34 DBG] Adding endpoint: (GET) /14
[14:06:34 DBG] Adding endpoint: (GET) /15
[14:06:34 DBG] Adding endpoint: (GET) /16
[14:06:34 DBG] Adding endpoint: (GET) /17
[14:06:34 DBG] Adding endpoint: (GET) /18
[14:06:34 DBG] Adding endpoint: (GET) /19
[14:06:34 DBG] Adding endpoint: (GET) /20
[14:06:34 DBG] Adding endpoint: (GET) /21
[14:06:34 DBG] Adding endpoint: (GET) /22
[14:06:34 DBG] Adding endpoint: (GET) /23
[14:06:34 DBG] Adding endpoint: (GET) /24
[14:06:34 DBG] Adding endpoint: (GET) /25
[14:06:34 DBG] Adding endpoint: (GET) /26
[14:06:34 DBG] Adding endpoint: (GET) /sync
[14:06:34 DBG] File PNP.ps1 changed. Syncing...
[14:06:34 DBG] Reading configuration file dashboards.ps1
[14:06:34 DBG] Reading configuration file scripts.ps1
[14:06:34 DBG] File Startup.ps1 changed. Syncing...
[14:06:34 DBG] Reading configuration file dashboards.ps1
[14:06:34 DBG] Reading configuration file scripts.ps1
[14:06:34 DBG] File Stuff.ps1 changed. Syncing...
[14:06:34 DBG] Reading configuration file dashboards.ps1
[14:06:34 DBG] Reading configuration file scripts.ps1
[14:06:34 DBG] File dashboards changed. Syncing...
[14:06:34 DBG] Reading configuration file dashboards.ps1
[14:06:34 DBG] File dashboards\dashboard changed. Syncing...
[14:06:34 DBG] Reading configuration file dashboards.ps1
[14:06:34 DBG] File dashboards\dashboard\dashboard.ps1 changed. Syncing...
[14:06:34 DBG] Reading configuration file dashboards.ps1
[14:06:35 DBG] File pages changed. Syncing...
[14:06:35 DBG] Reading configuration file dashboards.ps1
[14:06:35 DBG] File pages\Test.xml changed. Syncing...
[14:06:35 DBG] Reading configuration file dashboards.ps1
[14:06:35 INF] Latest commit Id: a955ede7c1b1e15a80f118ecafb97eadb64f2bf2, Number of changes since last sync: 19
[14:06:35 DBG] Sync took: 00:00:02.3413263
[14:06:35 INF] Sync done. Status Id: 1
2022-02-22 02:06:35 [INFO]  (Hangfire.BackgroundJobServer) Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
2022-02-22 02:06:35 [INFO]  (Hangfire.BackgroundJobServer) Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2022-02-22 02:06:35 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server adamdesk:4200:2bf32914 successfully announced in 0.1395 ms       
2022-02-22 02:06:35 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server adamdesk:4200:2bf32914 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...      
[14:06:35 DBG] Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
2022-02-22 02:06:35 [INFO]  (Hangfire.Server.BackgroundServerProcess) Server adamdesk:4200:2bf32914 all the dispatchers started
[14:06:35 INF] Now listening on: http://[::]:5000
[14:06:35 DBG] Loaded hosting startup assembly Universal.Server
[14:06:35 INF] Application started. Press Ctrl+C to shut down.
[14:06:35 INF] Hosting environment: Production
[14:06:35 INF] Content root path: E:\universal
[14:06:35 DBG] Hosting started
[14:06:35 DBG] Agent Output: 
[14:06:36 DBG] Agent Output: 
```

It seems to work fine and I see the folder is now populated. 

![image](https://user-images.githubusercontent.com/1256531/155219528-3416e2d4-185c-4985-a0ad-fdd3f57e6e1f.png)

**Comment by rwidmark** [comment]
Nothing the folder was empty, I did not remove the database however.

It just populated the folder with the default Conponents etc as I always do.
As far as I could tell it was the issue, when I started PSU it did copy the components folder etc before the git sync did run.

Work a round was to delay that so maybe you can do something like that as default?

I could not reproduce this at home either as I have faster internet then at work

@adamdriscoll

**Comment by adamdriscoll** [comment]
Certainly could look at that. It seems like we need to ensure that the git sync happens before anything else takes place in that folder. 

Tonight's nightly build includes a ton more logging around git sync so it might help highlight the issue even better. You'll need to enable debug logging but there is a ton more output.

**Comment by rwidmark** [comment]
@adamdriscoll I have isolated this issue. It only happens when you have slow connection. So if you delay the copying of the PSU component / framework folder a little bit then the issue will be gone.
Don't know if it's possible or if it's a good way to fix the issue. It's not a issue on PSU side but when you have slow connection or high ms then it appear.

**Comment by adamdriscoll** [comment]
We've added a new setting to avoid this issue. You can use the Clone behavior to prevent this from happening. https://docs.powershelluniversal.com/config/git#git-initialization-behavior
